### ISSUE TITLE
[BUG] Occasionally API returning error 400

### ISSUE THREAD

**Issue by SeitiYamatsumi** [FlowiseAI/Flowise#1013]
**Describe the bug**
Hi everyone,

I'm hosting Flowise on an AWS EC2 instance on a docker compose. Occasionally, after a period of inactivity, when I call the API, it returns a 400 error on both Xano and Weweb. In the Flowise server-error.log, I've encountered the following message.

`2023-10-05 19:19:58 [ERROR]: [server]: Error: Request failed with status code 400
Error: Request failed with status code 400
    at createError (/usr/local/lib/node_modules/flowise/node_modules/openai/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/flowise/node_modules/openai/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/flowise/node_modules/openai/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
`

I'm currently running two chatflows for two different clients on a t2.micro instance. Interestingly, only one of the chatflows is giving me this error. When I open the affected chatflow and send a message, it seems to return to normal operation, as if I'm waking it up.

The issue independ of prompt or the characters count, sometimes i send the same message and it returns error on API, but never inside Chatflow editor

Does anyone have any idea of what is causing this issue?

**Comment by Matr1xCode** [comment]
Hello, I also have the same problem and it's very frustrating .... If anyone has an idea of what the problem is, you're very welcome.
