### ISSUE TITLE
[BUG] Chain run errored with error: "Illegal invocation" when using Redis Cache - Version 1.3.7

### ISSUE THREAD

**Issue by vijaykammili** [FlowiseAI/Flowise#1043]
Chain run errored with error: "Illegal invocation" when using Redis Cache in following flow. Text is being inserted into the redis db without any issues but the output from the chat interface isn't working.

<img width="1449" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/121184261/1366b97e-2c43-435c-8ac6-9b50d6d66650">

Error:

TypeError: Illegal invocation
    at handleWriteReq (node:internal/stream_base_commons:61:21)
    at writeGeneric (node:internal/stream_base_commons:149:15)
    at Socket._writeGeneric (node:net:962:11)
    at Socket._write (node:net:974:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at EventEmitter.sendCommand (/usr/src/packages/node_modules/ioredis/built/Redis.js:394:29)
    at EventEmitter.get (/usr/src/packages/node_modules/ioredis/built/utils/Commander.js:90:25)

**Comment by HenryHengZJ** [comment]
this pr should fix that - https://github.com/FlowiseAI/Flowise/pull/1053

**Comment by vijaykammili** [comment]
Thank you very much @HenryHengZJ.
