### ISSUE TITLE
[BUG] this.pineconeIndex.namespace is not a function - Version 1.3.8

### ISSUE THREAD

**Issue by vijaykammili** [FlowiseAI/Flowise#1045]
[BUG] this.pineconeIndex.namespace is not a function - Version 1.3.8. This issue wasn't seen in 1.3.7. We updated to 1.3.8 and it broke all existing flows that use pinecone (This is for gcp-starter) project. 

<img width="353" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/121184261/fe56b3d7-9ef7-4c29-a1ea-f941d5497160">

Existing Flow: 

<img width="1047" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/121184261/88d18f2f-16ff-4988-8929-c28ed9ab1696">

**Comment by hemati** [comment]
Same issue here. this is the stacktrace:

```bash
 [chain/error] [1:chain:ConversationalRetrievalQAChain] [841ms] Chain run errored with error: "this.pineconeIndex.namespace is not a function"
 2023-10-12 17:20:15 [ERROR]: [server]: Error: this.pineconeIndex.namespace is not a function
 TypeError: this.pineconeIndex.namespace is not a function
     at PineconeStore.similaritySearchVectorWithScore (/home/wahed/git/Flowise/node_modules/langchain/dist/vectorstores/pinecone.cjs:182:46)
     at PineconeStore.similaritySearch (/home/wahed/git/Flowise/node_modules/langchain/dist/vectorstores/base.cjs:107:36)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
     at async VectorStoreRetriever.getRelevantDocuments (/home/wahed/git/Flowise/node_modules/langchain/dist/schema/retriever.cjs:69:29)
     at async ConversationalRetrievalQAChain._call (/home/wahed/git/Flowise/node_modules/langchain/dist/chains/conversational_retrieval_chain.cjs:140:22)
     at async ConversationalRetrievalQAChain.call (/home/wahed/git/Flowise/node_modules/langchain/dist/chains/base.cjs:104:28)
     at async ConversationalRetrievalQAChain_Chains.run (/home/wahed/git/Flowise/packages/components/dist/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.js:164:25)
     at async App.processPrediction (/home/wahed/git/Flowise/packages/server/dist/index.js:876:19)
     at async /home/wahed/git/Flowise/packages/server/dist/index.js:645:13
```

**Comment by hemati** [comment]
If you do a clean build, it will work again:

```bash
yarn clean
rm -rf node_modules yarn.lock
yarn install
yarn build
```

**Comment by HenryHengZJ** [comment]
yep we have to do a clean build to make it work, this was the PR - https://github.com/FlowiseAI/Flowise/pull/1044

**Comment by vijaykammili** [comment]
Thank you both. I'll give it a try.
