### ISSUE TITLE
[BUG] Issue for connect to Azure Open AI "LLM run errored with error: "Connection error.""

### ISSUE THREAD

**Issue by Bramiproject** [FlowiseAI/Flowise#1097]
Any issue for connect to Azure Open AI
LLM run errored with error: "Connection error."

im installed in docker container

![image](https://github.com/FlowiseAI/Flowise/assets/29449811/57a9a00a-ad41-4d6c-ace2-48e316eb0cc9)

![image](https://github.com/FlowiseAI/Flowise/assets/29449811/5a5572a8-98ab-418a-b3da-4473022ed7d7)

Please you're advices

**Comment by HenryHengZJ** [comment]
can you double check if you can make connection to Azure using API outside of Flowise? Docs - https://docs.flowiseai.com/chat-models/azure-chatopenai

**Comment by Bramiproject** [comment]
Previously I ran no problem, but now there is an issue, is this related to the Docker environment?

**Comment by Bramiproject** [comment]
Hi @HenryHengZJ can you run flowise using proxy ?

**Comment by chz8494** [comment]
+1
The chat models and chains can be modified easily to use proxy, but those
which relies on langchain is really kinda annoying, I have to change pkg in
sub dist…

**Comment by Bramiproject** [comment]
can you any sample for this, regarding to use proxy or Flowise support configure for proxy ?
my problem in proxy when request to azure with langchain.

**Comment by Bramiproject** [comment]
> can you any sample for this, regarding to use proxy or Flowise support configure for proxy ? my problem in proxy when request to azure with langchain.

can you help me @chz8494 or @HenryHengZJ

**Comment by mvenkatsriram** [comment]
Any fixes we made on flowwise behind proxy. We are getting same proxy issue in docker.

**Comment by mikeleedaily** [comment]
Hey @Bramiproject @HenryHengZJ I have encountered same problem. when I search up the discord it seems like there are people who face the same problem but remained unsolved. Any guidance on how to solve the problem?

(Plus I kinda feel like people in China using VPN encounters this problem. I'm using Flowise with VPN in China and the other guy from discord profile contains some Chinese character, thus assuming he's the same too)

**Comment by IzzyHibbert** [comment]
Same issue. 
Catching it inside of a Docker image with latest version (didn't experience anything similar months ago..)

```
2024-03-15 17:16:01 2024-03-15 16:16:01 [INFO]: ⬆️ POST /api/v1/chatflows
2024-03-15 17:16:32 2024-03-15 16:16:32 [INFO]: ⬆️ POST /api/v1/internal-prediction/3d1e72ab-fb43-47f5-840d-9b277d0cc34c
2024-03-15 17:18:19 2024-03-15 16:18:19 [ERROR]: Connection error.
2024-03-15 17:18:19 Error: Connection error.
2024-03-15 17:18:19     at OpenAI.makeRequest (/usr/local/lib/node_modules/flowise/node_modules/openai/core.js:292:19)
2024-03-15 17:18:19     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-15 17:18:19     at async /usr/local/lib/node_modules/flowise/node_modules/@langchain/openai/dist/embeddings.cjs:255:29
2024-03-15 17:18:19     at async RetryOperation._fn (/usr/local/lib/node_modules/flowise/node_modules/p-retry/index.js:50:12)
2024-03-15 17:18:19 2024-03-15 16:18:19 [ERROR]: [server]: Error: Error: Connection error.
2024-03-15 17:18:19 Error: Error: Connection error.
2024-03-15 17:18:19     at buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:326:19)
2024-03-15 17:18:19     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-15 17:18:19     at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1898:40)
2024-03-15 17:18:19     at async /usr/local/lib/node_modules/flowise/dist/index.js:1265:13
```

IT happens that Flowise doesn't even perform the calls (I am usng a LOCALAI model and have access to the log)

**Comment by vinamrajais** [comment]
Same issue

2024-03-16 08:38:17 [INFO]: ⬆️ POST /api/v1/internal-prediction/b9b72ef9-c9af-4b73-ae4e-60c86d5ca096
2024-03-16 08:39:36 [ERROR]: Connection error.
Error: Connection error.
    at OpenAI.makeRequest (/LLMs/Flowise/node_modules/.pnpm/openai@4.28.4/node_modules/openai/core.js:292:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /LLMs/Flowise/node_modules/.pnpm/@langchain+openai@0.0.14/node_modules/@langchain/openai/dist/embeddings.cjs:255:29
    at async RetryOperation._fn (/LLMs/Flowise/node_modules/.pnpm/p-retry@4.6.2/node_modules/p-retry/index.js:50:12)
2024-03-16 08:39:36 [ERROR]: [server]: Error: Error: Connection error.
Error: Error: Connection error.
    at buildFlow (/LLMs/Flowise/packages/server/dist/utils/index.js:326:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async App.buildChatflow (/LLMs/Flowise/packages/server/dist/index.js:1898:40)
    at async /LLMs/Flowise/packages/server/dist/index.js:1265:13

**Comment by Fanxi1992** [comment]
Error: Connection error.
    at OpenAI.makeRequest (C:\Users\15680\AppData\Roaming\npm\node_modules\flowise\node_modules\openai\core.js:292:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\15680\AppData\Roaming\npm\node_modules\flowise\node_modules\@langchain\openai\dist\llms.cjs:475:29
    at async RetryOperation._fn (C:\Users\15680\AppData\Roaming\npm\node_modules\flowise\node_modules\p-retry\index.js:50:12)
    
    same question, i'm in China too, who knows how to fix it? crying......

**Comment by vinamrajais** [comment]
@Bramiproject @IzzyHibbert @Fanxi1992 I see this ticket is open from some time. Anyone of you able to resolve it?

**Comment by vinamrajais** [comment]
Its working now.
Issue was with OpenAI APIs access quota, I have to buy a plan to able to use APIs. Others pls check if you can access openAI APIs

**Comment by automaton82** [comment]
Related to https://github.com/FlowiseAI/Flowise/issues/2077 ?

**Comment by Fanxi1992** [comment]
havn't, i gave up using flowise finally. I am now establishing my own
application by coding by myself.

wangyuwei ***@***.***> 于2024年6月3日周一 19:21写道：

**Comment by mikeleedaily** [comment]
In my case, I have set another computer of mine out of China and use teamviewer to access it lol
