### ISSUE TITLE
[BUG]TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by LiKe-rm** [FlowiseAI/Flowise#1106]
**Describe the bug**
I select Local QnA in the marketplace, fill out the basepath and model name for ChatLocalAI and LocalAIembeeding, upload the txt file, save it and talk to it, and it reports an error TypeError: Cannot read properties of undefined ( read 'replace')

**To Reproduce**

1. Use Local QnA
2. fill out the basepath and model name for ChatLocalAI and LocalAIembeeding
3. upload the txt file
4. chat and you will see the erro

**Expected behavior**
normal conversation.

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/72687314/0859c626-13a7-4f78-a9f8-d9493526c8b5)

**Additional context**
Couldn't you use flowise to load a local model?

**Comment by jpcorso** [comment]
I'm having the same trouble here wile making a chat with a file

**Comment by LordOfTheRats** [comment]
Same here

**Comment by HenryHengZJ** [comment]
is this only happening for LocalAI?

**Comment by LiKe-rm** [comment]
It seems that "Base Path" + "Module Name" should locate the model bin file, but what should I do if there are multiple bin files? For example "pytorch_model-00001-of-00002.bin", "pytorch_model-00002-of-00002.bin".

**Comment by LiKe-rm** [comment]
> is this only happening for LocalAI?

It looks like this, when I replace ChatLocalAI, LocalAI Embedding with ChatOpenAI, OpenAI Embedding, it works fine

**Comment by gboxxx** [comment]
I'm getting this error using OpenAI embeddings & ChatOpenAI - using the Conversational QnA Marketplace template (with Text File updated to version 2).

**Comment by pinyhagt** [comment]
I'm having the same issue. Running Flowise on my local machine with OpenAI and Pinecone.

![image](https://github.com/FlowiseAI/Flowise/assets/147110829/3f78eacb-fa1a-44a8-9e03-3bd4210dbd67)

**Comment by HenryHengZJ** [comment]
https://github.com/FlowiseAI/Flowise/pull/1127 this should fixed it! feel free to reopen if issue still persists

**Comment by mario6464** [comment]
Hi, I get the error "Cannot read properties of undefined (reading 'replace')" using a Conversational Retrieval QA Chain, Pinecone, OpenAI Embeddings, Cheerio Web Scraper, and a HTMLMarkdown Text Splitter. When I Upsert directly from the Flowise Canvas - I experience the issue. When I add memory, the issue goes away in the canvas.

When I hit the endpoint via POSTMAN and try to pass a URL to to the url parameter of Cheerio Web Scraper, I get the same error. Adding memory key value pairs in the body does not resolve the issue on my end. 

![image](https://github.com/FlowiseAI/Flowise/assets/147570897/79da8809-4854-4d89-86a8-fe3cf2785322)


In LangSmith, this is what I see:

`Cannot read properties of undefined (reading 'replace')

TypeError: Cannot read properties of undefined (reading 'replace')
    at OpenAIEmbeddings.embedQuery (/usr/src/node_modules/.pnpm/@langchain+openai@0.0.14/node_modules/@langchain/openai/dist/embeddings.cjs:206:46)
    at PineconeStore.similaritySearch (/usr/src/node_modules/.pnpm/@langchain+core@0.1.44/node_modules/@langchain/core/dist/vectorstores.cjs:108:90)
    at VectorStoreRetriever._getRelevantDocuments (/usr/src/node_modules/.pnpm/@langchain+core@0.1.44/node_modules/@langchain/core/dist/vectorstores.cjs:71:33)
    at VectorStoreRetriever.getRelevantDocuments (/usr/src/node_modules/.pnpm/@langchain+core@0.1.44/node_modules/@langchain/core/dist/retrievers.cjs:70:40)
    at async VectorStoreRetriever._streamIterator (/usr/src/node_modules/.pnpm/@langchain+core@0.1.44/node_modules/@langchain/core/dist/runnables/base.cjs:151:9)
    at async VectorStoreRetriever.transform (/usr/src/node_modules/.pnpm/@langchain+core@0.1.44/node_modules/@langchain/core/dist/runnables/base.cjs:344:9)
    at async RunnableSequence._streamIterator (/usr/src/node_modules/.pnpm/@langchain+core@0.1.44/node_modules/@langchain/core/dist/runnables/base.cjs:1084:30)`

I updated my flowise branch but I continue to experience the same issue
