### ISSUE TITLE
[BUG]TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by Ares0101** [FlowiseAI/Flowise#1123]
2023-10-24 15:01:50 [ERROR]: Cannot read properties of undefined (reading 'replace')
TypeError: Cannot read properties of undefined (reading 'replace')
    at /home/huiyu/Flowise/node_modules/langchain/dist/embeddings/openai.cjs:142:92
    at Array.map (<anonymous>)
    at OpenAIEmbeddings.embedDocuments (/home/huiyu/Flowise/node_modules/langchain/dist/embeddings/openai.cjs:142:79)
    at MemoryVectorStore.addDocuments (/home/huiyu/Flowise/node_modules/langchain/dist/vectorstores/memory.cjs:41:54)
    at MemoryVectorStore.fromDocuments (/home/huiyu/Flowise/node_modules/langchain/dist/vectorstores/memory.cjs:129:24)
    at InMemoryVectorStore_VectorStores.init (/home/huiyu/Flowise/packages/components/dist/nodes/vectorstores/InMemory/InMemoryVectorStore.js:62:62)
    at buildLangchain (/home/huiyu/Flowise/packages/server/dist/utils/index.js:223:72)
    at async App.processPrediction (/home/huiyu/Flowise/packages/server/dist/index.js:822:40)
    at async /home/huiyu/Flowise/packages/server/dist/index.js:609:13
2023-10-24 15:01:50 [ERROR]: [server]: Error: TypeError: Cannot read properties of undefined (reading 'replace')
Error: TypeError: Cannot read properties of undefined (reading 'replace')
    at buildLangchain (/home/huiyu/Flowise/packages/server/dist/utils/index.js:235:19)
    at async App.processPrediction (/home/huiyu/Flowise/packages/server/dist/index.js:822:40)
    at async /home/huiyu/Flowise/packages/server/dist/index.js:609:13

**Comment by chz8494** [comment]
I’ve seen this error before, actually very easy fix, it’s actually because of undefined pagecontent in document, only need one line, such as if doc.pagecontent !== undefined
