### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Terrdi** [FlowiseAI/Flowise#1155]
**Describe the bug**
I can't install flowise with npm.

**To Reproduce**

1. Run 
```sh
sudo npm install -g flowise
```
3. See error
```txt
12204 timing command:install Completed in 558640ms
12205 verbose stack Error: command failed
12205 verbose stack     at ChildProcess.<anonymous> (/opt/nodejs/node-v20.9.0-linux-x64/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
12205 verbose stack     at ChildProcess.emit (node:events:514:28)
12205 verbose stack     at maybeClose (node:internal/child_process:1105:16)
12205 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
12206 verbose pkgid grpc-tools@1.12.4
12207 verbose cwd /opt
12208 verbose Linux 6.2.0-35-generic
12209 verbose node v20.9.0
12210 verbose npm  v10.1.0
12211 error code 1
12212 error path /usr/local/lib/node_modules/flowise/node_modules/grpc-tools
12213 error command failed
12214 error command sh -c node-pre-gyp install
12215 error request to https://node-precompiled-binaries.grpc.io/grpc-tools/v1.12.4/linux-x64.tar.gz failed, reason:
12216 error node-pre-gyp info it worked if it ends with ok
12216 error node-pre-gyp info using node-pre-gyp@1.0.11
12216 error node-pre-gyp info using node@20.9.0 | linux | x64
12216 error node-pre-gyp info check checked for "/usr/local/lib/node_modules/flowise/node_modules/grpc-tools/bin/grpc_tools.node" (not found)
12216 error node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc-tools/v1.12.4/linux-x64.tar.gz
12216 error node-pre-gyp ERR! install request to https://node-precompiled-binaries.grpc.io/grpc-tools/v1.12.4/linux-x64.tar.gz failed, reason:  
12216 error node-pre-gyp ERR! install error 
12216 error node-pre-gyp ERR! stack FetchError: request to https://node-precompiled-binaries.grpc.io/grpc-tools/v1.12.4/linux-x64.tar.gz failed, reason: 
12216 error node-pre-gyp ERR! stack     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/node-fetch/lib/index.js:1501:11)
12216 error node-pre-gyp ERR! stack     at ClientRequest.emit (node:events:514:28)
12216 error node-pre-gyp ERR! stack     at TLSSocket.socketErrorListener (node:_http_client:495:9)
12216 error node-pre-gyp ERR! stack     at TLSSocket.emit (node:events:514:28)
12216 error node-pre-gyp ERR! stack     at emitErrorNT (node:internal/streams/destroy:151:8)
12216 error node-pre-gyp ERR! stack     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
12216 error node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
12216 error node-pre-gyp ERR! System Linux 6.2.0-35-generic
12216 error node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/flowise/node_modules/.bin/node-pre-gyp" "install"
12216 error node-pre-gyp ERR! cwd /usr/local/lib/node_modules/flowise/node_modules/grpc-tools
12216 error node-pre-gyp ERR! node -v v20.9.0
12216 error node-pre-gyp ERR! node-pre-gyp -v v1.0.11
12216 error node-pre-gyp ERR! not ok
12217 verbose exit 1
12218 timing npm Completed in 558703ms
12219 verbose unfinished npm timer reify 1698671108294
12220 verbose unfinished npm timer reify:build 1698671664952
12221 verbose unfinished npm timer build 1698671664953
12222 verbose unfinished npm timer build:deps 1698671664954
12223 verbose unfinished npm timer build:run:install 1698671664974
12224 verbose unfinished npm timer build:run:install:node_modules/flowise/node_modules/canvas 1698671664978
12225 verbose unfinished npm timer build:run:install:node_modules/flowise/node_modules/faiss-node 1698671664979
12226 verbose unfinished npm timer build:run:install:node_modules/flowise/node_modules/grpc-tools 1698671664980
12227 verbose unfinished npm timer build:run:install:node_modules/flowise/node_modules/sqlite3 1698671664982
12228 verbose unfinished npm timer build:run:install:node_modules/flowise/node_modules/flowise-components/node_modules/faiss-node 1698671664984
12229 verbose code 1
12230 error A complete log of this run can be found in: /root/.npm/_logs/2023-10-30T13_05_08_232Z-debug-0.log

```

**Expected behavior**
Install Successfully.

**Comment by DigYang** [comment]
me too

**Comment by EnochAbassey** [comment]
Which OS???   If linux try updating your os packages. Example, do apt update or apt-get update for ubuntu. Hope this helps.
