### ISSUE TITLE
[BUG] Error adding vectors' Error: invalid usage: need at least one object to send a request, add one with .withObject(obj)

### ISSUE THREAD

**Issue by netandreus** [FlowiseAI/Flowise#1170]
**Describe the bug**
Try to use ```Pdf File loader``` for just single pdf without success.

**To Reproduce**
I'm trying from chat and from console.

```
curl --location 'http://localhost:3000/api/v1/prediction/de45996c-c935-4e3f-aa73-716bbc667b32' \
--header 'Authorization: Bearer xxxxxxxxxxxx=' \
--form 'files=@"/Users/andrey/sandbox/llm/current/data/coal_contract.pdf"' \
--form 'chunkSize="200"' \
--form 'chunkOverlap="20"' \
--form 'metadata="{\"name\": \"coal_contract.pdf\"}"' \
--form 'question="What is the subject of contract?"'
```

and got an error:
```
Error adding vectors' Error: invalid usage: need at least one object to send a request, add one with .withObject(obj)
```

**Expected behavior**
Added embeddings.

**Screenshots**
<img width="1552" alt="flowise_error_adding_vectors" src="https://github.com/FlowiseAI/Flowise/assets/313477/89ea9ab6-31c7-4cf7-90d1-b2ddec5ec5fd">

**Flow**
[weaviate_ingest_pdf Chatflow.json](https://github.com/FlowiseAI/Flowise/files/13225212/weaviate_ingest_pdf.Chatflow.json)

**Setup**
-   Installation: Docker version 24.0.6, build ed223bc
-   Flowise Version flowise@1.3.8
-   OS: MacOS Ventura 13.5.2
-   Browser Chrome / console

**Additional context**

**Comment by DevKhare1999** [comment]
I am having the same issue
[netandreus](https://github.com/netandreus)

This is my workflow

<img width="589" alt="Untitled" src="https://github.com/user-attachments/assets/10bcb5cc-a2c5-410d-8561-103fd9bb19e5" />

When I try to make the POST call on python 

              import requests
              
              API_URL = "http://localhost:3000/api/v1/vector/upsert/7a9a57fd-92c5-4020-a7b1-ab34b802a730"
              
              # use form data to upload files
              form_data = {
                  "files": ('ExportData.json', open('ExportData.json', 'rb'))
              }
              body_data = {
                  "encodingName": "ExportData.json",
                  "chunkSize": 1,
                  "chunkOverlap": 1,
              }
              
              def query(form_data, body_data):
                  response = requests.post(API_URL, files=form_data, data=body_data)
                  return response.json()
              
              output = query(form_data, body_data)

I get the following response body
{'statusCode': 500,
 'success': False,
 'message': 'Error: vectorsService.upsertVector - Error: Error: Error adding vectors: Error: invalid usage: need at least one object to send a request, add one with .withObject(obj)',
 'stack': {}}
 
 The error log in Flowise is provided below:
 
 [ERROR]: Error: Error adding vectors: Error: invalid usage: need at least one object to send a request, add one with .withObject(obj)
2025-01-09 12:40:53 Error: Error: Error adding vectors: Error: invalid usage: need at least one object to send a request, add one with .withObject(obj)
2025-01-09 12:40:53     at Weaviate_VectorStores.upsert (/usr/src/packages/components/dist/nodes/vectorstores/Weaviate/Weaviate.js:93:27)
2025-01-09 12:40:53     at async buildFlow (/usr/src/packages/server/dist/utils/index.js:423:37)
2025-01-09 12:40:53     at async upsertVector (/usr/src/packages/server/dist/utils/upsertVector.js:169:32)
2025-01-09 12:40:53     at async Object.upsertVectorMiddleware (/usr/src/packages/server/dist/services/vectors/index.js:9:16)
2025-01-09 12:40:53     at async upsertVectorMiddleware (/usr/src/packages/server/dist/controllers/vectors/index.js:18:29)
2025-01-09 12:40:53 2025-01-09 08:40:53 [ERROR]: [server]: Error: Error: Error: Error adding vectors: Error: invalid usage: need at least one object to send a request, add one with .withObject(obj)
2025-01-09 12:40:53 Error: Error: Error: Error adding vectors: Error: invalid usage: need at least one object to send a request, add one with .withObject(obj)
2025-01-09 12:40:53     at buildFlow (/usr/src/packages/server/dist/utils/index.js:499:19)
2025-01-09 12:40:53     at async upsertVector (/usr/src/packages/server/dist/utils/upsertVector.js:169:32)
2025-01-09 12:40:53     at async Object.upsertVectorMiddleware (/usr/src/packages/server/dist/services/vectors/index.js:9:16)
2025-01-09 12:40:53     at async upsertVectorMiddleware (/usr/src/packages/server/dist/controllers/vectors/index.js:18:29)
