### ISSUE TITLE
[BUG] 1.35 up 1.39

### ISSUE THREAD

**Issue by pangzheng** [FlowiseAI/Flowise#1186]
docker update

run service  log view

```
docker-flowise-1  | 2023-11-07 04:38:18 [ERROR]: Error: Credentials could not be decrypted.
docker-flowise-1  | Error: Error: Credentials could not be decrypted.
docker-flowise-1  |     at getCredentialData (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/src/utils.js:476:15)
docker-flowise-1  |     at async ChatOpenAI_ChatModels.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chatmodels/ChatOpenAI/ChatOpenAI.js:144:32)
docker-flowise-1  |     at async buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:223:50)
docker-flowise-1  |     at async App.processPrediction (/usr/local/lib/node_modules/flowise/dist/index.js:918:40)
docker-flowise-1  |     at async /usr/local/lib/node_modules/flowise/dist/index.js:642:13
docker-flowise-1  | 2023-11-07 04:38:18 [ERROR]: [server]: Error: Error: Error: Credentials could not be decrypted.
```

**Comment by pangzheng** [comment]
clean Credentials 

run service log view

docker-flowise-1  | 2023-11-07 04:43:08 [ERROR]: OpenAI or Azure OpenAI API key not found
docker-flowise-1  | Error: OpenAI or Azure OpenAI API key not found
docker-flowise-1  |     at new ChatOpenAI (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/chat_models/openai.cjs:288:19)
docker-flowise-1  |     at ChatOpenAI_ChatModels.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chatmodels/ChatOpenAI/ChatOpenAI.js:174:23)
docker-flowise-1  |     at async buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:223:50)
docker-flowise-1  |     at async App.processPrediction (/usr/local/lib/node_modules/flowise/dist/index.js:918:40)
docker-flowise-1  |     at async /usr/local/lib/node_modules/flowise/dist/index.js:642:13

**Comment by pangzheng** [comment]
update docker-compose.yml & .env is work
