### ISSUE TITLE
[BUG]  Failed to parse function arguments from chat model response

### ISSUE THREAD

**Issue by kientv** [FlowiseAI/Flowise#1242]
https://github.com/langchain-ai/langchainjs/issues/2322

`flowise-flowise-1  | 2023-11-16 17:30:22 [ERROR]: [server]: Error: Failed to parse function arguments from chat model response. Text: "{
flowise-flowise-1  |   "fromEmail": "support@mitiga.vn",
flowise-flowise-1  |   "toEmail": "kientranvan@gmail.com",
flowise-flowise-1  |   "subject": "Nhắc Gia hạn Server",
flowise-flowise-1  |   "content": "Xin chào anh Trần Văn Kiên,\n\nChúng tôi xin thông báo rằng dịch vụ Server của anh sẽ hết hạn vào ngày 20-11-2023. Chúng tôi khuyến nghị anh gia hạn dịch vụ để đảm bảo tiếp tục sử dụng một cách liên tục và ổn định.\n\nNếu anh có bất kỳ câu hỏi hay cần hỗ trợ gì, xin vui lòng". SyntaxError: Unexpected end of JSON input
flowise-flowise-1  | Error: Failed to parse function arguments from chat model response. Text: "{
flowise-flowise-1  |   "fromEmail": "****example****",
flowise-flowise-1  |   "toEmail": "****example****",
flowise-flowise-1  |   "subject": "****example****",
flowise-flowise-1  |   "content": "****example****". SyntaxError: Unexpected end of JSON input
flowise-flowise-1  |     at parseOutput (/usr/src/packages/node_modules/langchain/dist/agents/openai/index.cjs:32:19)
flowise-flowise-1  |     at OpenAIAgent.plan (/usr/src/packages/node_modules/langchain/dist/agents/openai/index.cjs:176:16)
flowise-flowise-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
flowise-flowise-1  |     at async AgentExecutor._call (/usr/src/packages/node_modules/langchain/dist/agents/executor.cjs:144:26)
flowise-flowise-1  |     at async AgentExecutor.call (/usr/src/packages/node_modules/langchain/dist/chains/base.cjs:104:28)
flowise-flowise-1  |     at async AgentExecutor.run (/usr/src/packages/node_modules/langchain/dist/chains/base.cjs:69:30)
flowise-flowise-1  |     at async OpenAIFunctionAgent_Agents.run (/usr/src/packages/packages/components/dist/nodes/agents/OpenAIFunctionAgent/OpenAIFunctionAgent.js:77:28)
flowise-flowise-1  |     at async App.processPrediction (/usr/src/packages/packages/server/dist/index.js:1212:19)
flowise-flowise-1  |     at async /usr/src/packages/packages/server/dist/index.js:915:13
flowise-flowise-1  | 2023-11-16 17:31:29 [ERROR]: [server]: Error: Request timed out.
flowise-flowise-1  | TimeoutError: Request timed out.
flowise-flowise-1  |     at wrapOpenAIClientError (/usr/src/packages/node_modules/langchain/dist/util/openai.cjs:9:17)
flowise-flowise-1  |     at /usr/src/packages/node_modules/langchain/dist/chat_models/openai.cjs:521:69
flowise-flowise-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
flowise-flowise-1  |     at async RetryOperation._fn (/usr/src/packages/node_modules/p-retry/index.js:50:12)
`

**Comment by HenryHengZJ** [comment]
are u using openai function agent?

**Comment by kientv** [comment]
> are u using openai function agent?

Yes

**Comment by HenryHengZJ** [comment]
can you do a step by step guide so that we can replicate the issue

**Comment by kientv** [comment]
> can you do a step by step guide so that we can replicate the issue

I create chatflow with:
1. OpenAI function agent
2. Using Retrieval tool (custom tool) to query related data from chroma existing upsert.
3. Using send_mailgrid (custom tool).

**Comment by kientv** [comment]
The same with **Conversational retrieval agent**:
![image](https://github.com/FlowiseAI/Flowise/assets/3217438/baca8a03-7f1f-4823-9da8-3ec55bd23b25)
