### ISSUE TITLE
[BUG] Unable to set credentials on Elastic node in version 1.4.5

### ISSUE THREAD

**Issue by tirongi** [FlowiseAI/Flowise#1367]
On new and deprecated Elastic nodes it is not possible to set/create credentials.

The bug appear by using the latest version of Flowise (1.4.5).
Everything is ok in 1.4.4

**To Reproduce**
Add a new Elastic node into a chatflow or open a chatflow containing an existing Elastic node.

Message from debug window:
TypeError: this.buffer.charCodeAt is not a function
    at Tokenizer.parse (/home//git_cloned/Flowise/node_modules/htmlparser2/lib/Tokenizer.js:745:33)
    at Tokenizer.write (/home//git_cloned/Flowise/node_modules/htmlparser2/lib/Tokenizer.js:159:14)
    at Parser.write (/home//git_cloned/Flowise/node_modules/htmlparser2/lib/Parser.js:459:28)
    at sanitizeHtml (/home//git_cloned/Flowise/node_modules/sanitize-html/index.js:600:10)
    at sanitizeMiddleware (/home//git_cloned/Flowise/packages/server/dist/utils/XSS.js:13:52)
    at Layer.handle [as handle_request] (/home//git_cloned/Flowise/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home//git_cloned/Flowise/node_modules/express/lib/router/index.js:328:13)
    at /home//git_cloned/Flowise/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home//git_cloned/Flowise/node_modules/express/lib/router/index.js:346:12)
    at next (/home//git_cloned/Flowise/node_modules/express/lib/router/index.js:280:10)

**Comment by emrahtoy** [comment]
Related with [this issue](https://github.com/FlowiseAI/Flowise/issues/1360) 
This should be fixed with the last merge.
@HenryHengZJ

**Comment by tirongi** [comment]
> Related to [this issue](https://github.com/FlowiseAI/Flowise/issues/1360) This should have already been fixed with the last merge. @HenryHengZJ

Now, with the fix, the node is able to list and choose the already stored credentials, though it is not possible to use the "create new" to set a new credential.

Going there you simply have the "create new" plain text reported into the textbox and the following error in debug:

Error: Credential amp;elasticSearchUserPassword not found
    at /home/git_cloned/Flowise/packages/server/dist/index.js:189:31
    at Layer.handle [as handle_request] (/home/git_cloned/Flowise/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/git_cloned/Flowise/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/git_cloned/Flowise/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/git_cloned/Flowise/node_modules/express/lib/router/layer.js:95:5)
    at /home/git_cloned/Flowise/node_modules/express/lib/router/index.js:284:15
    at param (/home/git_cloned/Flowise/node_modules/express/lib/router/index.js:365:14)
    at param (/home/git_cloned/Flowise/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/home/git_cloned/Flowise/node_modules/express/lib/router/index.js:421:3)
    at next (/home/git_cloned/Flowise/node_modules/express/lib/router/index.js:280:10)
