### ISSUE TITLE
Flowise Issues - Docker Container Version

### ISSUE THREAD

**Issue by mvenkatsriram** [FlowiseAI/Flowise#1392]
I am trying to install Flowise in on premise server using docker compose.

Internet access via corporate proxy. The application loads fine, but it unable to make any outbound requests. 

Ex: Cheerio Webscrapper or OpenAI or HuggingFace.

But the curl requests are successful. Is there a restriction in running Flowise in On-Prem machines and connect via Proxy.

Even for very small flows with 3 nodes.  LLM, Prompt Template, LLM Chain. It fails to open once saved.

```
2023-12-14 20:44:29 [INFO]: ⬆️ POST /api/v1/prompts-list
2023-12-14 20:44:29 [ERROR]: unhandledRejection:  Request failed with status code 504
AxiosError: Request failed with status code 504
    at settle (/usr/local/lib/node_modules/flowise/node_modules/axios/dist/node/axios.cjs:1967:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/flowise/node_modules/axios/dist/node/axios.cjs:3062:11)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-12-14 20:44:35 [INFO]: Starting Flowise...
2023-12-14 20:44:35 [INFO]: ⚡️ [server]: Flowise Server is listening at 3000
2023-12-14 20:44:35 [INFO]: 📦 [server]: Data Source has been initialized!
2023-12-14 20:45:38 [INFO]: ⬆️ POST /api/v1/prompts-list
2023-12-14 20:45:38 [ERROR]: unhandledRejection:  Request failed with status code 504
AxiosError: Request failed with status code 504
    at settle (/usr/local/lib/node_modules/flowise/node_modules/axios/dist/node/axios.cjs:1967:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/flowise/node_modules/axios/dist/node/axios.cjs:3062:11)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-12-14 20:45:43 [INFO]: Starting Flowise...
2023-12-14 20:45:43 [INFO]: ⚡️ [server]: Flowise Server is listening at 3000
2023-12-14 20:45:43 [INFO]: 📦 [server]: Data Source has been initialized!
2023-12-14 20:46:20 [INFO]: ⬆️ POST /api/v1/prompts-list
2023-12-14 20:46:20 [ERROR]: unhandledRejection:  Request failed with status code 504
AxiosError: Request failed with status code 504
    at settle (/usr/local/lib/node_modules/flowise/node_modules/axios/dist/node/axios.cjs:1967:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/flowise/node_modules/axios/dist/node/axios.cjs:3062:11)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-12-14 20:46:25 [INFO]: Starting Flowise...
2023-12-14 20:46:25 [INFO]: ⚡️ [server]: Flowise Server is listening at 3000
2023-12-14 20:46:25 [INFO]: 📦 [server]: Data Source has been initialized!
2023-12-14 20:48:04 [INFO]: ⬆️ POST /api/v1/prompts-list
2023-12-14 20:48:04 [ERROR]: unhandledRejection:  Request failed with status code 504
AxiosError: Request failed with status code 504
    at settle (/usr/local/lib/node_modules/flowise/node_modules/axios/dist/node/axios.cjs:1967:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/flowise/node_modules/axios/dist/node/axios.cjs:3062:11)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-12-14 20:48:09 [INFO]: Starting Flowise...
2023-12-14 20:48:09 [INFO]: ⚡️ [server]: Flowise Server is listening at 3000
2023-12-14 20:48:09 [INFO]: 📦 [server]: Data Source has been initialized!
```

```
version: '3.1'
services:
    flowise:
        image: flowiseai/flowise
        restart: always
        environment:
            - HTTP_PROXY=http://172.18.0.1:8888
            - HTTPS_PROXY=http://172.18.0.1:8888
            - http_proxy=http://172.18.0.1:8888
            - https_proxy=http://172.18.0.1:8888
            - DEBUG=true
            - LOG_LEVEL=debug
            - DATABASE_TYPE=postgres
            - DATABASE_NAME=bitnami_flowise
            - DATABASE_HOST=flowise-postgresql
            - DATABASE_PORT=5432
            - DATABASE_USER=bn_flowise
            - DATABASE_PASSWORD=
            - TOOL_FUNCTION_BUILTIN_DEP=*
            - TOOL_FUNCTION_BUILTIN_DEP=fs
            - TOOL_FUNCTION_BUILTIN_DEP=crypto,fs
            - TOOL_FUNCTION_EXTERNAL_DEP=axios,moment
        ports:
            - 20045:3000
        depends_on:
            - flowise-postgresql
        volumes:
            - ~/.flowise:/root/.flowise
            - /etc/localtime:/etc/localtime:ro
        command: /bin/sh -c "sleep 3; flowise start"

    
    flowise-postgresql:
        image: docker.io/bitnami/postgresql:latest
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - POSTGRESQL_USERNAME=bn_flowise
            - POSTGRESQL_DATABASE=bitnami_flowise
        volumes:
            - flowise_postgresql_data:/bitnami/postgresql

volumes: 
    flowise_postgresql_data:
        driver: local

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "192.168.5.0/24"
```

**Comment by HenryHengZJ** [comment]
Flowise is using socketIO for streaming, it might be the connection to SocketIO was blocked due to proxy - [code](https://github.com/FlowiseAI/Flowise/blob/main/packages/server/src/index.ts#L1842)

**Comment by mvenkatsriram** [comment]
This isssue is not with reverse proxy. The problem is with forward proxy.. All outbound calls from FlowWise are failing.
