### ISSUE TITLE
[BUG] while using Conversional Retrieval QA Chain

### ISSUE THREAD

**Issue by ChristianKitte** [FlowiseAI/Flowise#1403]
Hello, I installed version 1.4.5 today and when using the Conversional Retrieval QA Chain I get the error message: Cannot use 'in' operator to search for 'generatePrompt'. First the system works as expected, then aborts with the message.

Error output:
v2023-12-16 17:29:57 [ERROR]: [server]: Error: Cannot use 'in' operator to search for 'generatePrompt' in
TypeError: Cannot use 'in' operator to search for 'generatePrompt' in
    at LLMChain._call (C:\Users\CK\AppData\Roaming\npm\node_modules\flowise\node_modules\langchain\dist\chains\llm_chain.cjs:157:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LLMChain.call (C:\Users\CK\AppData\Roaming\npm\node_modules\flowise\node_modules\langchain\dist\chains\base.cjs:104:28)
    at async LLMChain.predict (C:\Users\CK\AppData\Roaming\npm\node_modules\flowise\node_modules\langchain\dist\chains\llm_chain.cjs:184:24)
    at async ConversationSummaryMemory.predictNewSummary (C:\Users\CK\AppData\Roaming\npm\node_modules\flowise\node_modules\langchain\dist\memory\summary.cjs:72:16)
    at async ConversationSummaryMemory.saveContext (C:\Users\CK\AppData\Roaming\npm\node_modules\flowise\node_modules\langchain\dist\memory\summary.cjs:144:23)
    at async ConversationalRetrievalQAChain.call (C:\Users\CK\AppData\Roaming\npm\node_modules\flowise\node_modules\langchain\dist\chains\base.cjs:120:13)
    at async ConversationalRetrievalQAChain_Chains.run (C:\Users\CK\AppData\Roaming\npm\node_modules\flowise\node_modules\flowise-components\dist\nodes\chains\ConversationalRetrievalQAChain\ConversationalRetrievalQAChain.js:164:25)
    at async App.buildChatflow (C:\Users\CK\AppData\Roaming\npm\node_modules\flowise\dist\index.js:1297:19)
    at async C:\Users\CK\AppData\Roaming\npm\node_modules\flowise\dist\index.js:953:13

**Comment by HenryHengZJ** [comment]
closing the issue for now. Feel free to reopen if issue still persists.
