### ISSUE TITLE
Pupeteer & Playwright [BUG]

### ISSUE THREAD

**Issue by danishmbutt** [FlowiseAI/Flowise#1410]
**Describe the bug**
I can use Cheerio easily with any website. Pupeteer and Playwright are not working. 

**To Reproduce**
Create any workflow with Cheerio Webscraper.
Test with Cheerio.
Then replace cheerio with Playwright

<img width="974" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/77721639/ca20d7b4-1b84-4284-86e9-ba07cba7535c">

**Expected behavior**
The same website should work and pass results to the pinecone db and then the chatbot. 

ERROR Message - TypeError: (intermediate value) is not iterable (cannot read property undefined).

**Screenshots**
N/A

**Setup**
-Docker
- latest Flowise release - downloaded yesterday on render

**Comment by mukundsayeeganesh** [comment]
I am also facing the same issue

**Comment by mikehudson2** [comment]
Same, P & P don't work. But Apify does work.

**Comment by dirien** [comment]
I have the same issue (1.6.0) with Cheerio:

```bash
│ 2024-03-08 10:01:34 [INFO]: ⬆️ POST /api/v1/vector/internal-upsert/10ca0d6d-42c2-4e51-93b6-b5d8a0c8847d                                                                         │
│ 2024-03-08 10:01:44 [ERROR]: (intermediate value) is not iterable (cannot read property undefined)                                                                             │
│ TypeError: (intermediate value) is not iterable (cannot read property undefined)                                                                                               │
│     at Cheerio_DocumentLoaders.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/documentloaders/Cheerio/Cheerio.js:130:22)                 │
│     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                                                              │
│     at async buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:290:36)                                                                                        │
│     at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1503:13)                                                                                      │
│     at async /usr/local/lib/node_modules/flowise/dist/index.js:1112:13                                                                                                         │
│ 2024-03-08 10:01:44 [ERROR]: [server]: Error: TypeError: (intermediate value) is not iterable (cannot read property undefined)                                                 │
│ Error: TypeError: (intermediate value) is not iterable (cannot read property undefined)                                                                                        │
│     at buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:333:19)                                                                                              │
│     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                                                              │
│     at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1503:13)                                                                                      │
│     at async /usr/local/lib/node_modules/flowise/dist/index.js:1112:13
```

**Comment by 4rr0wx** [comment]
I have the same issue. Ive tried lowering the Page numbers and at 300 pages it startet working.
