### ISSUE TITLE
[BUG] PG Vector Store Fetch Failed

### ISSUE THREAD

**Issue by sidhellman** [FlowiseAI/Flowise#1449]
**Describe the bug**
tried to store a document which was almost 80 MB, after increasing the size for files which we can upload at index.ts.
Vector store was Postgres

**To Reproduce**
Simply try to upload a large doc 80MB+ in a postgres DB, locally hosted

**Expected behavior**
Should work easily as ir does with small docs

**error below**

Error: TypeError: fetch failed
    at Postgres_VectorStores.upsert (/root/Flowise/packages/components/dist/nodes/vectorstores/Postgres/Postgres.js:58:27)
    at async buildLangchain (/root/Flowise/packages/server/dist/utils/index.js:273:17)
    at async App.upsertVector (/root/Flowise/packages/server/dist/index.js:1299:13)
    at async /root/Flowise/packages/server/dist/index.js:958:13
2023-12-30 00:43:41 [ERROR]: [server]: Error: Error: TypeError: fetch failed

Any advise ?

**Comment by HenryHengZJ** [comment]
have u tried uploading a smaller file, if that works? `fetch failed` often means its failing to reach the Postgres instance

**Comment by Siddharth1988** [comment]
Yes, on smaller files, works perfectly fine.

**Comment by fejdraus** [comment]
In another reference I wrote a solution to this problem - you need to use node-fetch instead of fetch, since fetch doesn't timeout correctly.
