### ISSUE TITLE
yarn start is failing for data initialization

### ISSUE THREAD

**Issue by hemant-manwani** [FlowiseAI/Flowise#1538]
Hello Thanks a lot for this package - I am using node version 18.15.0 and running it by 

npm install -g flowise
npx flowise start

Getting the following error, do you what is the issue?

npx flowise start --FLOWISE_USERNAME=user --FLOWISE_PASSWORD=1234
2024-01-16 11:58:49 [INFO]: Starting Flowise...
2024-01-16 11:58:49 [INFO]: ⚡️ [server]: Flowise Server is listening at 3000
2024-01-16 11:58:49 [INFO]: 📦 [server]: Data Source has been initialized!
2024-01-16 11:58:55 [ERROR]: ❌ [server]: Error during Data Source initialization: require() of ES Module /Users/hemantmanwani/Downloads/second_brain/Flowise/node_modules/@upstash/redis/nodejs.mjs not supported.
Instead change the require of /Users/hemantmanwani/Downloads/second_brain/Flowise/node_modules/@upstash/redis/nodejs.mjs to a dynamic import() which is available in all CommonJS modules.
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/hemantmanwani/Downloads/second_brain/Flowise/node_modules/@upstash/redis/nodejs.mjs not supported.
Instead change the require of /Users/hemantmanwani/Downloads/second_brain/Flowise/node_modules/@upstash/redis/nodejs.mjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/hemantmanwani/Downloads/second_brain/Flowise/node_modules/langchain/node_modules/@langchain/community/dist/caches/upstash_redis.cjs:4:17)
    at Object.<anonymous> (/Users/hemantmanwani/Downloads/second_brain/Flowise/node_modules/langchain/node_modules/@langchain/community/caches/upstash_redis.cjs:1:18)
    at Object.<anonymous> (/Users/hemantmanwani/Downloads/second_brain/Flowise/node_modules/langchain/dist/cache/upstash_redis.cjs:17:14)
    at Object.<anonymous> (/Users/hemantmanwani/Downloads/second_brain/Flowise/node_modules/langchain/cache/upstash_redis.cjs:1:18)
    at Object.<anonymous> (/Users/hemantmanwani/Downloads/second_brain/Flowise/packages/components/dist/nodes/cache/UpstashRedisCache/UpstashRedisCache.js:4:25)
    at /Users/hemantmanwani/Downloads/second_brain/Flowise/packages/server/dist/NodesPool.js:32:42
    at Array.map (<anonymous>)
    at NodesPool.initializeNodes (/Users/hemantmanwani/Downloads/second_brain/Flowise/packages/server/dist/NodesPool.js:30:38)
    at async NodesPool.initialize (/Users/hemantmanwani/Downloads/second_brain/Flowise/packages/server/dist/NodesPool.js:20:9)
    at async /Users/hemantmanwani/Downloads/second_brain/Flowise/packages/server/dist/index.js:77:13

**Comment by rizvand** [comment]
Hi @hemant-manwani, have you found any workaround to solve this issue?

**Comment by abraxas93** [comment]
Have the same issue on my mac :( Has anybody found a solution to resolve it?

**Comment by rizvand** [comment]
I rolled back and also tried redeploying while [locking](https://github.com/FlowiseAI/Flowise/issues/1536#issuecomment-1893402582) the `@upstash/redis` version for quick fix
