### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'text')

### ISSUE THREAD

**Issue by robertofabrizi** [FlowiseAI/Flowise#1699]
**Describe the bug**
When I use MultiRetrieval Q&A Chain I get this error:

```
2024-02-08 16:25:58 [ERROR]: [server]: Error: Cannot read properties of undefined (reading 'text')
TypeError: Cannot read properties of undefined (reading 'text')
    at App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1557:24)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1057:13
```

**To Reproduce**
I created a MultiRetrieval Q&A Chain from the marketplace, deleted two out of three databases to start small, filled every credentials in, asked a question, it worked, asked another, it broke with this error.

**Expected behavior**
To keep working :-)

**Screenshots**
<img width="1919" alt="Screenshot 2024-02-08 172853" src="https://github.com/FlowiseAI/Flowise/assets/6720929/b3790591-37dc-4f94-9575-4470e2689a82">

**Setup**
-   Docker
-   Flowise Version 1.5.0
-   OS: Linux
-   Browser: Chrome

**Comment by HenryHengZJ** [comment]
I've tried on `1.5.0` seems to work fine: 
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/3dff3de6-a90d-46ed-93aa-a79b07da92e1)

**Comment by robertofabrizi** [comment]
It bugs sometimes, I haven't been able to reproduce it in a deterministic way, as you can see it bugged at the second question there, sometimes at the first, sometimes the fourth

**Comment by rutther** [comment]
me too
