### ISSUE TITLE
[BUG] Can't Add Credentials on Latest Version

### ISSUE THREAD

**Issue by joaovitor2763** [FlowiseAI/Flowise#1766]
**Describe the bug**
Just made deploy on Huggingface following instructions but can't add credentials, this is the console log:

`
===== Application Startup at 2024-02-20 11:25:37 =====

2024-02-20 11:27:08 [INFO]: Starting Flowise...
2024-02-20 11:27:08 [INFO]: ⚡️ [server]: Flowise Server is listening at 7860
2024-02-20 11:27:08 [INFO]: 📦 [server]: Data Source has been initialized!
2024-02-20 11:27:10 [ERROR]: ❌ [server]: Error during Data Source initialization: require() of ES Module /usr/local/lib/node_modules/flowise/node_modules/json-with-bigint/json-with-bigint.js from /usr/local/lib/node_modules/flowise/node_modules/@qdrant/openapi-typescript-fetch/dist/cjs/fetcher.js not supported.
Instead change the require of json-with-bigint.js in /usr/local/lib/node_modules/flowise/node_modules/@qdrant/openapi-typescript-fetch/dist/cjs/fetcher.js to a dynamic import() which is available in all CommonJS modules.
Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/local/lib/node_modules/flowise/node_modules/json-with-bigint/json-with-bigint.js from /usr/local/lib/node_modules/flowise/node_modules/@qdrant/openapi-typescript-fetch/dist/cjs/fetcher.js not supported.
Instead change the require of json-with-bigint.js in /usr/local/lib/node_modules/flowise/node_modules/@qdrant/openapi-typescript-fetch/dist/cjs/fetcher.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/@qdrant/openapi-typescript-fetch/dist/cjs/fetcher.js:5:28)
    at Object.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/@qdrant/openapi-typescript-fetch/dist/cjs/index.js:4:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/@qdrant/js-client-rest/dist/cjs/api-client.js:4:36)
    at Object.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/@qdrant/js-client-rest/dist/cjs/qdrant-client.js:5:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/@qdrant/js-client-rest/dist/cjs/index.js:18:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/vectorstores/Qdrant/Qdrant.js:4:26)
    at /usr/local/lib/node_modules/flowise/dist/NodesPool.js:32:42
    at Array.map (<anonymous>)
    at NodesPool.initializeNodes (/usr/local/lib/node_modules/flowise/dist/NodesPool.js:30:38)
    at async NodesPool.initialize (/usr/local/lib/node_modules/flowise/dist/NodesPool.js:20:9)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:78:13
Error: Node qdrant not found
    at /usr/local/lib/node_modules/flowise/dist/index.js:229:23
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:284:15
    at param (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:365:14)
    at param (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:421:3)
    at next (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:280:10)
    at sanitizeMiddleware (/usr/local/lib/node_modules/flowise/dist/utils/XSS.js:24:5)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:328:13)
    at /usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:280:10)
Error: Credential azureOpenAIApi not found
    at /usr/local/lib/node_modules/flowise/dist/index.js:197:27
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:284:15
    at param (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:365:14)
    at param (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:421:3)
    at next (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:280:10)
    at sanitizeMiddleware (/usr/local/lib/node_modules/flowise/dist/utils/XSS.js:24:5)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:328:13)
    at /usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:280:10)
Error: Credential azureOpenAIApi not found
    at /usr/local/lib/node_modules/flowise/dist/index.js:197:27
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:284:15
    at param (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:365:14)
    at param (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:421:3)
    at next (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:280:10)
    at sanitizeMiddleware (/usr/local/lib/node_modules/flowise/dist/utils/XSS.js:24:5)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:328:13)
    at /usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:280:10)
`

**To Reproduce**
Try to add credentials for any service on any screen. 

<img width="1570" alt="Screenshot 2024-02-20 at 08 36 22" src="https://github.com/FlowiseAI/Flowise/assets/8019800/26a0773a-068c-4a78-9ed4-4f610894faf3">

**Setup**
- Huggingface

**Comment by WilliWespe** [comment]
I have the same problem locally. I tried downgrading to flowise version 1.4.0, but the problem is still there.

**Comment by Timoss2024** [comment]
<img width="1777" alt="Screenshot 2024-02-20 at 14 55 33" src="https://github.com/FlowiseAI/Flowise/assets/160149190/cb114867-8b2e-4006-88e7-22ff4143aba5">
<img width="1769" alt="Screenshot 2024-02-20 at 14 56 03" src="https://github.com/FlowiseAI/Flowise/assets/160149190/302594d6-0cc5-4e88-b856-d87af8340ead">
I have almost the same problem here with the latest version of Flowise, (forked yesterday).
I try to add credentials to ChatOpenAI and to Pinecone but it seems like it don't let me create new credentials, when I click on  - Create New - , nothing is happening, I also tried two different browser, the problem is the same in both.

Could please help me with this ?
