### ISSUE TITLE
[BUG] PDF Loaders: Invalid PDF structure

### ISSUE THREAD

**Issue by forhonourlx** [FlowiseAI/Flowise#1855]
**Describe the bug**
Hi,
I build a basic chatflow of loading PDF, but get errors after trying different PDF files(in English / Chinese):
How can I fix that? Is there any size or coding restriction? How can I adjust them?
Thanks in advance.
![1709387715461](https://github.com/FlowiseAI/Flowise/assets/16576219/2a27cbc4-63ad-4285-b207-b46da66c92a2)

example: [https://arxiv.org/pdf/2402.17177.pdf](url)
```
2024-03-02 21:48:55 Warning: Indexing all PDF objects
2024-03-02 21:48:55 2024-03-02 13:48:55 [ERROR]: Invalid PDF structure
2024-03-02 21:48:55 Error
2024-03-02 21:48:55     at InvalidPDFExceptionClosure (/usr/local/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:452:35)
2024-03-02 21:48:55     at Object.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:455:2)
2024-03-02 21:48:55     at __w_pdfjs_require__ (/usr/local/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:45:30)
2024-03-02 21:48:55     at Object.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:7939:23)
2024-03-02 21:48:55     at __w_pdfjs_require__ (/usr/local/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:45:30)
2024-03-02 21:48:55     at /usr/local/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:88:18
2024-03-02 21:48:55     at /usr/local/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:91:10
2024-03-02 21:48:55     at webpackUniversalModuleDefinition (/usr/local/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:18:20)
2024-03-02 21:48:55     at Object.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:25:3)
2024-03-02 21:48:55     at Module._compile (node:internal/modules/cjs/loader:1356:14)
2024-03-02 21:48:55     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
2024-03-02 21:48:55     at Module.load (node:internal/modules/cjs/loader:1197:32)
2024-03-02 21:48:55     at Module._load (node:internal/modules/cjs/loader:1013:12)
2024-03-02 21:48:55     at Module.require (node:internal/modules/cjs/loader:1225:19)
2024-03-02 21:48:55     at require (node:internal/modules/helpers:177:18)
2024-03-02 21:48:55     at /usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/documentloaders/Pdf/Pdf.js:105:165
```

**Setup**
-   Installation docker
-   Flowise Version 1.6.0
-   OS: Windows 11
-   Browser chrome

**Comment by HenryHengZJ** [comment]
Have you tried to see if turning on Legacy build of PDF loader helps?
<img width="452" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/a3ffb17d-aee0-4c2c-a582-9ee234fadb7b">
