### ISSUE TITLE
[BUG] Retrieval Chain : fetch failed on PgVector with Ollama

### ISSUE THREAD

**Issue by maulanaakbardj** [FlowiseAI/Flowise#1859]
**Describe the bug**
response fetch failed when retrieving documents from pgVector

Error : 
```
2024-03-03 16:57:46 [INFO]: [server]: Chatflow 7f00bcb4-c7bb-4b70-8139-5ef0e47a37bd added into ChatflowPool
2024-03-03 17:02:49 [ERROR]: [server]: Error: fetch failed
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at async createOllamaStream (C:\Users\maula\AppData\Roaming\npm\node_modules\flowise\node_modules\@langchain\community\dist\utils\ollama.cjs:12:22)
    at async createOllamaChatStream (C:\Users\maula\AppData\Roaming\npm\node_modules\flowise\node_modules\@langchain\community\dist\utils\ollama.cjs:60:5)
    at async ChatOllama._streamResponseChunks (C:\Users\maula\AppData\Roaming\npm\node_modules\flowise\node_modules\@langchain\community\dist\chat_models\ollama.cjs:378:30)
    at async ChatOllama._call (C:\Users\maula\AppData\Roaming\npm\node_modules\flowise\node_modules\@langchain\community\dist\chat_models\ollama.cjs:486:26)
    at async ChatOllama._generate (C:\Users\maula\AppData\Roaming\npm\node_modules\flowise\node_modules\@langchain\core\dist\language_models\chat_models.cjs:352:22)
    at async Promise.allSettled (index 0)
    at async ChatOllama._generateUncached (C:\Users\maula\AppData\Roaming\npm\node_modules\flowise\node_modules\@langchain\core\dist\language_models\chat_models.cjs:114:25)
    at async LLMChain._call (C:\Users\maula\AppData\Roaming\npm\node_modules\flowise\node_modules\langchain\dist\chains\llm_chain.cjs:157:37)
    at async LLMChain.invoke (C:\Users\maula\AppData\Roaming\npm\node_modules\flowise\node_modules\langchain\dist\chains\base.cjs:58:28)
    at async StuffDocumentsChain._call (C:\Users\maula\AppData\Roaming\npm\node_modules\flowise\node_modules\langchain\dist\chains\combine_docs_chain.cjs:62:24)
    at async StuffDocumentsChain.invoke (C:\Users\maula\AppData\Roaming\npm\node_modules\flowise\node_modules\langchain\dist\chains\base.cjs:58:28)
    at async RetrievalQAChain._call (C:\Users\maula\AppData\Roaming\npm\node_modules\flowise\node_modules\langchain\dist\chains\retrieval_qa.cjs:81:24)
    at async RetrievalQAChain.invoke (C:\Users\maula\AppData\Roaming\npm\node_modules\flowise\node_modules\langchain\dist\chains\base.cjs:58:28)
    at async RetrievalQAChain_Chains.run (C:\Users\maula\AppData\Roaming\npm\node_modules\flowise\node_modules\flowise-components\dist\nodes\chains\RetrievalQAChain\RetrievalQAChain.js:44:25)
    at async App.buildChatflow (C:\Users\maula\AppData\Roaming\npm\node_modules\flowise\dist\index.js:1726:19)
```

**To Reproduce**

1. web scraper or upload pdf in a pgvector
2. Using Retrieval QA Chain to LLM & pgVector

**Expected behavior**

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/67249292/b02931f1-ad71-4bc7-a4d0-515ad52a8cc4)
![image](https://github.com/FlowiseAI/Flowise/assets/67249292/7fdc91e5-5c17-468c-bb48-95dfbb61e4b4)

**Flow**
If applicable, add exported flow in order to help replicating the problem.
![image](https://github.com/FlowiseAI/Flowise/assets/67249292/4b9f6e68-373d-46a7-93fc-13ff2e35a2c9)

**Setup**

- Flowise Version: 1.6.0
- Operating System: Windows

**Additional context**

**Comment by maulanaakbardj** [comment]
Hi, I closed this issue because I believed that the `fetch failed` error occurred due to the insufficient strength of my test environment. This resulted in a timeout. However, upon trying it in a larger environment, there were no issues and it worked successfully
