### ISSUE TITLE
[BUG] LlamaIndex returns "Cannot initialize VectorStoreIndex without nodes or indexStruct" with vector store retriever

### ISSUE THREAD

**Issue by automaton82** [FlowiseAI/Flowise#1883]
**Describe the bug**
Setup a vector store retriever flow with LlamaIndex as per below, then execute it. You will get the error:
```
2024-03-05 17:32:01 [ERROR]: [server]: Error: Error: Cannot initialize VectorStoreIndex without nodes or indexStruct
Error: Error: Cannot initialize VectorStoreIndex without nodes or indexStruct
    at buildFlow (E:\git\Flowise\packages\server\dist\utils\index.js:333:19)
    at async App.buildChatflow (E:\git\Flowise\packages\server\dist\index.js:1734:40)
    at async E:\git\Flowise\packages\server\dist\index.js:1161:13
```

**To Reproduce**

1. Create this flow:
![image](https://github.com/FlowiseAI/Flowise/assets/4467711/de3b2150-37d9-4046-a9bf-a55540f6743e)

Or import the JSON file:
[llamaIndex test Chatflow.json](https://github.com/FlowiseAI/Flowise/files/14502204/llamaIndex.test.Chatflow.json)

Try to ask any question.

**Expected behavior**
This should probably work.

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/4467711/5e0b6081-bac5-4d6f-bec0-0086be089c26)

**Flow**
[llamaIndex test Chatflow.json](https://github.com/FlowiseAI/Flowise/files/14502204/llamaIndex.test.Chatflow.json)

**Setup**
Using latest build from the repo, built locally on Windows.

**Comment by automaton82** [comment]
Note the query engine appears to have the same issue, so presumably this is a problem with the simplestore node.

**Comment by automaton82** [comment]
I replicated the same issue with a fresh Docker image, so it's not the pathing on Windows (vectorstore has the wrong `/` in the path, but that doesn't seem to be the issue given the same thing happens on Docker Linux image).

**Comment by automaton82** [comment]
Okay I figured it out.

This only fails the very first time, before the database has been created. It won't create the database if the call to do the embeddings comes in the prediction call. If you first run the upsert, then do the query, it will succeed.

What's more, all subsequent calls, even with new chatflows, documents and other things will upsert correctly on-the-fly once the database has been created.

**Comment by HenryHengZJ** [comment]
so if we do the upsert first then query, it works fine?

**Comment by automaton82** [comment]
I believe it would, yes. As a note this is what the LangChain nodes do, at least if you use the in-memory vector store.

A prediction will cause an upsert.

Only issue is there's no way to delete the previous entries, I opened a discussion about that since it will grow indefinitely (at least with SimpleStore).
