### ISSUE TITLE
[BUG] TypeError: fetch failed

### ISSUE THREAD

**Issue by dirien** [FlowiseAI/Flowise#1927]
**Describe the bug**

When "upserting", independent of the vector store, I get follwing error

```bash
docker-flowise-1  | This will be mandatory after the next "langchain" minor version bump to 0.2.
docker-flowise-1  | 2024-03-12 05:42:58 [INFO]: 📦 [server]: Data Source has been initialized!
docker-flowise-1  | 2024-03-12 05:43:04 [INFO]: ⬆️ POST /api/v1/vector/internal-upsert/d07606e2-e8e3-4062-9d8b-ba9ec680720b
docker-flowise-1  | 2024-03-12 05:43:05 [ERROR]: TypeError: fetch failed
docker-flowise-1  | Error: TypeError: fetch failed
docker-flowise-1  |     at Pinecone_VectorStores.upsert (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/vectorstores/Pinecone/Pinecone.js:40:27)
docker-flowise-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
docker-flowise-1  |     at async buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:273:17)
docker-flowise-1  |     at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1503:13)
docker-flowise-1  |     at async /usr/local/lib/node_modules/flowise/dist/index.js:1112:13
docker-flowise-1  | 2024-03-12 05:43:05 [ERROR]: [server]: Error: Error: TypeError: fetch failed
docker-flowise-1  | Error: Error: TypeError: fetch failed
docker-flowise-1  |     at buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:333:19)
docker-flowise-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
docker-flowise-1  |     at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1503:13)
docker-flowise-1  |     at async /usr/local/lib/node_modules/flowise/dist/index.js:1112:13
^CGracefully stopping... (press Ctrl+C again to force)
``` 

**To Reproduce**

Run flowise via docker-compose, create a simple flow with Document Loader and vector store

**Expected behavior**

No error message, and upsert works.

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**
-   Installation [e.g. docker, `npx flowise start`, `yarn start`]
    As container via docker-compose
-   Flowise Version [e.g. 1.2.11]
    1.6.0
-   OS: [e.g. macOS, Windows, Linux]
    Container Linux
-   Browser [e.g. chrome, safari]
    Chrome

**Additional context**

**Comment by socialsciencesoftware** [comment]
Would you share what solved the problem? I'm having the same issue.

**Comment by jpbotha11** [comment]
I am having the same issue and would also like to know how to solve. Thanks

**Comment by anasmohammed361** [comment]
+1

**Comment by anasmohammed361** [comment]
running the docker-compose with networkmode:host fixed the issue for , i think the reason would be because , i was running my ollama and my vector db server as a seperate docker-compose , if you wanna run everything under one docker-compose under the same network then swapping out the `localhost` for the name of your `service` might do the trick for you .

Eg: Solution 1 

``` 
services:
    flowise:
        network_mode: host
        image: flowiseai/flowise
        environment:
            - PORT=${PORT}
            - CORS_ORIGINS=${CORS_ORIGINS}
            - IFRAME_ORIGINS=${IFRAME_ORIGINS}
            - FLOWISE_USERNAME=${FLOWISE_USERNAME}
            - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
            - FLOWISE_FILE_SIZE_LIMIT=${FLOWISE_FILE_SIZE_LIMIT}
            - DEBUG=${DEBUG}
            - DATABASE_PATH=${DATABASE_PATH}
            - DATABASE_TYPE=${DATABASE_TYPE}
            - DATABASE_PORT=${DATABASE_PORT}
            - DATABASE_HOST=${DATABASE_HOST}
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_USER=${DATABASE_USER}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_SSL=${DATABASE_SSL}
            - DATABASE_SSL_KEY_BASE64=${DATABASE_SSL_KEY_BASE64}
            - APIKEY_PATH=${APIKEY_PATH}
            - SECRETKEY_PATH=${SECRETKEY_PATH}
            - FLOWISE_SECRETKEY_OVERWRITE=${FLOWISE_SECRETKEY_OVERWRITE}
            - LOG_LEVEL=${LOG_LEVEL}
            - LOG_PATH=${LOG_PATH}
            - BLOB_STORAGE_PATH=${BLOB_STORAGE_PATH}
            - DISABLE_FLOWISE_TELEMETRY=${DISABLE_FLOWISE_TELEMETRY}
        ports:
            - '${PORT}:${PORT}'
        volumes:
            - .flowise:/root/.flowise
        command: /bin/sh -c "sleep 3; flowise start"
    
```


Eg:2 Running all under same service


```
services:
    flowise:
        image: flowiseai/flowise
        environment:
            - PORT=${PORT}
            - CORS_ORIGINS=${CORS_ORIGINS}
            - IFRAME_ORIGINS=${IFRAME_ORIGINS}
            - FLOWISE_USERNAME=${FLOWISE_USERNAME}
            - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
            - FLOWISE_FILE_SIZE_LIMIT=${FLOWISE_FILE_SIZE_LIMIT}
            - DEBUG=${DEBUG}
            - DATABASE_PATH=${DATABASE_PATH}
            - DATABASE_TYPE=${DATABASE_TYPE}
            - DATABASE_PORT=${DATABASE_PORT}
            - DATABASE_HOST=${DATABASE_HOST}
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_USER=${DATABASE_USER}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_SSL=${DATABASE_SSL}
            - DATABASE_SSL_KEY_BASE64=${DATABASE_SSL_KEY_BASE64}
            - APIKEY_PATH=${APIKEY_PATH}
            - SECRETKEY_PATH=${SECRETKEY_PATH}
            - FLOWISE_SECRETKEY_OVERWRITE=${FLOWISE_SECRETKEY_OVERWRITE}
            - LOG_LEVEL=${LOG_LEVEL}
            - LOG_PATH=${LOG_PATH}
            - BLOB_STORAGE_PATH=${BLOB_STORAGE_PATH}
            - DISABLE_FLOWISE_TELEMETRY=${DISABLE_FLOWISE_TELEMETRY}
        ports:
            - '${PORT}:${PORT}'
        volumes:
            - .flowise:/root/.flowise
        command: /bin/sh -c "sleep 3; flowise start"
        networks:
            - my_network
    vectordb:
        image: qdrant/qdrant
        ports:
            - "6333:6333"
        volumes:
            - ./db-cache:/qdrant/storage:z
        networks:
        - my_network


networks:
  my_network:


```

Now your vector db url will be `http://vectordb:6333`

This is because the name of the service is vectordb.

**Comment by jpbotha11** [comment]
In my case the upsert process timed out. I was running the upsert for too many documents at once.
Lowering the document count to one or two documents at a time resolved the issue for me.

**Comment by anasmohammed361** [comment]
> In my case the upsert process timed out. I was running the upsert for too many documents at once. Lowering the document count to one or two documents at a time resolved the issue for me.

Yes that is an issue too , you will get the error logs in the server console if the document is large than the available context  lenght

**Comment by BenjaminChan1105** [comment]
I got the same problem. It was solved when I re-install the Ollama.

**Comment by papmalikba** [comment]
Hi there, I have a question, I have Flowise installed globally and Ollama. Bolth locally installed but different localhost...is that what causing the "Error: vectorsService.upsertVector - Error: TypeError: fetch failed " issue?
if so, is there a solution? 
Thank you
