### ISSUE TITLE
[BUG] Operator does not exist error when opening chat window

### ISSUE THREAD

**Issue by zanaffar** [FlowiseAI/Flowise#1947]
**Describe the bug**
After upgrading to version 1.6.1, Flowise crashes whenever I open the chat window for any of my chatflows. When I watch the logs for the flowise pod, I see the following error when the crash occurs:
```
2024-03-13 23:18:52 [ERROR]: unhandledRejection: operator does not exist: character varying = uuid
QueryFailedError: operator does not exist: character varying = uuid
    at PostgresQueryRunner.query (/usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.loadRawResults (/usr/local/lib/node_modules/flowise/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2192:25)
    at async SelectQueryBuilder.executeEntitiesAndRawResults (/usr/local/lib/node_modules/flowise/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2040:26)
    at async SelectQueryBuilder.getRawAndEntities (/usr/local/lib/node_modules/flowise/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
    at async SelectQueryBuilder.getMany (/usr/local/lib/node_modules/flowise/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25)
    at async App.getChatMessage (/usr/local/lib/node_modules/flowise/dist/index.js:1552:30)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:529:34
```

**Setup**

-   Installation: Kubernetes
-   Flowise Version: 1.6.1
-   OS: Linux
-   Browser: Chrome, Edge

**Additional context**
I am experiencing this crash on both, an old and a fresh instance of Postgres. In order to rule out any migration issues, I created a completely fresh database instance. The problem persists even with a fresh instance.

**Comment by emrahtoy** [comment]
I have faced with the same bug

Here are the reasons behind

1. Relational uuid comparison has to be done between same object types ( in this case it is between uuid and varchar )
2. PostgreSQL does not like BETWEEN clause with the timestamp object types. Instead it should be >= and <=

I confirmed 1. situation and object type change fixes it ( will be result with a migration file )
I will test the second situation soon.

**Comment by emrahtoy** [comment]
By the way;

Typeorm has got `@Column({ type: 'uuid' })` and `@Column({ type: 'timestamp with time zone' })` decaorators. This can fix the problems when the entity files are changed. But then, Sqlite support should be tested as it is not nicely documented.

@HenryHengZJ @0xi4o
