### ISSUE TITLE
[Flowise]Error: TypeError: fetch failed

### ISSUE THREAD

**Issue by attlong01** [FlowiseAI/Flowise#1956]
**Describe the bug**
2024-03-15 05:45:45 [INFO]: ⬆️ POST /api/v1/vector/internal-upsert/2b1ebf16-53fc-40db-97c2-e2ed18faa4ca
Warning: TT: undefined function: 32
2024-03-15 05:45:46 [ERROR]: TypeError: fetch failed
Error: TypeError: fetch failed
    at Pinecone_VectorStores.upsert (/usr/src/packages/components/dist/nodes/vectorstores/Pinecone/Pinecone.js:40:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async buildFlow (/usr/src/packages/server/dist/utils/index.js:265:17)
    at async App.upsertVector (/usr/src/packages/server/dist/index.js:1693:13)
    at async /usr/src/packages/server/dist/index.js:1193:13
2024-03-15 05:45:46 [ERROR]: [server]: Error: Error: TypeError: fetch failed
Error: Error: TypeError: fetch failed
    at buildFlow (/usr/src/packages/server/dist/utils/index.js:326:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async App.upsertVector (/usr/src/packages/server/dist/index.js:1693:13)
    at async /usr/src/packages/server/dist/index.js:1193:13

**Comment by HenryHengZJ** [comment]
Pinning pinecone dependency should solve the issue. PR https://github.com/FlowiseAI/Flowise/pull/2036

**Comment by HenryHengZJ** [comment]
Should be resolved in `v1.6.3`
