### ISSUE TITLE
[BUG] Installation WSL issue

### ISSUE THREAD

**Issue by danielstankw** [FlowiseAI/Flowise#2043]
**Describe the bug**
I attempt to install the application but with no success. I am on Windows 10, using WSL Ubuntu 20.04.6 LTS

**To Reproduce**

1. `node --version` --> `v21.7.1`
2.  `npm install -g flowise`
3. Output

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'flowise@1.6.2',
npm WARN EBADENGINE   required: { node: '>=18.15.0 <19.0.0 || ^20' },
npm WARN EBADENGINE   current: { node: 'v21.7.1', npm: '10.5.0' }
npm WARN EBADENGINE }
npm WARN deprecated set-value@0.2.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm WARN deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
npm WARN deprecated domexception@4.0.0: Use your platform's native DOMException instead
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated vm2@3.9.19: The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to isolated-vm.
npm WARN deprecated puppeteer@19.11.1: < 21.8.0 is no longer supported
npm WARN deprecated puppeteer@20.9.0: < 21.8.0 is no longer supported
npm WARN deprecated @oclif/screen@3.0.8: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated highlight.js@9.15.10: Version no longer supported. Upgrade to @latest
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     '/home/XXX/.nvm/versions/node/v21.7.1/lib/node_modules/flowise/node_modules/faiss-node',
npm WARN cleanup     [Error: ENOTEMPTY: directory not empty, rmdir '/home/XXX/.nvm/versions/node/v21.7.1/lib/node_modules/flowise/node_modules/faiss-node'] {
npm WARN cleanup       errno: -39,
npm WARN cleanup       code: 'ENOTEMPTY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: '/home/XX/.nvm/versions/node/v21.7.1/lib/node_modules/flowise/node_modules/faiss-node'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     '/home/XXX/.nvm/versions/node/v21.7.1/lib/node_modules/flowise/node_modules/sqlite3',
npm WARN cleanup     [Error: ENOTEMPTY: directory not empty, rmdir '/home/XXX/.nvm/versions/node/v21.7.1/lib/node_modules/flowise/node_modules/sqlite3'] {
npm WARN cleanup       errno: -39,
npm WARN cleanup       code: 'ENOTEMPTY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: '/home/XXX/.nvm/versions/node/v21.7.1/lib/node_modules/flowise/node_modules/sqlite3'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path /home/XXX/.nvm/versions/node/v21.7.1/lib/node_modules/flowise/node_modules/grpc-tools
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install
npm ERR! request to https://node-precompiled-binaries.grpc.io/grpc-tools/v1.12.4/linux-x64.tar.gz failed, reason: self-signed certificate in certificate chain
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.11
npm ERR! node-pre-gyp info using node@21.7.1 | linux | x64
npm ERR! (node:2723) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! node-pre-gyp info check checked for "/home/XXX/.nvm/versions/node/v21.7.1/lib/node_modules/flowise/node_modules/grpc-tools/bin/grpc_tools.node" (not found)
npm ERR! node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc-tools/v1.12.4/linux-x64.tar.gz
npm ERR! node-pre-gyp ERR! install request to https://node-precompiled-binaries.grpc.io/grpc-tools/v1.12.4/linux-x64.tar.gz failed, reason: self-signed certificate in certificate chain
npm ERR! node-pre-gyp ERR! install error
npm ERR! node-pre-gyp ERR! stack FetchError: request to https://node-precompiled-binaries.grpc.io/grpc-tools/v1.12.4/linux-x64.tar.gz failed, reason: self-signed certificate in certificate chain
npm ERR! node-pre-gyp ERR! stack     at ClientRequest.<anonymous> (/home/XXX/.nvm/versions/node/v21.7.1/lib/node_modules/flowise/node_modules/node-fetch/lib/index.js:1501:11)
npm ERR! node-pre-gyp ERR! stack     at ClientRequest.emit (node:events:519:28)
npm ERR! node-pre-gyp ERR! stack     at TLSSocket.socketErrorListener (node:_http_client:500:9)
npm ERR! node-pre-gyp ERR! stack     at TLSSocket.emit (node:events:519:28)
npm ERR! node-pre-gyp ERR! stack     at emitErrorNT (node:internal/streams/destroy:169:8)
npm ERR! node-pre-gyp ERR! stack     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
npm ERR! node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR! node-pre-gyp ERR! System Linux 5.10.102.1-microsoft-standard-WSL2
npm ERR! node-pre-gyp ERR! command "/home/XXX/.nvm/versions/node/v21.7.1/bin/node" "/home/XXX/.nvm/versions/node/v21.7.1/lib/node_modules/flowise/node_modules/.bin/node-pre-gyp" "install"
npm ERR! node-pre-gyp ERR! cwd /home/XXX/.nvm/versions/node/v21.7.1/lib/node_modules/flowise/node_modules/grpc-tools
npm ERR! node-pre-gyp ERR! node -v v21.7.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.11
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in: /home/XXX/.npm/_logs/2024-03-26T12_19_47_013Z-debug-0.log
```

**Comment by danielstankw** [comment]
If I use a node version of `v18.19.1`

```
stankod1@PLWA1189NA:~/.npm/_logs$ npm install -g flowise
npm WARN deprecated set-value@0.2.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm WARN deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
npm WARN deprecated @oclif/screen@3.0.8: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated domexception@4.0.0: Use your platform's native DOMException instead
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated vm2@3.9.19: The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to isolated-vm.
npm WARN deprecated puppeteer@19.11.1: < 21.8.0 is no longer supported
npm WARN deprecated highlight.js@9.15.10: Version no longer supported. Upgrade to @latest
npm WARN deprecated puppeteer@20.9.0: < 21.8.0 is no longer supported
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     '/home/XXX/.nvm/versions/node/v18.19.1/lib/node_modules/flowise/node_modules/faiss-node',
npm WARN cleanup     [Error: ENOTEMPTY: directory not empty, rmdir '/home/XXX/.nvm/versions/node/v18.19.1/lib/node_modules/flowise/node_modules/faiss-node'] {
npm WARN cleanup       errno: -39,
npm WARN cleanup       code: 'ENOTEMPTY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: '/home/XXX/.nvm/versions/node/v18.19.1/lib/node_modules/flowise/node_modules/faiss-node'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     '/home/XXX/.nvm/versions/node/v18.19.1/lib/node_modules/flowise/node_modules/sqlite3',
npm WARN cleanup     [Error: ENOTEMPTY: directory not empty, rmdir '/home/XXX/.nvm/versions/node/v18.19.1/lib/node_modules/flowise/node_modules/sqlite3'] {
npm WARN cleanup       errno: -39,
npm WARN cleanup       code: 'ENOTEMPTY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: '/home/XXX/.nvm/versions/node/v18.19.1/lib/node_modules/flowise/node_modules/sqlite3'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path /home/XXX/.nvm/versions/node/v18.19.1/lib/node_modules/flowise/node_modules/grpc-tools
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install
npm ERR! request to https://node-precompiled-binaries.grpc.io/grpc-tools/v1.12.4/linux-x64.tar.gz failed, reason: self-signed certificate in certificate chain
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.11
npm ERR! node-pre-gyp info using node@18.19.1 | linux | x64
npm ERR! node-pre-gyp info check checked for "/home/XXX/.nvm/versions/node/v18.19.1/lib/node_modules/flowise/node_modules/grpc-tools/bin/grpc_tools.node" (not found)
npm ERR! node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc-tools/v1.12.4/linux-x64.tar.gz
npm ERR! node-pre-gyp ERR! install request to https://node-precompiled-binaries.grpc.io/grpc-tools/v1.12.4/linux-x64.tar.gz failed, reason: self-signed certificate in certificate chain
npm ERR! node-pre-gyp ERR! install error
npm ERR! node-pre-gyp ERR! stack FetchError: request to https://node-precompiled-binaries.grpc.io/grpc-tools/v1.12.4/linux-x64.tar.gz failed, reason: self-signed certificate in certificate chain
npm ERR! node-pre-gyp ERR! stack     at ClientRequest.<anonymous> (/home/XXX/.nvm/versions/node/v18.19.1/lib/node_modules/flowise/node_modules/node-fetch/lib/index.js:1501:11)
npm ERR! node-pre-gyp ERR! stack     at ClientRequest.emit (node:events:517:28)
npm ERR! node-pre-gyp ERR! stack     at TLSSocket.socketErrorListener (node:_http_client:501:9)
npm ERR! node-pre-gyp ERR! stack     at TLSSocket.emit (node:events:517:28)
npm ERR! node-pre-gyp ERR! stack     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR! node-pre-gyp ERR! stack     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR! node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR! node-pre-gyp ERR! System Linux 5.10.102.1-microsoft-standard-WSL2
npm ERR! node-pre-gyp ERR! command "/home/XXX/.nvm/versions/node/v18.19.1/bin/node" "/home/XXX/.nvm/versions/node/v18.19.1/lib/node_modules/flowise/node_modules/.bin/node-pre-gyp" "install"
npm ERR! node-pre-gyp ERR! cwd /home/XXX/.nvm/versions/node/v18.19.1/lib/node_modules/flowise/node_modules/grpc-tools
npm ERR! node-pre-gyp ERR! node -v v18.19.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.11
npm ERR! node-pre-gyp ERR! not ok

```

**Comment by HenryHengZJ** [comment]
@vinodkiran we can probably just use `"node": ">=18.0.0"`

**Comment by HenryHengZJ** [comment]
In the meantime, @danielstankw can you use node 20?
