### ISSUE TITLE
[BUG] Can't Setup Flowise on AWS according to Doumentation

### ISSUE THREAD

**Issue by droegier** [FlowiseAI/Flowise#2051]
**Describe the bug**
The setup on AWS does not work.

**To Reproduce**
1. Follow this document precisely, step by step.
https://docs.flowiseai.com/configuration/deployment/aws

**Expected behavior**
Successful docker-compose call (Step nr. 7). Instead I got the following Error:

```
Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/.local/lib/python3.9/site-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/compose/cli/docker_client.py", line 124, in docker_client
    kwargs = kwargs_from_env(environment=environment, ssl_version=tls_version)
TypeError: kwargs_from_env() got an unexpected keyword argument 'ssl_version'
```

**Comment by droegier** [comment]
I get the following issue when installing docker-compose:

```
[ec2-user@ip-172-31-8-173 ~]$ pip3 install docker-compose
Defaulting to user installation because normal site-packages is not writeable
Collecting docker-compose
  Downloading docker_compose-1.29.2-py2.py3-none-any.whl (114 kB)
     |████████████████████████████████| 114 kB 5.2 MB/s            
Collecting python-dotenv<1,>=0.13.0
  Downloading python_dotenv-0.21.1-py3-none-any.whl (19 kB)
Collecting dockerpty<1,>=0.4.1
  Downloading dockerpty-0.4.1.tar.gz (13 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests<3,>=2.20.0 in /usr/lib/python3.9/site-packages (from docker-compose) (2.25.1)
Collecting docopt<1,>=0.6.1
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Collecting texttable<2,>=0.9.0
  Downloading texttable-1.7.0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: distro<2,>=1.5.0 in /usr/lib/python3.9/site-packages (from docker-compose) (1.5.0)
Requirement already satisfied: PyYAML<6,>=3.10 in /usr/lib64/python3.9/site-packages (from docker-compose) (5.4.1)
Requirement already satisfied: jsonschema<4,>=2.5.1 in /usr/lib/python3.9/site-packages (from docker-compose) (3.2.0)
Collecting websocket-client<1,>=0.32.0
  Downloading websocket_client-0.59.0-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 10.1 MB/s            
Collecting docker[ssh]>=5
  Downloading docker-7.0.0-py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 48.0 MB/s            
Collecting urllib3>=1.26.0
  Downloading urllib3-2.2.1-py3-none-any.whl (121 kB)
     |████████████████████████████████| 121 kB 52.5 MB/s            
Collecting packaging>=14.0
  Downloading packaging-24.0-py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 3.7 MB/s             
Collecting requests<3,>=2.20.0
  Downloading requests-2.31.0-py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 2.0 MB/s             
Collecting paramiko>=2.4.3
  Downloading paramiko-3.4.0-py3-none-any.whl (225 kB)
     |████████████████████████████████| 225 kB 50.2 MB/s            
Requirement already satisfied: six>=1.3.0 in /usr/lib/python3.9/site-packages (from dockerpty<1,>=0.4.1->docker-compose) (1.15.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/lib/python3.9/site-packages (from jsonschema<4,>=2.5.1->docker-compose) (20.3.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /usr/lib64/python3.9/site-packages (from jsonschema<4,>=2.5.1->docker-compose) (0.17.3)
Requirement already satisfied: setuptools in /usr/lib/python3.9/site-packages (from jsonschema<4,>=2.5.1->docker-compose) (59.6.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.9/site-packages (from requests<3,>=2.20.0->docker-compose) (2.10)
Collecting certifi>=2017.4.17
  Downloading certifi-2024.2.2-py3-none-any.whl (163 kB)
     |████████████████████████████████| 163 kB 50.8 MB/s            
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.3.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)
     |████████████████████████████████| 142 kB 52.2 MB/s            
Collecting pynacl>=1.5
  Downloading PyNaCl-1.5.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (856 kB)
     |████████████████████████████████| 856 kB 29.6 MB/s            
Requirement already satisfied: cryptography>=3.3 in /usr/lib64/python3.9/site-packages (from paramiko>=2.4.3->docker[ssh]>=5->docker-compose) (36.0.1)
Collecting bcrypt>=3.2
  Downloading bcrypt-4.1.2-cp39-abi3-manylinux_2_28_x86_64.whl (698 kB)
     |████████████████████████████████| 698 kB 28.0 MB/s            
Requirement already satisfied: cffi>=1.12 in /usr/lib64/python3.9/site-packages (from cryptography>=3.3->paramiko>=2.4.3->docker[ssh]>=5->docker-compose) (1.14.5)
Requirement already satisfied: pycparser in /usr/lib/python3.9/site-packages (from cffi>=1.12->cryptography>=3.3->paramiko>=2.4.3->docker[ssh]>=5->docker-compose) (2.20)
Requirement already satisfied: ply==3.11 in /usr/lib/python3.9/site-packages (from pycparser->cffi>=1.12->cryptography>=3.3->paramiko>=2.4.3->docker[ssh]>=5->docker-compose) (3.11)
Using legacy 'setup.py install' for dockerpty, since package 'wheel' is not installed.
Using legacy 'setup.py install' for docopt, since package 'wheel' is not installed.
Installing collected packages: urllib3, charset-normalizer, certifi, requests, pynacl, packaging, bcrypt, paramiko, docker, websocket-client, texttable, python-dotenv, docopt, dockerpty, docker-compose
    Running setup.py install for docopt ... done
    Running setup.py install for dockerpty ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
awscli 2.14.5 requires urllib3<1.27,>=1.25.4, but you have urllib3 2.2.1 which is incompatible.
Successfully installed bcrypt-4.1.2 certifi-2024.2.2 charset-normalizer-3.3.2 docker-7.0.0 docker-compose-1.29.2 dockerpty-0.4.1 docopt-0.6.2 packaging-24.0 paramiko-3.4.0 pynacl-1.5.0 python-dotenv-0.21.1 requests-2.31.0 texttable-1.7.0 urllib3-2.2.1 websocket-client-0.59.0
```

**Comment by KI-Experten** [comment]
I guess this is the same Problem I had.
The problem: docker version 7.0.0 is not compatible with the python version.

I solved the problem with downgrading the docker version:
Use these Commands after the error appears:

"pip uninstall docker"
"pip install docker==6.1.3"
"pip3 install docker-compose"

Hope this is helpful

**Comment by HenryHengZJ** [comment]
thanks for helping @KI-Experten!

closing for now
