### ISSUE TITLE
fetch failed LocalAI with flowise on remote machine

### ISSUE THREAD

**Issue by PunkBank** [FlowiseAI/Flowise#2057]
**Describe the bug**

First: I dont know if it is a bug or a more a problem on my end.

I want to use LocalAI with flowise. 
I set up docker, flowise and LocalAI accordingly on another machine in my network.

1. Flowise works alone. Meaning, I can access it via browser on my local machine using the IP of the remote machine and the specific port.

2. I can access the LocalAI models on the remote machine itself via 
```
> curl http://localhost:8080/v1/models
{"object":"list","data":[{"id":"em_german_mistral_v01.Q4_0.gguf","object":"model"}]}
```

as well as from my local machine via the IP of the remote machine via

```
> curl http://<IP_remote_machine>:8080/v1/models
{"object":"list","data":[{"id":"em_german_mistral_v01.Q4_0.gguf","object":"model"}]}
```

So I assume LocalAI is working. 

--> However, when I try to use the LocalAI node in flowise and give "http://localhost:8080/v1" or "http://<IP_remote_machine>:8080/v1/" as base path, I get in both cases a fetch error. 

Error message is: 

```
[ERROR]: [server]: Error: fetch failed
TypeError: fetch failed
    at node:internal/deps/undici/undici:12345:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async request (/path_to_flowise/node_modules/@huggingface/inference/dist/index.js:204:20)
    at async textGeneration (/path_to_flowise/node_modules/@huggingface/inference/dist/index.js:713:15)
    at async RetryOperation._fn (/path_to_flowise/node_modules/p-retry/index.js:50:12)
```

I am confused, why is it even calling something related to huggingface?
Could the problem be, that LocalAI and flowise are on two different hard drives?
Or am I giving the LocalAI node in flowise the wrong IP? Do I have to somehow get the docker IP of LocalAI?

What am I missing here?

**To Reproduce**

I basically just follow the following procedure:

https://docs.flowiseai.com/integrations/langchain/chat-models/chatlocalai

This basically just involes:
Starting LocalAI via `docker compose`
Starting flowise.
Open flowise in Firefox browser on my local machine using the remote machine's IP and the specific port. 
I type in the ChatLocalAI Basepath the path(s) mentioned above.

I get the error.

**Expected behavior**
No error. 

Test chat should produce text with LocalAI model.

**Setup**

-   Docker version 26.0.0
-   LocalAI: git clone https://github.com/go-skynet/LocalAI
-   Flowise flowise/1.6.0 linux-x64 node-v20.11.1
-   OS remote: Ubuntu 22.04.3 LTS
-   OS local: Windows 10
-   Browser Firefox

**Comment by HenryHengZJ** [comment]
The error looks like it cant reach LocalAI. If you are running both Flowise and LocalAI on docker, you probably need to change the base path to `http://host.docker.internal:8080/v1`
