### ISSUE TITLE
[BUG] Duplicate chatflow fails in 1.6.2

### ISSUE THREAD

**Issue by msiwanHahn** [FlowiseAI/Flowise#2058]
**Describe the bug**
Trying to duplicate chatflow. Duplication fails.
index-DGQWeMvb.js:449  DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'duplicatedFlowData' exceeded the quota.
    at G (http://localhost:3000/assets/index-DGQWeMvb.js:449:123775)
    at onClick (http://localhost:3000/assets/index-DGQWeMvb.js:9:6491)
    at Object.oI (http://localhost:3000/assets/index-BlOiciPs.js:59:9864)
    at aI (http://localhost:3000/assets/index-BlOiciPs.js:59:10018)
    at sI (http://localhost:3000/assets/index-BlOiciPs.js:59:10075)
    at e2 (http://localhost:3000/assets/index-BlOiciPs.js:59:31462)
    at i_ (http://localhost:3000/assets/index-BlOiciPs.js:59:31879)
    at http://localhost:3000/assets/index-BlOiciPs.js:59:36792
    at vy (http://localhost:3000/assets/index-BlOiciPs.js:62:36957)
    at OE (http://localhost:3000/assets/index-BlOiciPs.js:59:8999)
G @ index-DGQWeMvb.js:449

        [NEW] Explain Console errors by using Copilot in Edge: click 
         to explain an error. 
        Learn more
        Don't show again

**To Reproduce**
Steps to reproduce the behavior: Update to version 1.6.2
Open existing chatflow
Go to setting choosing "duplicate chatflow"

**Expected behavior**

**Screenshots**

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation local  & Azure
-   Flowise Version 1.6..2
-  Win 11 / MacOS 14.4.1
-   Browser [e.g. edge, safari & chrome]

**Additional context**

**Comment by HenryHengZJ** [comment]
@msiwanHahn your local storage seems to be full. Try to clear it:
<img width="620" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/7a00c3b7-c2d6-4e05-97b6-6520e3c0d2a1">

**Comment by msiwanHahn** [comment]
Thanks Henry for looking into this. We, my colleague and I tested on several machines (Win / iOS), with different browsers (we deleted the local storage). We get still the same error, independent of running flowise localhost or in our container@ Azure.
