### ISSUE TITLE
[BUG] Cannot convert undefined or null to object - Redis Vector Store

### ISSUE THREAD

**Issue by danielstankw** [FlowiseAI/Flowise#2135]
Due to the issues I had with In-memory vector store I have switched it to the Redis one. Every time I attempt to Upsert Vector Database I get the following error":
![image](https://github.com/FlowiseAI/Flowise/assets/72759092/17beabed-0dd5-4d1b-ba05-87f2f213fd28)

```
2024-04-09 06:58:45 [ERROR]: Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at escapeAllStrings (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/vectorstores/Redis/utils.js:14:12)
    at /usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/vectorstores/Redis/utils.js:18:42
    at Array.forEach (<anonymous>)
    at escapeAllStrings (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/vectorstores/Redis/utils.js:14:22)
    at /usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/vectorstores/Redis/utils.js:18:42
    at Array.forEach (<anonymous>)
    at escapeAllStrings (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/vectorstores/Redis/utils.js:14:22)
    at Redis_VectorStores.upsert (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/vectorstores/Redis/Redis.js:55:54)
    at async buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:265:17)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1698:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1193:13
2024-04-09 06:58:45 [ERROR]: [server]: Error: TypeError: Cannot convert undefined or null to object
Error: TypeError: Cannot convert undefined or null to object
    at buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:326:19)
    at async App.upsertVector (/usr/local/lib/node_modules/flowise/dist/index.js:1698:13)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:1193:13
```

**Comment by HenryHengZJ** [comment]
do you have Redis Stack running on Docker? https://redis.io/docs/latest/operate/oss_and_stack/install/install-stack/docker/

1.) My Flow:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/6514192f-c2ca-408c-bcef-fc646ab85c48)

2.) Upsert result 
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/2f7ff56a-8e91-4824-bafc-5f012da11952)

3.) Vectors on Redis that were upserted:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/5768f779-b7ce-4de7-80ad-1b457e65d615)

**Comment by HenryHengZJ** [comment]
in your flow, you are using LocalAI and Azure, I'd suggest try replacing each one at at time to see which one was causing issue. Also, is it just PDF? have you tried Text file?

**Comment by danielstankw** [comment]
@HenryHengZJ 
Do I need to have redis stack running in docker to use this application? 
I am connecting to redis that is hosted externally.

**Comment by tiberiu89** [comment]
Yes, can confirm this is happening for me also using the pdf loader. It seems that this is the case with some of the pdf file, not all. Found this similar issue https://github.com/FlowiseAI/Flowise/issues/2099

**Comment by danielstankw** [comment]
@HenryHengZJ can this be looked into ? 
Even with document loader it doesnt work. It seems there is a big issue with parsing PDF

**Comment by nguyenhung10012003** [comment]
I have same issue, that is case with pdf file, the docx file, txt is still working

**Comment by nguyenhung10012003** [comment]
I've fixed it in [#3789 ](https://github.com/FlowiseAI/Flowise/pull/3789)
