### ISSUE TITLE
[BUG] Socket closed unexpectedly - Redis

### ISSUE THREAD

**Issue by danielstankw** [FlowiseAI/Flowise#2186]
I have installed the Flowiseai using the traditional method (docker) as well as Kubernetes pods using unofficial chart.
In both of those cases whenever I attempt to connect to the redis store to store vector embeddings I get the following error:

```bash
2024-04-15 07:03:35 [INFO]: Starting Flowise...
2024-04-15 07:03:35 [INFO]: ⚡️ [server]: Flowise Server is listening at 3000
2024-04-15 07:03:36 [INFO]: 📦 [server]: Data Source is being initialized!
2024-04-15 07:03:38 [INFO]: 📦 [server]: Data Source has been initialized!
2024-04-15 07:24:32 [INFO]: ⬆️ POST /api/v1/vector/internal-upsert/962166d0-816d-4c8d-8a2e-341a53495b37
2024-04-15 07:25:32 [ERROR]: uncaughtException:  Socket closed unexpectedly
Error: Socket closed unexpectedly
    at Socket.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/@redis/client/dist/lib/client/socket.js:194:118)
    at Object.onceWrapper (node:events:632:26)
    at Socket.emit (node:events:517:28)
    at TCP.<anonymous> (node:net:350:12)
```

Not sure if this is the issue but it seems like its Redis communication problem:
[https://stackoverflow.com/questions/71574823/reusing-redis-connection-socket-closed-unexpectedly-node-redis](url)
[https://community.fly.io/t/redis-socketclosedunexpectedlyerror-socket-closed-unexpectedly/5897](url)

![image](https://github.com/FlowiseAI/Flowise/assets/72759092/c88d17e8-8c24-4249-94a3-34d3e5073fd0)

**Comment by HenryHengZJ** [comment]
Strange, you should be fine with InMemory since it doesn't make connection. Id suggest try with different vector store, then embeddings, basically divide and conquer

**Comment by danielstankw** [comment]
When I try with the Redis I get the error: 

```
2024-05-23 08:10:08 [ERROR]: uncaughtException:  Socket closed unexpectedly
Error: Socket closed unexpectedly
    at Socket.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/@redis/client/dist/lib/client/socket.js:194:118)
    at Object.onceWrapper (node:events:632:26)
    at Socket.emit (node:events:517:28)
    at TCP.<anonymous> (node:net:350:12)
```

**Comment by danielstankw** [comment]
@HenryHengZJ is there any update on the redis vector store fix?

**Comment by nikitas-novatix** [comment]
Any update ? 
1 year later and we still have the same issue...

I am using Redis for queue mode and i also have the exact same `[ERROR]: uncaughtException:  Socket closed unexpectedly` coming from redis.

@HenryHengZJ we need some sort of keep-alive mechanism or even just a ping at regular intervals.

**Comment by nikitas-novatix** [comment]
@HenryHengZJ Probably found a fix:

Node-redis supports OS-level keep-alives and protocol-level pings via client options:  
https://github.com/redis/node-redis/blob/master/docs/client-configuration.md#client-configuration

By changing **every** place you build or pass a Redis config (whether via `createClient()` or a config object in your queue manager, vector store, pub/sub, etc.) to include:

```diff
--- before
-  // your existing Redis options:
-  url: process.env.REDIS_URL,
-  // or host/port + auth + tls in queuemanager.ts
+  // your existing Redis options:
+  url: process.env.REDIS_URL,
+  // or host/port + auth + tls…
+  
+  // send OS-level TCP keep-alive probes (1st after 4 min):
+  socket: {
+    /* existing socket opts */,
+    keepAlive: true,
+    keepAliveInitialDelay: 240_000,
+  },
+  // send a Redis PING every 4 min to reset Azure’s 10 min idle timer:
+  pingInterval: 240_000,
+  // avoid buffering commands if the socket blips:
+  disableOfflineQueue: true,


you ensure the same Flowise TCP connection is never idle long enough to trigger Azure’s per-connection 10 min timeout.

⚠️ This bug affects all Redis clients in Flowise (queue manager, vector store, SSE, etc.), so I think it should be quite critical for the next release.

**Comment by nikitas-novatix** [comment]
@HenryHengZJ 
I made the necessary changes and tested them, seems to solve it. Will do a PR tomorrow

**Comment by nikitas-novatix** [comment]
@HenryHengZJ @danielstankw 

Here's the PR for this issue:
#4377

**Comment by HenryHengZJ** [comment]
question: why dont just disabled timeout on Redis? Because the recent versions of Redis doesnt have a timeout already https://redis.io/docs/latest/develop/reference/clients/#client-timeouts

**Comment by nikitas-novatix** [comment]
> question: why dont just disabled timeout on Redis? Because the recent versions of Redis doesnt have a timeout already https://redis.io/docs/latest/develop/reference/clients/#client-timeouts

Some providers do enable timeouts. For example Azure Cache for Redis enforces a non-configurable 10-minute idle timeout on server-side connections. Not sure when/if they will update that (they're still on Redis 6.0) but since it's used for a lot of production environments this keepalive mechanism is needed in this case..
