### ISSUE TITLE
[BUG] issue in pnpm run dev 

### ISSUE THREAD

**Issue by AdelEddarai** [FlowiseAI/Flowise#2189]
I got this error when i try pnpm run dev : 

Failed to load resource: net::ERR_CONNECTION_REFUSED
2ErrorBoundary.jsx:31  Uncaught TypeError: Cannot read properties of undefined (reading 'status')
    at ErrorBoundary (ErrorBoundary.jsx:31:62)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)

**Comment by HenryHengZJ** [comment]
Try reinstalling, and clean build before dev
```
pnpm i
pnpm clean
pnpm build-force
pnpm dev
```
