### ISSUE TITLE
[BUG] TypeError: Cannot read properties of undefined (reading 'filePath') 

### ISSUE THREAD

**Issue by BoyuanGao** [FlowiseAI/Flowise#2278]
**Describe the bug**
2024-04-29 15:36:18 [ERROR]: Cannot read properties of undefined (reading 'filePath')
TypeError: Cannot read properties of undefined (reading 'filePath')
    at buildFlow (C:\Users\gaoby\AppData\Roaming\npm\node_modules\flowise\dist\utils\index.js:373:82)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async utilBuildChatflow (C:\Users\gaoby\AppData\Roaming\npm\node_modules\flowise\dist\utils\buildChatflow.js:213:36)
    at async createInternalPrediction (C:\Users\gaoby\AppData\Roaming\npm\node_modules\flowise\dist\controllers\internal-predictions\index.js:7:29)
2024-04-29 15:36:18 [ERROR]: [server]: Error: TypeError: Cannot read properties of undefined (reading 'filePath')
Error: TypeError: Cannot read properties of undefined (reading 'filePath')
    at buildFlow (C:\Users\gaoby\AppData\Roaming\npm\node_modules\flowise\dist\utils\index.js:448:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async utilBuildChatflow (C:\Users\gaoby\AppData\Roaming\npm\node_modules\flowise\dist\utils\buildChatflow.js:213:36)
    at async createInternalPrediction (C:\Users\gaoby\AppData\Roaming\npm\node_modules\flowise\dist\controllers\internal-predictions\index.js:7:29)

**To Reproduce**
1. ask a query in chatbox
2. see the bug

**Expected behavior**
Expect response of agent

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/141694963/8e406fd7-e90f-415f-956e-268f53973829)

**Setup**

-   npx flowise start
-   Flowise Version [1.6.6]
-   OS: Win 11
-   Browser: MS edge

**Comment by BoyuanGao** [comment]
Issue fixed by reconfig the agent node 
![image](https://github.com/FlowiseAI/Flowise/assets/141694963/20e47306-29b3-4af7-9740-145427991d63)
