### ISSUE TITLE
[BUG]Retriever Tool

### ISSUE THREAD

**Issue by nag-24** [FlowiseAI/Flowise#2308]
**Describe the bug**
Retriever Tool fetches the matching docs correctly from Pinecone's database but the retrievals are not sent correctly to LLM .

**To Reproduce**
See Langsmith trace where the correct document is retrieved but the tooloutput is sent to LLM as "toolOutput": "\n\n\n\n\n\n"
https://smith.langchain.com/public/6595062e-ac4f-4d30-85aa-e36b809c8d57/r

**Expected behavior**

**Screenshots**

**Flow**
If applicable, add exported flow in order to help replicating the problem.
![Screenshot 2024-04-30 223530 chatflow](https://github.com/FlowiseAI/Flowise/assets/160205830/7cd65506-ea95-429c-997a-17ab509036f0)

**Setup**

-   Installation [e.g. docker, `npx flowise start`, `pnpm start`] `pnpm start` 
-   Flowise Version [e.g. 1.2.11] 1.6.6
-   OS: [e.g. macOS, Windows, Linux] Windows
-   Browser [e.g. chrome, safari] Chrome

**Additional context**
The LLM responses works fine when accessed through Jupyter notebook using Langchain Python code. See screenshot.
![Screenshot of jupyter notebook output](https://github.com/FlowiseAI/Flowise/assets/160205830/cd2075d6-adec-4b19-b931-a8bc8dd746cf)

**Comment by nag-24** [comment]
also check out this Langmsith trace. https://smith.langchain.com/public/dc94321b-f83d-49bd-8fca-4d308daf52ee/r, the retrieval is again correct but sent as  "context": "<doc id='0'>undefined</doc>\n<doc id='1'>undefined</doc>\n<doc id='2'>undefined</doc>\n<doc id='3'>undefined</doc>"

**Comment by nag-24** [comment]
also check out this Langmsith trace using Conversation agent https://smith.langchain.com/public/b54e85e9-3313-4954-ba94-f0947aa2e32c/r  , Received tool input did not match expected schema

Error: Received tool input did not match expected schema
    at DynamicStructuredTool.call (/usr/src/node_modules/.pnpm/@langchain+core@0.1.57/node_modules/@langchain/core/dist/tools.cjs:68:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/src/packages/components/dist/src/agents.js:315:39
    at async Promise.all (index 0)
    at async AgentExecutor.call (/usr/src/packages/components/dist/src/agents.js:302:30)
    at async AgentExecutor.invoke (/usr/src/node_modules/.pnpm/langchain@0.1.33@aws-crypto+sha256-js@5.2.0@aws-sdk+client-bedrock-runtime@3.422.0@aws-sdk_4nagnmezyqrtxortipronoidfi/node_modules/langchain/dist/chains/base.cjs:58:28)
    at async ConversationalAgent_Agents.run (/usr/src/packages/components/dist/nodes/agents/ConversationalAgent/ConversationalAgent.js:119:19)
    at async utilBuildChatflow (/usr/src/packages/server/dist/utils/buildChatflow.js:243:15)
    at async createInternalPrediction (/usr/src/packages/server/dist/controllers/internal-predictions/index.js:7:29)

**Comment by nag-24** [comment]
It worked now when I changed the metadata field in my pinecone index from "content" to "text". See this langsmith trace.  https://smith.langchain.com/public/078984df-3237-4275-845a-cc633291fc2d/r. I think the issue is fixed now.
