### ISSUE TITLE
[BUG] ollama nomic-embed-text Integration failed

### ISSUE THREAD

**Issue by heqichun** [FlowiseAI/Flowise#2330]
When I use FlowiseAI to integrate ollama nomic-embed-text , it fails, and the error message is as follows:
2024-05-06 17:05:55 2024-05-06 09:05:55 [ERROR]: Request to Ollama server failed: 500 Internal Server Error
2024-05-06 17:05:55 Error: Request to Ollama server failed: 500 Internal Server Error
2024-05-06 17:05:55     at OllamaEmbeddings._request (/usr/src/node_modules/.pnpm/@langchain+community@0.0.39_@aws-crypto+sha256-js@5.2.0_@aws-sdk+client-bedrock-runtime@3.422_oux7xphldewvrf2fc6svjnuw5y/node_modules/@langchain/community/dist/embeddings/ollama.cjs:124:19)
2024-05-06 17:05:55     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-05-06 17:05:55     at async RetryOperation._fn (/usr/src/node_modules/.pnpm/p-retry@4.6.2/node_modules/p-retry/index.js:50:12)
2024-05-06 17:05:55 2024-05-06 09:05:55 [ERROR]: [server]: Error: Error: Request to Ollama server failed: 500 Internal Server Error
2024-05-06 17:05:55 Error: Error: Request to Ollama server failed: 500 Internal Server Error
2024-05-06 17:05:55     at buildFlow (/usr/src/packages/server/dist/utils/index.js:448:19)
2024-05-06 17:05:55     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-05-06 17:05:55     at async utilBuildChatflow (/usr/src/packages/server/dist/utils/buildChatflow.js:213:36)
2024-05-06 17:05:55     at async createInternalPrediction (/usr/src/packages/server/dist/controllers/internal-predictions/index.js:7:29)

**Comment by HenryHengZJ** [comment]
can you try turn on the MMAP of ollama embeddings? 
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/c77a5130-9619-4823-a822-7bb566e70c5f)
