### ISSUE TITLE
[BUG?] Weaviate index name is converted to a name beginning with a capital letter

### ISSUE THREAD

**Issue by BadlyDrawnBoy** [FlowiseAI/Flowise#2338]
**Describe the bug**
When I upsert documents to a weaviate vector database with a index starting with lower letters, disconnect the document wire, save the flow an try to ask a question with the Conversational Retrieval QA Chain it cannot find the index. Only after changing the index "gptpilot" to "Gptpilot" in the Weaviate node it works.

**Flow**
[GPT4 GPT-Pilot QA with Weaviate Chatflow.json](https://github.com/FlowiseAI/Flowise/files/15226998/GPT4.GPT-Pilot.QA.with.Weaviate.Chatflow.json)

**Setup**

-   Installation pnpm start
-   Flowise Version 1.6.6
-   OS: Debian 12
-   local Weaviate 1.24.10 (Docker, latest)
-   local postgres (Debian) for the record manager
-   Browser Firefox

**Additional context**
2024-05-05 22:17:20 [INFO]: [server]: Chatflow d3e66327-b772-4ca9-a823-ff712225382d added into ChatflowPool
2024-05-05 22:17:21 [ERROR]: [server]: Error: Error in similaritySearch Error: Cannot query field "gptpilot" on type "GetObjectsObj". Did you mean "Gptpilot"?: {"response":{"errors":[{"locations":[{"column":6,"line":1}],"message":"Cannot query field \"gptpilot\" on type \"GetObjectsObj\". Did you mean \"Gptpilot\"?","path":null}],"status":200,"headers":{}},"request":{"query":"{Get{gptpilot(nearVector:{vector:[0.010034136,-0.026084688,-0.001746319,-0.028212 ...

... 42,-0.025447814,0.0032148531,-0.020556089,-0.0031454067,-0.0067549176,-0.0047968724]},limit:4){text _additional { distance vector }}}}"}}
    at WeaviateStore.similaritySearchVectorWithScoreAndEmbedding (/home/martin/programme/ai/Flowise/node_modules/.pnpm/@langchain+weaviate@0.0.1_encoding@0.1.13_graphql@16.8.1/node_modules/@langchain/weaviate/dist/vectorstores.cjs:289:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WeaviateStore.similaritySearchVectorWithScore (/home/martin/programme/ai/Flowise/node_modules/.pnpm/@langchain+weaviate@0.0.1_encoding@0.1.13_graphql@16.8.1/node_modules/@langchain/weaviate/dist/vectorstores.cjs:241:38)
    at async WeaviateStore.similaritySearch (/home/martin/programme/ai/Flowise/node_modules/.pnpm/@langchain+core@0.1.57/node_modules/@langchain/core/dist/vectorstores.cjs:108:25)
    at async VectorStoreRetriever.getRelevantDocuments (/home/martin/programme/ai/Flowise/node_modules/.pnpm/@langchain+core@0.1.57/node_modules/@langchain/core/dist/retrievers/index.cjs:70:29)
    at async VectorStoreRetriever._streamIterator (/home/martin/programme/ai/Flowise/node_modules/.pnpm/@langchain+core@0.1.57/node_modules/@langchain/core/dist/runnables/base.cjs:158:9)
    at async VectorStoreRetriever.transform (/home/martin/programme/ai/Flowise/node_modules/.pnpm/@langchain+core@0.1.57/node_modules/@langchain/core/dist/runnables/base.cjs:382:9)
    at async RunnableSequence._streamIterator (/home/martin/programme/ai/Flowise/node_modules/.pnpm/@langchain+core@0.1.57/node_modules/@langchain/core/dist/runnables/base.cjs:1128:30)

**Comment by HenryHengZJ** [comment]
thats not a bug, thats the design by weaviate https://weaviate.io/developers/weaviate/config-refs/schema#class
