### ISSUE TITLE
Error: chatflowsService.getAllChatflows - Error: getRunningExpressApp failed! [BUG]

### ISSUE THREAD

**Issue by aligundogar** [FlowiseAI/Flowise#2350]
Oh snap!
The following error occured when loading this page.
Status: 500
Error: chatflowsService.getAllChatflows - Error: getRunningExpressApp failed!
Please retry after some time. If the issue persists, reach out to us on our Discord server.
Alternatively, you can raise an issue on Github.

![image](https://github.com/FlowiseAI/Flowise/assets/48637822/185b99bf-2d79-4e2a-926b-118486d97652)

**Setup**
Docker, portainer stack.
OS Linux, Debian 12.
Chrome
Version 1.7.1

**Comment by mikkelkrogsholm** [comment]
I think there is a fault in the new docker image.

**Comment by kempec110** [comment]
Same issue running portainer after updating to 1.7.1. Logs:

`2024-05-07T23:49:35.232166845Z 2024-05-07 23:49:35 [INFO]: Starting Flowise...
2024-05-07T23:49:35.276525300Z 2024-05-07 23:49:35 [INFO]: ⚡️ [server]: Flowise Server is listening at 3000
2024-05-07T23:49:35.339526703Z 2024-05-07 23:49:35 [INFO]: 📦 [server]: Data Source is initializing...
2024-05-07T23:49:35.380886021Z Migration "AddDocumentStore1711637331047" failed, error: column "docid" does not exist
2024-05-07T23:49:35.383811798Z 2024-05-07 23:49:35 [ERROR]: ❌ [server]: Error during Data Source initialization: column "docid" does not exist
2024-05-07T23:49:35.383849078Z QueryFailedError: column "docid" does not exist
2024-05-07T23:49:35.383855198Z     at PostgresQueryRunner.query (/usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
2024-05-07T23:49:35.383858798Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-05-07T23:49:35.383861998Z     at async AddDocumentStore1711637331047.up (/usr/local/lib/node_modules/flowise/dist/database/migrations/postgres/1711637331047-AddDocumentStore.js:26:9)
2024-05-07T23:49:35.383865158Z     at async MigrationExecutor.executePendingMigrations (/usr/local/lib/node_modules/flowise/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
2024-05-07T23:49:35.383868638Z     at async DataSource.runMigrations (/usr/local/lib/node_modules/flowise/node_modules/typeorm/data-source/DataSource.js:265:35)
2024-05-07T23:49:35.383871678Z     at async /usr/local/lib/node_modules/flowise/dist/index.js:60:13`

**Comment by xhorizont** [comment]
Same here after upgrade

Migration "AddDocumentStore1711637331047" failed, error: column "docid" does not exist
2024-05-08 08:38:11 [ERROR]: ❌ [server]: Error during Data Source initialization: column "docid" does not exist
QueryFailedError: column "docid" does not exist
    at PostgresQueryRunner.query (/usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AddDocumentStore1711637331047.up (/usr/local/lib/node_modules/flowise/dist/database/migrations/postgres/1711637331047-AddDocumentStore.js:26:9)
    at async MigrationExecutor.executePendingMigrations (/usr/local/lib/node_modules/flowise/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/local/lib/node_modules/flowise/node_modules/typeorm/data-source/DataSource.js:265:35)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:60:13

**Comment by HenryHengZJ** [comment]
put in a fix [here](https://github.com/FlowiseAI/Flowise/pull/2342), will push to a new release shortly

**Comment by HenryHengZJ** [comment]
should be fixed in latest `v1.7.2`, please try redeploy/pull the latest changes again
