### ISSUE TITLE
[BUG] ERROR getrunningexpressappin latest version of flowise

### ISSUE THREAD

**Issue by tradexsrl** [FlowiseAI/Flowise#2371]
Hi this morning , when i open flowise UI i get this error

Status: 500
Error: chatflowsService.getAllChatflows - Error: getRunningExpressApp failed!

tried to restart all container in the stack with no luck
if i look into the log i get this error:
024-05-09 06:43:22 [INFO]: Starting Flowise...

2024-05-09 06:43:22 [INFO]: ⚡️ [server]: Flowise Server is listening at 3000

2024-05-09 06:43:22 [INFO]: 📦 [server]: Data Source is initializing...

Migration "AddDocumentStore1711637331047" failed, error: column "docid" does not exist

2024-05-09 06:43:22 [ERROR]: ❌ [server]: Error during Data Source initialization: column "docid" does not exist

QueryFailedError: column "docid" does not exist

    at PostgresQueryRunner.query (/usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async AddDocumentStore1711637331047.up (/usr/local/lib/node_modules/flowise/dist/database/migrations/postgres/1711637331047-AddDocumentStore.js:26:9)

    at async MigrationExecutor.executePendingMigrations (/usr/local/lib/node_modules/flowise/node_modules/typeorm/migration/MigrationExecutor.js:225:17)

    at async DataSource.runMigrations (/usr/local/lib/node_modules/flowise/node_modules/typeorm/data-source/DataSource.js:265:35)

    at async /usr/local/lib/node_modules/flowise/dist/index.js:60:13

**Comment by HenryHengZJ** [comment]
should be fixed in latest `v1.7.2`, please try redeploy/pull the latest changes again

**Comment by wiliprince** [comment]
Help! I'm currently experiencing this error message:

Status: 500
Error: chatflowsService.getAllChatflows - Error: getRunningExpressApp failed!
![Screenshot 2024-12-19 170147](https://github.com/user-attachments/assets/054a2b75-da5c-4307-ac6e-49da2d25b3b2)

**Comment by chris409409** [comment]
Hi, I have this error too. Who can help? And please don't close this threat before solving the problem here. Thanks!

**Comment by Dexarc** [comment]
Hi
Getting the same issue in the latest 
Status: 500
Error: chatflowsService.getAllChatflows - Error: getRunningExpressApp failed!

**Comment by amritpaul010** [comment]
Status: 500
Error: chatflowsService.getAllChatflows - Error: getRunningExpressApp failed!

same issue. whats the solution?

**Comment by waltonjm** [comment]
Status: 500
Error: chatflowsService.getAllChatflows - Error: getRunningExpressApp failed!

Same issue with upgraded from v2.2.3 to v2.2.5. Did a global install and redeployed Flowise as a service on Render - anyone have a solution?

**Comment by VictorinoConsultoriaTI** [comment]
Estou com o mesmo erro pela minha VPS de projetos DEMOS, só está acontecendo com o Flowise, fiquei sem palavras quando fui mostrar para um possível cliênte.
Status: 500
Error: chatflowsService.getAllChatflows - Error: getRunningExpressApp failed!

Se alguém tiver uma solução, por favor me ajude na resolução. Antecipadamente muito grato.

**Comment by VTorres09** [comment]
Try to disabled the DATABASE_SSL, worked for me.
