### ISSUE TITLE
500 error while upserting data to pgvector [BUG]

### ISSUE THREAD

**Issue by Vladibik** [FlowiseAI/Flowise#2387]
**Describe the bug**
Error 500 trying to upsert any data to the pgvector.

**To Reproduce**
1. Load chatflow
2. Upsert the data to vector store

**Expected behavior**
I expect data to be upserted to the vector store. 

**Screenshots**
The chatflow: https://prnt.sc/oeAMqosPVIRJ
The error: https://prnt.sc/3PzORcgPGX5z
The config of the Postgres in Flowise seems ok: https://prnt.sc/lXhkZUO40O8b (credentials double checked)
Postgres instance is available: https://prnt.sc/QVlRftDdlgmr - I'm not sure if the table structure is fine?

**Flow**
[pgvector.json](https://github.com/FlowiseAI/Flowise/files/15276563/pgvector.json)

**Setup**

-   Installation: `npx flowise start`
-   Flowise Version 1.7.2 
-   OS: Windows
-   Browser Chrome

**Additional context**
Console log 
```
2024-05-10 19:27:41 [ERROR]: [server]: Error: Error: Error: Error inserting: {text}
at buildLangchain (C:\Users\bikes\AppData\Roaming\npm\node_modules\flowise\dist\utils\index.js:331:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async App.upsertVector (C:\Users\bikes\AppData\Roaming\npm\node_modules\flowise\dist\index.js:1342:13)
    at async C:\Users\bikes\AppData\Roaming\npm\node_modules\flowise\dist\index.js:1014:13
```

**Comment by feihangyu** [comment]
Has this problem been solved? I've encountered it too.
