### ISSUE TITLE
Manual Deployment on AWS [BUG]

### ISSUE THREAD

**Issue by BearByteAI** [FlowiseAI/Flowise#2701]
**Describe the bug**
Setup Section, Step 7., on 'docker-compose up -d'
https://docs.flowiseai.com/configuration/deployment/aws#launch-ec2-instance

kwargs = kwargs_from_env(environment=environment, ssl_version=tls_version)
TypeError: kwargs_from_env() got an unexpected keyword argument 'ssl_version'

**To Reproduce**
[Steps to reproduce the behavior:](https://docs.flowiseai.com/configuration/deployment/aws#launch-ec2-instance)

**Expected behavior**
Continue Deployment as documentation

**Screenshots**
[ec2-user@ip-XXX ~]$ cd Flowise/docker/
[ec2-user@ip-XXX docker]$ nano .env
[ec2-user@ip-XXX docker]$ docker-compose up -d
WARNING: The CORS_ORIGINS variable is not set. Defaulting to a blank string.
WARNING: The IFRAME_ORIGINS variable is not set. Defaulting to a blank string.
WARNING: The DEBUG variable is not set. Defaulting to a blank string.
WARNING: The DATABASE_TYPE variable is not set. Defaulting to a blank string.
WARNING: The DATABASE_PORT variable is not set. Defaulting to a blank string.
WARNING: The DATABASE_HOST variable is not set. Defaulting to a blank string.
WARNING: The DATABASE_NAME variable is not set. Defaulting to a blank string.
WARNING: The DATABASE_USER variable is not set. Defaulting to a blank string.
WARNING: The DATABASE_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The DATABASE_SSL variable is not set. Defaulting to a blank string.
WARNING: The DATABASE_SSL_KEY_BASE64 variable is not set. Defaulting to a blank string.
WARNING: The LOG_LEVEL variable is not set. Defaulting to a blank string.
WARNING: The DISABLE_FLOWISE_TELEMETRY variable is not set. Defaulting to a blank string.
WARNING: The MODEL_LIST_CONFIG_JSON variable is not set. Defaulting to a blank string.
Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/.local/lib/python3.9/site-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/compose/cli/docker_client.py", line 124, in docker_client
    kwargs = kwargs_from_env(environment=environment, ssl_version=tls_version)
TypeError: kwargs_from_env() got an unexpected keyword argument 'ssl_version'

**Flow**
-

**Setup**
as documented here https://docs.flowiseai.com/configuration/deployment/aws#launch-ec2-instance

**Additional context**
-

**Comment by inno-elon** [comment]
Also getting this error. I had to downgrade urllib and I'm still able to connect to my instance but i'm not able to view port 3000 in the browser, it just times out.

**Comment by BearByteAI** [comment]
> I was able to eventually fix with my urllib downgrade

Great, did you do it on AWS linux?

**Comment by inno-elon** [comment]
> > I was able to eventually fix with my urllib downgrade
> 
> Great, did you do it on AWS linux?

yes
