### ISSUE TITLE
[BUG] 400 Client Error: Bad Request for url: https://s3.us-east-1.amazonaws.com 

### ISSUE THREAD

**Issue by ParseDark** [FlowiseAI/Flowise#272]
**Describe the bug**
I create a huggingface not it's have the network issue.

```
Error: 400 Client Error: Bad Request for url: https://s3.us-east-1.amazonaws.com/lfs.huggingface.co/repos/36/2c/362cd4772ca1a9fd07d666e19be9b736df444e38495291ed4d6fb4c4d6d7595d/a8fd120b1a0032e70ff3d4b8ab8e46a6d01c2cb08ffe7c007a021c1788928146
    at HfInference.request (/Users/hawei/.local/opt/node-v18.15.0/lib/node_modules/flowise/node_modules/@huggingface/inference/dist/index.js:452:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HfInference.featureExtraction (/Users/hawei/.local/opt/node-v18.15.0/lib/node_modules/flowise/node_modules/@huggingface/inference/dist/index.js:291:17)
    at async RetryOperation._fn (/Users/hawei/.local/opt/node-v18.15.0/lib/node_modules/flowise/node_modules/p-retry/index.js:50:12) {
  attemptNumber: 7,
  retriesLeft: 0
}

```

**To Reproduce**
Follow this diagram create a flow. : 
<img width="1907" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26950370/c1ba4afd-9135-425d-8753-033a609e53b5">

**Expected behavior**
Huggingface node can success running.

**Screenshots**
<img width="1920" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26950370/4bb21e71-bf21-4d79-9c09-2d1942e61e57">
<img width="1112" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26950370/c5a4f4c3-4ba5-4036-a0b3-075a29e4731c">

**Setup**
<img width="572" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26950370/b946efc2-4cfe-4bd1-9c11-a61a716eb7d1">

**Additional context**

**Comment by HenryHengZJ** [comment]
when running on huggingface inference api without using flowise, does it work?

**Comment by HenryHengZJ** [comment]
Should be fixed now
