### ISSUE TITLE
[BUG] "binTools()" error whilst using AWS ChatBedrock

### ISSUE THREAD

**Issue by dheerajbhadani** [FlowiseAI/Flowise#2725]
**Describe the bug**

"binTools()" error whilst using AWS ChatBedrock. Below is error log for reference purpose:
2024-06-26 10:10:56 2024-06-26 09:10:56 [ERROR]: This agent requires that the "bindTools()" method be implemented on the input model.
2024-06-26 10:10:56 Error: This agent requires that the "bindTools()" method be implemented on the input model.
2024-06-26 10:10:56     at prepareAgent (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/agents/ToolAgent/ToolAgent.js:191:15)
2024-06-26 10:10:56 2024-06-26 09:10:56 [ERROR]: [server]: Error: Error: This agent requires that the "bindTools()" method be implemented on the input model.
2024-06-26 10:10:56 Error: Error: This agent requires that the "bindTools()" method be implemented on the input model.
2024-06-26 10:10:56     at buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:493:19)
2024-06-26 10:10:56     at async utilBuildChatflow (/usr/local/lib/node_modules/flowise/dist/utils/buildChatflow.js:222:36)
2024-06-26 10:10:56     at async createInternalPrediction (/usr/local/lib/node_modules/flowise/dist/controllers/internal-predictions/index.js:7:29)

**To Reproduce**

1. Load attached flow
2. Click on 'chat'
3. Type  'Hey!' as input 

**Expected behavior**
Flow should continue without error.

**Screenshots**
![Screenshot 2024-06-26 102503](https://github.com/FlowiseAI/Flowise/assets/7458031/e5942094-8145-4e50-a82f-dd893928853e)

**Flow**
[BindToolErrorReproducible Chatflow.json](https://github.com/user-attachments/files/15985649/BindToolErrorReproducible.Chatflow.json)

**Setup**

-   Installation: docker
-   Flowise Version: 1.8.2
-   OS: WSL
-   Browser: chrome

**Additional context**
It works fine with OpenAI Chat model (ChatOpenAI).

**Comment by HenryHengZJ** [comment]
Tool Agent currently works with certain models, AWSBedrock not yet:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/b1b0612d-0aca-4a3f-ba4e-065855b4dd10)

**Comment by KonstantinOhrimenko** [comment]
It seems the bug can be fixed by updating the `@langchain/community` dependency to version [^0.2.6](https://github.com/langchain-ai/langchainjs/tree/0.2.6/libs/langchain-community), which implements the [bindTools](https://github.com/langchain-ai/langchainjs/blob/eff8512aad53e2c1538059e7cdc9d243ad3e4b72/libs/langchain-community/src/chat_models/bedrock/web.ts#L682) method in the Bedrock Chat Model. Version 0.0.43 is currently in use.

**Comment by HenryHengZJ** [comment]
It will be pushed as part of this PR https://github.com/FlowiseAI/Flowise/pull/2798

**Comment by HenryHengZJ** [comment]
working in v2.0:
![image](https://github.com/user-attachments/assets/762bf935-3f63-4a8f-b0a0-84ee02896da9)

**Comment by yangzishy** [comment]
> working in v2.0: ![image](https://private-user-images.githubusercontent.com/26460777/351415494-762bf935-3f63-4a8f-b0a0-84ee02896da9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MTg4OTgsIm5iZiI6MTcyNTYxODU5OCwicGF0aCI6Ii8yNjQ2MDc3Ny8zNTE0MTU0OTQtNzYyYmY5MzUtM2Y2My00YThmLWIwYTAtODRlZTAyODk2ZGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDEwMjk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkZTI0OWViYjNiZjBjM2QwYmY3MzcyMjA2ZThlYTk0YjVlNDNhODEzYmQzNTU0MDhlMjVmZWE2MDFjYWJmZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p5AXivmcM3-YqqWgw_WnKR1rFSGAiSastayoY7GbUnw)

hello！Can this tool be provided to baiduwenxin model?
