### ISSUE TITLE
[BUG] Flowise not working on macos with flowise 1.8.3

### ISSUE THREAD

**Issue by stigtk** [FlowiseAI/Flowise#2800]
**Describe the bug**
Flowise not working on macos with flowise 1.8.3

**To Reproduce**
fresh installation of flowise on macos

1. npm install -g flowise on macos
2. nxp flowise start
3.
    2024-07-14 09:58:19 [ERROR]: ❌ [server]: Error during Data Source initialization: SQLITE_ERROR: no such column: ChatFlow.isPublic
    QueryFailedError: SQLITE_ERROR: no such column: ChatFlow.isPublic
        at handler (/usr/local/lib/node_modules/flowise/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:88:37)
        at replacement (/usr/local/lib/node_modules/flowise/node_modules/sqlite3/lib/trace.js:25:27)
        at Statement.errBack (/usr/local/lib/node_modules/flowise/node_modules/sqlite3/lib/sqlite3.js:15:21)
4. i flowise Chatflow fails to load view

**Expected behavior**

**Screenshots**
<img width="699" alt="image" src="https://github.com/user-attachments/assets/4f4ad225-7038-4165-b247-b48fa252f892">

<img width="1483" alt="image" src="https://github.com/user-attachments/assets/5282963e-e348-4d82-a553-17d2422efdae">

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation [npm install -g flowise , `npx flowise start`]
-   Flowise Version [1.8.3]
-   OS: [macOS 14.5 ]
-   Browser [chrome]

**Additional context**

**Comment by stigtk** [comment]
Just have to delete the old databse.sqllite from user/.flowise

**Comment by stigtk** [comment]
done
