### ISSUE TITLE
[BUG] Bad request errror at the SearxngSearch Tool

### ISSUE THREAD

**Issue by seonghobae** [FlowiseAI/Flowise#2815]
**Describe the bug**
SearxngSearch Tool shows `Bad request` error even I set tool properly.

**To Reproduce**

1. Go to Searxng tool
2. Link with worker
3. Run with Query

**Expected behavior**
Working without bad requests error.

**Screenshots**
![image](https://github.com/user-attachments/assets/d7564195-d434-4667-b423-892470a59122)
![image](https://github.com/user-attachments/assets/5a1bf29e-ff8a-4a70-a9cc-f5560b150170)

**Flow**
For security reason, I can't export this.

**Setup**

-   Installation: Docker
-   Flowise Version: 81918d5e3ccd
-   OS: Linux
-   Browser: Safari, Edge

**Additional context**
Searxng always works correctly.

**Comment by genwch** [comment]
same here. attached error captured from langsmith
same issue on version 1.8.4 & 1.8.3

`BAD REQUEST

Error: BAD REQUEST
    at SearxngSearch._call (/usr/local/lib/node_modules/flowise/node_modules/@langchain/community/dist/tools/searxng_search.cjs:120:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SearxngSearch.call (/usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/tools.cjs:78:22)
    at async /usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/src/agents.js:315:39
    at async Promise.all (index 0)
    at async AgentExecutor._call (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/src/agents.js:302:30)
    at async AgentExecutor.invoke (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/chains/base.cjs:58:28)
    at async ConversationalAgent_Agents.run (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/agents/ConversationalAgent/ConversationalAgent.js:119:19)
    at async utilBuildChatflow (/usr/local/lib/node_modules/flowise/dist/utils/buildChatflow.js:258:15)
    at async createInternalPrediction (/usr/local/lib/node_modules/flowise/dist/controllers/internal-predictions/index.js:7:29) `

**Comment by kstan79** [comment]
how you guys make it working, it seems not fire at my side
<img width="1278" alt="image" src="https://github.com/user-attachments/assets/7cc48287-f85b-4371-93e4-0aabbdbaee74">

**Comment by HenryHengZJ** [comment]
Fixed in this PR: https://github.com/FlowiseAI/Flowise/pull/3263
