### ISSUE TITLE
[BUG] Flowise , astra db configuration : TypeError: astra_db_ts_1.DataAPIClient is not a constructor

### ISSUE THREAD

**Issue by marelix2** [FlowiseAI/Flowise#2957]
**Describe the bug**

once im trying to upsert data do astra db via flowise im getting error 

```
2024-08-07 09:24:25 [ERROR]: TypeError: astra_db_ts_1.DataAPIClient is not a constructor
Error: TypeError: astra_db_ts_1.DataAPIClient is not a constructor
    at Astra_VectorStores.upsert (/xxx/ai-repo/apps/Flowise/packages/components/dist/nodes/vectorstores/Astra/Astra.js:51:27)
    at async buildFlow (/xxx/ai-repo/apps/Flowise/packages/server/dist/utils/index.js:408:37)
    at async upsertVector (/xxx/ai-repo/apps/Flowise/packages/server/dist/utils/upsertVector.js:115:32)
    at async Object.upsertVectorMiddleware (/xxx/ai-repo/apps/Flowise/packages/server/dist/services/vectors/index.js:9:16)
    at async createInternalUpsert (/xxx/ai-repo/apps/Flowise/packages/server/dist/controllers/vectors/index.js:28:29)
```

**To Reproduce**

1. follow instructions provided in documentation -> [AstraDB](https://docs.flowiseai.com/integrations/langchain/vector-stores/astradb)
2. try to upsert data
3. See error

**Expected behavior**
i guess it should upsert data :D

**Screenshots**
![Screenshot 2024-08-07 at 09 32 53](https://github.com/user-attachments/assets/0ba7b263-2d6a-4ed9-8e88-080c060f2621)

**Flow**
[Astra database loader Chatflow.json](https://github.com/user-attachments/files/16519932/Astra.database.loader.Chatflow.json)

**Setup**
-   Installation: pnpm start
-   Flowise Version: 2.0.1
-   OS: macOS
-   Browser: chrome

**Comment by conornormile** [comment]
I'm getting the same bug. Was working fine but now returning this message when a user submits a query.

**Comment by HenryHengZJ** [comment]
Updated and fixed: https://github.com/FlowiseAI/Flowise/pull/3381
