### ISSUE TITLE
[BUG] Ollama embedding error 500

### ISSUE THREAD

**Issue by IzzyHibbert** [FlowiseAI/Flowise#2976]
I decided to open single and specific tickets instead of a unique one [2944](https://github.com/FlowiseAI/Flowise/issues/2944) because after a bit of investigation the KO on different embeddings have nothing in common.

Test performed on Flowise 2.0.1

### **Case Flowise (docker) => Ollama (no-docker, just in Windows)**
The Ollama endpoint is at http://192.168.178.76:11434 in the test I am keeping the LocalAI chat model and just using Ollama Embedding model (installed in Win, no docker).

The issue here is shown in this picture 
![Screenshot 2024-08-07 alle 09 48 43](https://github.com/user-attachments/assets/c51907af-eb65-4d8c-9799-41d3f0f4f49b)
while FLowise error detail being displayed in Docker is 
![Screenshot 2024-08-07 alle 09 49 31](https://github.com/user-attachments/assets/026e4cb8-2504-4629-b8c9-8a32f84f23ce)

Now let's repeat the same in Postman. The endpoint , in Flowise I use http://192.168.178.76:11434, in Postman is visible here. The Postman test is successful.

![Screenshot 2024-08-07 alle 09 50 53](https://github.com/user-attachments/assets/c994a8e4-8279-4015-b5fc-320a247ea169)

Looks like others reported already the same problem (Error 500), see discord users :

![Screenshot 2024-08-08 alle 10 20 14](https://github.com/user-attachments/assets/2b882912-a991-4027-8cf9-25e53096ec77)

![Screenshot 2024-08-08 alle 10 19 24](https://github.com/user-attachments/assets/615652bb-a33e-4edc-8804-25c76d69e082)

![Screenshot 2024-08-08 alle 10 19 08](https://github.com/user-attachments/assets/a8d4da1e-6e93-40f7-ac87-5c45a5c5afb9)

**Comment by IzzyHibbert** [comment]
I made further tests here after the discoveries of [#2978](https://github.com/FlowiseAI/Flowise/issues/2978), [#2977](https://github.com/FlowiseAI/Flowise/issues/2977).

The reported tests come from the following model [Ollama](https://ollama.com/library/nomic-embed-text).
Ollama is on a Win machine (no docker).

The page doesn't tell the vector. Very likely 512 or 768.
As soon as I changed the vector dimension of in the Vector store, it changed the error to this :




![Screenshot 2024-08-08 alle 14 37 04](https://github.com/user-attachments/assets/6d05869a-2519-4c14-8035-6640811b0fe3)

Or this in debug

```
2024-08-08 12:36:59 [ERROR]: [server]: Error: TypeError: fetch failed
Error: TypeError: fetch failed
    at buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:483:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async utilBuildChatflow (/usr/local/lib/node_modules/flowise/dist/utils/buildChatflow.js:227:36)
    at async createInternalPrediction (/usr/local/lib/node_modules/flowise/dist/controllers/internal-predictions/index.js:7:29)


```

**Comment by HenryHengZJ** [comment]
I havent tried Ollama on Windows, but was able to get it working when I have both FW and Ollama on docker: http://host.docker.internal:8000/

https://docs.flowiseai.com/integrations/langchain/chat-models/chatollama#additional

**Comment by IzzyHibbert** [comment]
I used the mdoel bge-m3 and works.
