### ISSUE TITLE
[BUG] Cannot find module '@langchain/aws'

### ISSUE THREAD

**Issue by darkanubis0100** [FlowiseAI/Flowise#2993]
```
(Flowise) PS C:\Users\Administrator> npx flowise start
2024-08-10 14:45:49 [INFO]: Starting Flowise...
2024-08-10 14:45:49 [INFO]: 📦 [server]: Data Source is initializing...
2024-08-10 14:45:53 [ERROR]: ❌ [server]: Error during initDatabase with file C:\Users\Administrator\node_modules\flowise-components\dist\nodes\retrievers\AWSBedrockKBRetriever\AWSBedrockKBRetriever.js: Cannot find module '@langchain/aws'
Require stack:
- C:\Users\Administrator\node_modules\flowise-components\dist\nodes\retrievers\AWSBedrockKBRetriever\AWSBedrockKBRetriever.js
- C:\Users\Administrator\node_modules\flowise\dist\NodesPool.js
- C:\Users\Administrator\node_modules\flowise\dist\index.js
- C:\Users\Administrator\node_modules\flowise\dist\commands\start.js
- C:\Users\Administrator\node_modules\@oclif\core\lib\module-loader.js
- C:\Users\Administrator\node_modules\@oclif\core\lib\config\plugin.js
- C:\Users\Administrator\node_modules\@oclif\core\lib\config\config.js
- C:\Users\Administrator\node_modules\@oclif\core\lib\config\index.js
- C:\Users\Administrator\node_modules\@oclif\core\lib\command.js
- C:\Users\Administrator\node_modules\@oclif\core\lib\index.js
- C:\Users\Administrator\node_modules\flowise\bin\run
Error: Cannot find module '@langchain/aws'
Require stack:
- C:\Users\Administrator\node_modules\flowise-components\dist\nodes\retrievers\AWSBedrockKBRetriever\AWSBedrockKBRetriever.js
- C:\Users\Administrator\node_modules\flowise\dist\NodesPool.js
- C:\Users\Administrator\node_modules\flowise\dist\index.js
- C:\Users\Administrator\node_modules\flowise\dist\commands\start.js
- C:\Users\Administrator\node_modules\@oclif\core\lib\module-loader.js
- C:\Users\Administrator\node_modules\@oclif\core\lib\config\plugin.js
- C:\Users\Administrator\node_modules\@oclif\core\lib\config\config.js
- C:\Users\Administrator\node_modules\@oclif\core\lib\config\index.js
- C:\Users\Administrator\node_modules\@oclif\core\lib\command.js
- C:\Users\Administrator\node_modules\@oclif\core\lib\index.js
- C:\Users\Administrator\node_modules\flowise\bin\run
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\Administrator\node_modules\flowise-components\dist\nodes\retrievers\AWSBedrockKBRetriever\AWSBedrockKBRetriever.js:3:15)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at C:\Users\Administrator\node_modules\flowise\dist\NodesPool.js:35:46
    at Array.map (<anonymous>)
    at NodesPool.initializeNodes (C:\Users\Administrator\node_modules\flowise\dist\NodesPool.js:32:38)
    at async NodesPool.initialize (C:\Users\Administrator\node_modules\flowise\dist\NodesPool.js:22:9)
    at async App.initDatabase (C:\Users\Administrator\node_modules\flowise\dist\index.js:66:13)
2024-08-10 14:45:54 [INFO]: 📦 [server]: Data Source has been initialized!
2024-08-10 14:45:54 [INFO]: ⚡️ [server]: Flowise Server is listening at :3000
```
So far everything seems to be unaffected until I try to run any workflow. It can take up to 3 minutes to start getting a response and there are so many bugs that even the tools don't work properly.

Just in case, I tried reinstalling Flowise to an earlier version (2.0.3) and it didn't help at all. I also tried to force the installation of the apparently missing module and that didn't work either. For some reason Flowise does not recognize the package.

**Comment by toi500** [comment]
2.0.4

**Comment by HenryHengZJ** [comment]
How are you installing Flowise? Git clone? Or npm or docker?

**Comment by darkanubis0100** [comment]
> How are you installing Flowise? Git clone? Or npm or docker?

Apparently it only happens in the npm version (which is curiously the same version of the repository).

**Comment by HenryHengZJ** [comment]
Ah okay, so you were using `npm install -g flowise`?

**Comment by darkanubis0100** [comment]
> Ah okay, so you were using `npm install -g flowise`?

YeahI have even specified the versions for their respective downgrade but it didn't work.

Just in case, I've been using NodeJS 20, the same version that uses the Dockerfile.

**Comment by HenryHengZJ** [comment]
I am using Node20, and works fine for me though..

Can you try deleting the installed flowise folder and do the install again?

![image](https://github.com/user-attachments/assets/bbb3ddbb-4ca1-4b9b-b915-11625dfd8302)

**Comment by darkanubis0100** [comment]
> I am using Node20, and works fine for me though..
> 
> Can you try deleting the installed flowise folder and do the install again?
> 
> ![image](https://github.com/user-attachments/assets/bbb3ddbb-4ca1-4b9b-b915-11625dfd8302)
> 

It was one of the first things I tried. Could it be that it doesn't work with Windows anymore? Because it's weird.

**Comment by HenryHengZJ** [comment]
I'm using Windows, I think if you try version 2.0.1, it should works for now since we havent introduced that package in that version

**Comment by darkanubis0100** [comment]
> I'm using Windows, I think if you try version 2.0.1, it should works for now since we havent introduced that package in that version

In the end I managed to solve it, instead of npm I used pnpm (much faster and managed to solve all the conflicts).

**Comment by HenryHengZJ** [comment]
What's your steps for that? 
`pnpm install -g flowise`?

**Comment by darkanubis0100** [comment]
> What's your steps for that? `pnpm install -g flowise`?

`pnpm install -g flowise && pnpm exec flowise start`

**Comment by HenryHengZJ** [comment]
Closing for now
