### ISSUE TITLE
[BUG] Advise as how to debug error messages.

### ISSUE THREAD

**Issue by elfxxx** [FlowiseAI/Flowise#302]
Hi FlowiseAI team, thanks a lot, this is an fantastic framework.

I am getting the following errors when running an MRKL agent with different tools. I can't figure out how to debug these messages. Like which node is causing that error. Can anyone advise on how to proceed on the method to debug ?

**Example one** for one workflow with 
<img width="312" alt="screen2" src="https://github.com/FlowiseAI/Flowise/assets/136269067/669c98eb-2236-4729-b382-b50d0116e69d">

Error in the chat:
`TypeError: llm._modelType is not a function`

Full terminal log:

```
TypeError: llm._modelType is not a function
    at isChatModel (/opt/homebrew/lib/node_modules/flowise/node_modules/langchain/dist/prompts/selectors/conditional.cjs:44:16)
    at ConditionalPromptSelector.getPrompt (/opt/homebrew/lib/node_modules/flowise/node_modules/langchain/dist/prompts/selectors/conditional.cjs:31:17)
    at loadQAStuffChain (/opt/homebrew/lib/node_modules/flowise/node_modules/langchain/dist/chains/question_answering/load.cjs:24:60)
    at VectorDBQAChain.fromLLM (/opt/homebrew/lib/node_modules/flowise/node_modules/langchain/dist/chains/vector_db_qa.cjs:94:56)
    at VectorDBQAChain_Chains.init (/opt/homebrew/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chains/VectorDBQAChain/VectorDBQAChain.js:30:48)
    at buildLangchain (/opt/homebrew/lib/node_modules/flowise/dist/utils/index.js:208:72)
    at async App.processPrediction (/opt/homebrew/lib/node_modules/flowise/dist/index.js:539:44)
    at async /opt/homebrew/lib/node_modules/flowise/dist/index.js:294:13

```

**Second example**:
<img width="312" alt="screen1" src="https://github.com/FlowiseAI/Flowise/assets/136269067/2cb00319-1f55-4072-8912-6f46da320fa9">

Error in the chat:
`TypeError: Cannot read properties of undefined (reading 'replaceAll')`

Full terminal log:
```
	TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at /opt/homebrew/lib/node_modules/flowise/node_modules/langchain/dist/embeddings/openai.cjs:114:95
    at Array.map (<anonymous>)
    at OpenAIEmbeddings.embedDocuments (/opt/homebrew/lib/node_modules/flowise/node_modules/langchain/dist/embeddings/openai.cjs:114:82)
    at MemoryVectorStore.addDocuments (/opt/homebrew/lib/node_modules/flowise/node_modules/langchain/dist/vectorstores/memory.cjs:26:54)
    at MemoryVectorStore.fromDocuments (/opt/homebrew/lib/node_modules/flowise/node_modules/langchain/dist/vectorstores/memory.cjs:67:24)
    at InMemoryVectorStore_VectorStores.init (/opt/homebrew/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/vectorstores/InMemory/InMemoryVectorStore.js:50:62)
    at buildLangchain (/opt/homebrew/lib/node_modules/flowise/dist/utils/index.js:208:72)
    at async App.processPrediction (/opt/homebrew/lib/node_modules/flowise/dist/index.js:539:44)
    at async /opt/homebrew/lib/node_modules/flowise/dist/index.js:294:13

```

**Comment by chungyau97** [comment]
Hey there, during `yarn build` or yarn build-force` do you encounter this?
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/9c1a9a45-d2d3-4cfe-b1ec-4ed16bd8e9c6)

**Comment by chungyau97** [comment]
Sorry about the prev confusing message, 
Which platform are you currently running on? Docker/Npx/Yarn

**Comment by elfxxx** [comment]
No worries. Thanks for your help.
I used npx.

**Comment by elfxxx** [comment]
@chungyau97 Any advise on how to proceed ?

**Comment by chungyau97** [comment]
@elfxxx 
Troubleshoot steps:

1. Which version of NodeJS are you working on? 18.16.0
2. Export all your flows 
3. C:\Users\your_name\.flowise delete this folder; **This will delete Flowise data**
4. Do `npm install -g flowise` again; **This will update your Flowise to the latest version**
5. `npx flowise start` again to check whether error still persists.

**Comment by elfxxx** [comment]
Ok. It seems that this resolved it. Thank you.
