### ISSUE TITLE
[BUG]After configuring the Azure OpenAI model as instructed, unable to successfully invoke GPT.

### ISSUE THREAD

**Issue by Gpwner** [FlowiseAI/Flowise#3062]
**Describe the bug**
After configuring the Azure OpenAI model as instructed, I am unable to successfully invoke GPT,such as GPT3.5 and so on.
**To Reproduce**
1、Add a ChatFlows
2、drag an LLM chain,then add a Azure OpenAI component and a Prompt template
3、configure a Credential for Azure OpenAI
4、Save it 
5、Chat with the bot

i got a 'Connection error.'

**Setup**

-   Installation [`pnpm start`]- (https://github.com/FlowiseAI/Flowise?tab=readme-ov-file#setup)
-   Flowise Version [2.0.4]
-   OS: [ Windows]
-   Browser [chrome]

**Additional context**

Always got this error:
```
2024-08-27 14:52:06 [INFO]: ⬆️ POST /api/v1/node-load-method/azureOpenAI
2024-08-27 14:54:07 [INFO]: ⬆️ POST /api/v1/chatflows
2024-08-27 14:54:13 [INFO]: ⬆️ POST /api/v1/internal-prediction/e1b36727-8589-4071-9710-e79ad98c2f16
2024-08-27 14:54:13 [INFO]: [server]: Chatflow e1b36727-8589-4071-9710-e79ad98c2f16 added into ChatflowPool
2024-08-27 14:55:35 [ERROR]: [server]: Error: Connection error.
Error: Connection error.
    at OpenAI.makeRequest (D:\PycharmProjects\Flowise\node_modules\.pnpm\openai@4.51.0_encoding@0.1.13\node_modules\openai\core.js:304:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async D:\PycharmProjects\Flowise\node_modules\.pnpm\@langchain+openai@0.0.30_encoding@0.1.13_langchain@0.2.12_@aws-sdk+client-s3@3.624.0_@aws-sdk_v7hdqt5a3unkzskojvmttjcn2a\node_modules\@langchain\openai\dist\llms.cjs:508:29
    at async RetryOperation._fn (D:\PycharmProjects\Flowise\node_modules\.pnpm\p-retry@4.6.2\node_modules\p-retry\index.js:50:12)
```
By the way,I think my network is ok,a js demo to call azure api from my PC successfully:
```
const {AzureOpenAI} = require("openai");

const https = require('https');


const endpoint = "https://southindia-aicc-bazhan.openai.azure.com";
const apiKey = "";
const apiVersion = "2024-02-15-preview";
const deployment = "gpt-35-turbo";
const agent = new https.Agent({
    rejectUnauthorized: false,
});


const prompt = [{"role": "system", "content": "what is a apple?"}]

async function main() {
    console.log("== Get completions Sample ==");

    const client = new AzureOpenAI({endpoint, apiKey, apiVersion, deployment, httpAgent: agent});

    const result = await client.chat.completions.create({messages: prompt, model: deployment, max_tokens: 1000});

    for (const choice of result.choices) {
        console.log(choice.message.content);
    }
}

main().catch((err) => {
    console.error("Error occurred:", err);
});

module.exports = {main};

```
![image](https://github.com/user-attachments/assets/33e7e4e5-991f-4d26-b8db-d5055ac957f1)

Can anyone help?

**Comment by Gpwner** [comment]
@HenryHengZJ 能否帮忙解答一下，多谢

**Comment by Gpwner** [comment]
我自己摸索出了在js中调用azure open ai的方法：
```
const {AzureOpenAI} = require("openai");

const https = require('https');


const endpoint = "/";
const apiKey = "";
const apiVersion = "";
const deployment = "4o-mini";
const agent = new https.Agent({
    rejectUnauthorized: false,
});


const prompt = [{"role": "system", "content": "如何快速缓解疲劳？"}]

async function main() {
    console.log("== Get completions Sample ==");

    const client = new AzureOpenAI({endpoint, apiKey, apiVersion, deployment, httpAgent: agent});

    const result = await client.chat.completions.create({messages: prompt, model: deployment, max_tokens: 1000});

    for (const choice of result.choices) {
        console.log(choice.message.content);
    }
}

main().catch((err) => {
    console.error("Error occurred:", err);
});

module.exports = {main};


```

但是目前还不知道，应该如何对接flowise平台的AzureOpenAI组件，有人能帮忙解决一下吗,感激不尽

**Comment by Gpwner** [comment]
Despite following this guide for configuration, I still have that error [Link to the documentation](https://docs.flowiseai.com/integrations/langchain/chat-models/azure-chatopenai-1).
![image](https://github.com/user-attachments/assets/1b5dc822-d641-4bfe-ba90-8cea65c1b47d)

**Comment by Gpwner** [comment]
here are my chatflow:
![image](https://github.com/user-attachments/assets/d7d55139-54aa-4a6f-a241-1f5d0edd3c30)
and here is my Credential of Azure OpenAI
![image](https://github.com/user-attachments/assets/aa7dad75-63cb-4be3-80cc-589439854f97)
