### ISSUE TITLE
Error buildAgentGraph - Invalid update for channel start:supervisor. Values: start,start

### ISSUE THREAD

**Issue by ispkumar** [FlowiseAI/Flowise#3082]
After deploying the Flowise in GCP cluster I am encountering below error for sequential agents

Error buildAgentGraph - Invalid update for channel start:supervisor. Values: start,start

Error: EphemeralValue can only receive one value per step.

**Comment by oleksandr-lytvynenko** [comment]
Got the same error as well.
![Screenshot 2024-08-27 at 11 25 49](https://github.com/user-attachments/assets/d4aa7f2c-17e1-4d52-a173-c8c80be737ce)

Flowise stdout output:
```
2024-08-27 08:15:50 [INFO]: [server]: Chatflow 6db3b82b-2cad-49d9-8196-3c305251dc2d_5adaf888-1d10-4aaa-bbdd-a3eeeec2831d added into ChatflowPool
2024-08-27 08:15:50 [ERROR]: [server]: Error: Invalid update for channel start:frontline_support. Values: __start__,__start__
Error: EphemeralValue can only receive one value per step.
Error: Invalid update for channel start:frontline_support. Values: __start__,__start__
Error: EphemeralValue can only receive one value per step.
    at buildAgentGraph (/usr/local/lib/node_modules/flowise/dist/utils/buildAgentGraph.js:339:19)
    at async utilBuildAgentResponse (/usr/local/lib/node_modules/flowise/dist/utils/buildChatflow.js:363:31)
    at async utilBuildChatflow (/usr/local/lib/node_modules/flowise/dist/utils/buildChatflow.js:159:20)
    at async createInternalPrediction (/usr/local/lib/node_modules/flowise/dist/controllers/internal-predictions/index.js:7:29)
```

To reproduce:

1 . Clone "Support Routing System" marketplace agentlow
  
![Screenshot 2024-08-27 at 11 20 08](https://github.com/user-attachments/assets/fa0d3303-1cd6-47de-803a-924c117743cc)

2 . Choose OpenAI creds here
![Screenshot 2024-08-27 at 11 23 50](https://github.com/user-attachments/assets/4a099a6b-ca64-4006-b7ed-54e31b76fd58)


3 . Remove these edges 
![Screenshot 2024-08-27 at 11 25 30](https://github.com/user-attachments/assets/9bece34b-c026-4697-89bd-bc22823e8e4e)

4 . Start chat , type anything as a first message

**Comment by oleksandr-lytvynenko** [comment]
Error was reproduced for [v2.0.5](https://hub.docker.com/layers/flowiseai/flowise/2.0.5/images/sha256-dcd250feac7fb47802af9b25dd409f805607db921a956d099471d1e62c1602b3?context=explore)

For 2.0.4, it works OK

**Comment by dDoom** [comment]
I have same problem reproduced to [v2.0.5](https://hub.docker.com/layers/flowiseai/flowise/2.0.5/images/sha256-dcd250feac7fb47802af9b25dd409f805607db921a956d099471d1e62c1602b3?context=explore)

**Comment by HenryHengZJ** [comment]
hmm im not able to replicate the issue, have my Docker instance v2.0.6 deployed on Railway:
![image](https://github.com/user-attachments/assets/9ddf9437-9f9a-4e03-9d6a-82d5325fcb1d)
