### ISSUE TITLE
[BUG] Upsert - Error: vectorsService.upsertVector - Error: TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by ApplicationError** [FlowiseAI/Flowise#3113]
**Describe the bug**
Error: vectorsService.upsertVector - Error: TypeError: Cannot read properties of undefined (reading '0')

I've setup a new Flowise project with the following components & configuration:

Conversational Retrieval QA Chain
- Chat Model
-- GroqChat (Model Name: llama-3.1-405b-reasoning)
- Vector Store Retriever
-- Pinecone
--- Embeddings
---- VoyageAI Embeddings (Model name: voyage-2)
--- Document
---- Pdf File (.pdf file)
---- File Loader (.txt file)
--- Text Splitter (Chuck Size: 1000, Chunk Coverlap: 200)

Check I go to "upsert" the data to Pinecone I get that error message.
Error: vectorsService.upsertVector - Error: TypeError: Cannot read properties of undefined (reading '0')

**To Reproduce**

1.) Setup as outlined above
2.) Save project
3.) Click on green "upsert" icon
4.) Click on green "upsert" button

**Expected behavior**
The data from the PDF and the TXT file to be stored in the Pinecone vector store.

**Setup**

-   Installation: Render / Docker
-   Flowise Version: 2.0.7

**Render.com Logs**

error 	2024-08-29 19:57:30 [ERROR]: TypeError: Cannot read properties of undefined (reading '0')
error 	Error: TypeError: Cannot read properties of undefined (reading '0')
info 	at Pinecone_VectorStores.upsert (/usr/src/packages/components/dist/nodes/vectorstores/Pinecone/Pinecone.js:80:27)
info 	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
info 	at async buildFlow (/usr/src/packages/server/dist/utils/index.js:415:37)
info 	at async upsertVector (/usr/src/packages/server/dist/utils/upsertVector.js:126:32)
info 	at async Object.upsertVectorMiddleware (/usr/src/packages/server/dist/services/vectors/index.js:9:16)
info 	at async createInternalUpsert (/usr/src/packages/server/dist/controllers/vectors/index.js:28:29)
error 	2024-08-29 19:57:30 [ERROR]: [server]: Error: Error: TypeError: Cannot read properties of undefined (reading '0')
error 	Error: Error: TypeError: Cannot read properties of undefined (reading '0')
info 	at buildFlow (/usr/src/packages/server/dist/utils/index.js:493:19)
info 	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
info 	at async upsertVector (/usr/src/packages/server/dist/utils/upsertVector.js:126:32)
info 	at async Object.upsertVectorMiddleware (/usr/src/packages/server/dist/services/vectors/index.js:9:16)
info	at async createInternalUpsert (/usr/src/packages/server/dist/controllers/vectors/index.js:28:29)

![2024-08-29 at 4 14 PM](https://github.com/user-attachments/assets/e0d89a5a-9165-4f6b-919d-34df226694da)

**Comment by HenryHengZJ** [comment]
If you switch to other embeddings model it should works. Seen this issue with voyage embeddings, mostly due to the rate limit

**Comment by ApplicationError** [comment]
> If you switch to other embeddings model it should works. Seen this issue with voyage embeddings, mostly due to the rate limit

Thank you very much for the reply. Do you have any recommendations for embedding models that would work best?

**Comment by Vortigern-source** [comment]
I have a similar issue, Im not sure what embedding to use with groq if VoyageAI isnt working the best

**Comment by Vortigern-source** [comment]
What embeddings can be used that are free? Also are you saying that reducing the rate limit option should fix it?

**Comment by jockharkness** [comment]
> If you switch to other embeddings model it should works. Seen this issue with voyage embeddings, mostly due to the rate limit

I have a similar setup (except using in-memory vector store) and the exact same error message.

I changed to OpenAI embeddings and it didn't fix the issue, still getting the same error message

**Comment by abslearn** [comment]
Same issue here. I changed to OpenAI embeddings and it didn't fix the issue, still getting the same error message

**Comment by ZellW** [comment]
Same problem as everyone else.  Sure hope it gets fixed.  Starting to have too many problems with Flowise, something I used to really like.

**Comment by harnalashok** [comment]
Ollama embeddings nomic-embed-text worked for me
