### ISSUE TITLE
[BUG] Claude Sonnet 3.5 based Software Team (from Marketplace) consistently fails with "found multiple assistant roles in a row"

### ISSUE THREAD

**Issue by TiGz** [FlowiseAI/Flowise#3147]
**Describe the bug**

When I clone the "Software Team" sequential multi-agent flow from the Marketplace and replace the Open AI chat model with Anthropic Chat Model (Claude Sonnet 3.5) and then issue a user request like:

"Create a one page web app where the user can play tic tac toe"

I get the following flow:
supervisor
software_engineer
supervisor
code_reviewer
supervisor
software_engineer

but this last call to Anthropic fails with:

400 {"type":"error","error":{"type":"invalid_request_error","message":"messages: roles must alternate between \"user\" and \"assistant\", but found multiple \"assistant\" roles in a row"}}

Error: 400 {"type":"error","error":{"type":"invalid_request_error","message":"messages: roles must alternate between \"user\" and \"assistant\", but found multiple \"assistant\" roles in a row"}}
    at APIError.generate (/Users/adam/dev/higherleveldev/Flowise/node_modules/.pnpm/@anthropic-ai+sdk@0.21.1_encoding@0.1.13/node_modules/@anthropic-ai/sdk/error.js:40:20)
    at Anthropic.makeStatusError (/Users/adam/dev/higherleveldev/Flowise/node_modules/.pnpm/@anthropic-ai+sdk@0.21.1_encoding@0.1.13/node_modules/@anthropic-ai/sdk/core.js:263:33)
    at Anthropic.makeRequest (/Users/adam/dev/higherleveldev/Flowise/node_modules/.pnpm/@anthropic-ai+sdk@0.21.1_encoding@0.1.13/node_modules/@anthropic-ai/sdk/core.js:306:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (/Users/adam/dev/higherleveldev/Flowise/node_modules/.pnpm/p-retry@4.6.2/node_modules/p-retry/index.js:50:12)

This same user input always works fine for Open AI.

**To Reproduce**

see above

**Expected behavior**
Swapping out Open AI for Anthropic Claude should be feasible for the Software Team flow and still have it work reliably.

**Setup**

-   Installation `pnpm start`
-   Flowise Version 2.0.7
-   OS: macOS (Apple Silicon)
-   Browser chrome

**Additional context**
Is this a known issue with Claude? Has anyone from the Langchain world talked to anyone at Anthropic about this?
Or is it likely to be a Flowise issue? Or a Langchain issue?

**Comment by HenryHengZJ** [comment]
This is a known issue with Claude for now. As Claude expect every messages to have alternate roles, whereas OpenAI does not. Since each agent within agentflow is being treated as "human" role, thats why the error

**Comment by HenryHengZJ** [comment]
Now resolved, Anthropic removed this restriction
