### ISSUE TITLE
[BUG] - CSV Loader usable issue in Document Store

### ISSUE THREAD

**Issue by nmoturi** [FlowiseAI/Flowise#3159]
**Describe the bug**

Process issue using the CSV loader in Document Store. Below is the error

**To Reproduce**

Document Store, Add a new Document Loader - CSV Loader with Recursive Character Text Splitter
3. Click on '....'
Process
6. See error

[ERROR]: unhandledRejection: Invalid URL

TypeError: Invalid URL

    at new URL (node:internal/url:797:36)

    at parseUrl (/usr/local/lib/node_modules/flowise/node_modules/@aws-sdk/client-s3/node_modules/@smithy/url-parser/dist-cjs/index.js:29:21)

    at toEndpointV1 (/usr/local/lib/node_modules/flowise/node_modules/@aws-sdk/client-s3/node_modules/@smithy/middleware-endpoint/dist-cjs/index.js:119:41)

    at customEndpointProvider (/usr/local/lib/node_modules/flowise/node_modules/@aws-sdk/client-s3/node_modules/@smithy/middleware-endpoint/dist-cjs/index.js:239:65)

**Expected behavior**

Process the document

**Screenshots**

<img width="418" alt="image" src="https://github.com/user-attachments/assets/492bd675-2e65-4649-934f-97ae1547b45b">

**Setup**

-   Installation [e.g. docker, `npx flowise start`, `pnpm start`]
Docker Installation
-   Flowise Version [e.g. 1.2.11]
v2.0.7
-   OS: [e.g. macOS, Windows, Linux]
Linux
-   Browser [e.g. chrome, safari]
Chrome

**Comment by HenryHengZJ** [comment]
works for me: 
![image](https://github.com/user-attachments/assets/baf69e31-6dc0-46c9-9b80-03d31589a1ca)

![image](https://github.com/user-attachments/assets/f506e69e-6189-44fd-ba4c-3996680210c2)

![image](https://github.com/user-attachments/assets/14e28ad1-e260-46be-8dba-cb19aaf50056)

**Comment by nmoturi** [comment]
Thanks, Henry. That's very strange. I have precisely the same flow. The logs indicate the below error, is there any reason why it's trying to access aws-sdk or this is normal..?

-Naran

at new URL (node:internal/url:797:36)

at parseUrl (/usr/local/lib/node_modules/flowise/node_modules/@aws-sdk/client-s3/node_modules/@smithy/url-parser/dist-cjs/index.js:29:21)

at toEndpointV1 (/usr/local/lib/node_modules/flowise/node_modules/@aws-sdk/client-s3/node_modules/@smithy/middleware-endpoint/dist-cjs/index.js:119:41)

at customEndpointProvider (/usr/local/lib/node_modules/flowise/node_modules/@aws-sdk/client-s3/node_modules/@smithy/middleware-endpoint/dist-cjs/index.js:239:65)

**Comment by HenryHengZJ** [comment]
I'm not sure, but does it happen only on one CSV? Can you try other CSV as well?

**Comment by nmoturi** [comment]
Hi Henry,

I am getting the same error for any CSV and even for the PDF documents..

TypeError: Invalid URL
    at new URL (node:internal/url:797:36)
    at parseUrl ***@***.******@***.***/url-parser/dist-cjs/index.js:29:21)
    at toEndpointV1 ***@***.******@***.***/middleware-endpoint/dist-cjs/index.js:119:41)
    at customEndpointProvider ***@***.******@***.***/middleware-endpoint/dist-cjs/index.js:239:65)

Thanks,
Naran
From: Henry Heng ***@***.***>
Date: Tuesday, 17 September 2024 at 4:28 AM
To: FlowiseAI/Flowise ***@***.***>
Cc: Naran M ***@***.***>, Author ***@***.***>
Subject: Re: [FlowiseAI/Flowise] [BUG] - CSV Loader usable issue in Document Store (Issue #3159)

I'm not sure, but does it happen only on one CSV? Can you try other CSV as well?

**Comment by moturi12** [comment]
This issue is resolved, I was using the S3 for blob storage and pointing to wrong endpoint
Thanks,
Naran
