### ISSUE TITLE
[BUG]   pdf flow results in ==> message: 'PDFDocument: stream must have data'

### ISSUE THREAD

**Issue by ashokrs** [FlowiseAI/Flowise#319]
Installed Flowise on my ubuntu instance on AWS EC2.
Created a pdf flow workflow.
Put all the keys required.
Uploaded a pdf document via the PDF parser component.
Then, opened the chat interface and got an error.

    at UnknownErrorExceptionClosure (/usr/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:443:37)
    at Object.<anonymous> (/usr/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:446:2)
    at __w_pdfjs_require__ (/usr/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:45:30)
    at Object.<anonymous> (/usr/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:7939:23)
    at __w_pdfjs_require__ (/usr/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:45:30)
    at /usr/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:88:18
    at /usr/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:91:10
    at webpackUniversalModuleDefinition (/usr/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:18:20)
    at Object.<anonymous> (/usr/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:25:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14) {
  message: 'PDFDocument: stream must have data',
  details: 'Error: PDFDocument: stream must have data'

**Comment by govind-kumarr** [comment]
@ashokrs  I think @HenryHengZJ  has added the pull request for this issue.

**Comment by ashokrs** [comment]
@govind-kumarr thanks.
However, I ahd an fortunate accident as the system worked by just doing as described below:
I exported the flow as a JSON file and saved it. Navigated to the previous screen.
Came back and loaded the same workflow again. This time, it worked. Those errors went away.
~~~
I could run "Flowise" by logged in via "x2go" to the EC2 instance as well as configuring the firewall rules and able to launch on my laptop's web browser @ home. No issues. All good.

**Comment by HenryHengZJ** [comment]
dont think ive seen this error before. Is it resolved now @ashokrs ?

**Comment by ashokrs** [comment]
Yes. Resolved. 
As I said, after the error I had an fortunate accident as the system worked by just doing as described below:
I exported the flow as a JSON file and saved it. Navigated to the previous screen.
Came back and loaded the same workflow again. This time, it worked. Those errors went away.

**Comment by simsherpa** [comment]
I'm encountering the same error:

`Error
    at UnknownErrorExceptionClosure (/opt/homebrew/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:443:37)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:446:2)
    at __w_pdfjs_require__ (/opt/homebrew/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:45:30)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:7939:23)
    at __w_pdfjs_require__ (/opt/homebrew/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:45:30)
    at /opt/homebrew/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:88:18
    at /opt/homebrew/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:91:10
    at webpackUniversalModuleDefinition (/opt/homebrew/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:18:20)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/flowise/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:25:3)
    at Module._compile (node:internal/modules/cjs/loader:1255:14) {
  message: 'PDFDocument: stream must have data',
  details: 'Error: PDFDocument: stream must have data'
}`

**Comment by JNNelson** [comment]
Hello.
How did you solve it?
I have the same problem.
Docker v26.1.4
I've already tried with version 1.8.3 and also with 1.72.
VPS Contabo

**Comment by JNNelson** [comment]
@simsherpa How did you solve it?
