### ISSUE TITLE
[BUG] Custom tools can't import modules

### ISSUE THREAD

**Issue by turbotankist** [FlowiseAI/Flowise#3278]
**Describe the bug**
I try to import standart npm module  const { exec } = require('child_process');
but it fails with error:
```
Cannot find module 'child_process'

VMError: Cannot find module 'child_process'
    at LegacyResolver.resolveFull (/usr/local/lib/node_modules/flowise/node_modules/@flowiseai/nodevm/lib/resolver.js:126:9)
    at LegacyResolver.resolveFull (/usr/local/lib/node_modules/flowise/node_modules/@flowiseai/nodevm/lib/resolver.js:316:16)
    at LegacyResolver.resolveFull (/usr/local/lib/node_modules/flowise/node_modules/@flowiseai/nodevm/lib/resolver-compat.js:147:17)
    at LegacyResolver.resolve (/usr/local/lib/node_modules/flowise/node_modules/@flowiseai/nodevm/lib/resolver.js:121:15)
    at resolve (/usr/local/lib/node_modules/flowise/node_modules/@flowiseai/nodevm/lib/nodevm.js:317:21)
    at VM2 Wrapper.apply (/usr/local/lib/node_modules/flowise/node_modules/@flowiseai/nodevm/lib/bridge.js:490:11)
    at requireImpl (/usr/local/lib/node_modules/flowise/node_modules/@flowiseai/nodevm/lib/setup-node-sandbox.js:90:19)
    at require (/usr/local/lib/node_modules/flowise/node_modules/@flowiseai/nodevm/lib/setup-node-sandbox.js:171:10)
    at /usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/tools/CustomTool:1:115
    at /usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/tools/CustomTool:25:3
    at VM2 Wrapper.apply (/usr/local/lib/node_modules/flowise/node_modules/@flowiseai/nodevm/lib/bridge.js:490:11)
    at NodeVM.run (/usr/local/lib/node_modules/flowise/node_modules/@flowiseai/nodevm/lib/nodevm.js:497:23)
    at DynamicStructuredTool._call (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/tools/CustomTool/core.js:79:35)
    at DynamicStructuredTool.call (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/tools/CustomTool/core.js:40:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/src/agents.js:319:39
```
`const fetch = require('node-fetch');` works fine

**To Reproduce**

create custom tool with import anything else node-fetch
const { exec } = require('child_process');

**Expected behavior**
The [documentation](https://docs.flowiseai.com/integrations/langchain/tools/custom-tool#import-external-dependencies) says 
`You can import any built-in NodeJS and supported into Function `
but build-in child_process and os doesn't work

**Setup**

-   flowiseai/flowise:2.1.1 container in EKS

**Comment by HenryHengZJ** [comment]
you need to specify in env file: https://docs.flowiseai.com/configuration/environment-variables#for-built-in-and-external-dependencies

**Comment by turbotankist** [comment]
Thanks, It's working
