### ISSUE TITLE
Error "Expected a Runnable, function or object. Instead got an unsupported type" with a simple RAG Flow

### ISSUE THREAD

**Issue by n0valis** [FlowiseAI/Flowise#3308]
**Describe the bug**
I have created a simple RAG Flow which I wanted to test with a pdf document or a webpage. Both upserts work well but in the chat I ask a question about anything I get an error message: Error: Expected a Runnable, function or object.
Instead got an unsupported type.
Here's the flow
![Flow](https://github.com/user-attachments/assets/0c68e301-1d95-4d85-a6d1-5897bec2f0dd)

**Setup**

-   Installation`npx flowise start`
-   Flowise Version can't find it, the latest, installed yesterday
-   OS: Windows
-   Browser chrome

**Additional context**
`Error: Expected a Runnable, function or object.
Instead got an unsupported type.
    at _coerceToRunnable (C:\Users\smaug\AppData\Local\npm-cache\_npx\8b95a19c5c9c8708\node_modules\@langchain\core\dist\runnables\base.cjs:1772:15)
    at _coerceToRunnable (C:\Users\smaug\AppData\Local\npm-cache\_npx\8b95a19c5c9c8708\node_modules\@langchain\core\dist\runnables\base.cjs:1765:30)
    at RunnableBinding.pipe (C:\Users\smaug\AppData\Local\npm-cache\_npx\8b95a19c5c9c8708\node_modules\@langchain\core\dist\runnables\base.cjs:354:19)
    at createRetrieverChain (C:\Users\smaug\AppData\Local\npm-cache\_npx\8b95a19c5c9c8708\node_modules\flowise-components\dist\nodes\chains\ConversationalRetrievalQAChain\ConversationalRetrievalQAChain.js:256:53)
    at createChain (C:\Users\smaug\AppData\Local\npm-cache\_npx\8b95a19c5c9c8708\node_modules\flowise-components\dist\nodes\chains\ConversationalRetrievalQAChain\ConversationalRetrievalQAChain.js:287:28)
    at ConversationalRetrievalQAChain_Chains.init (C:\Users\smaug\AppData\Local\npm-cache\_npx\8b95a19c5c9c8708\node_modules\flowise-components\dist\nodes\chains\ConversationalRetrievalQAChain\ConversationalRetrievalQAChain.js:133:29)
    at buildFlow (C:\Users\smaug\AppData\Local\npm-cache\_npx\8b95a19c5c9c8708\node_modules\flowise\dist\utils\index.js:440:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async utilBuildChatflow (C:\Users\smaug\AppData\Local\npm-cache\_npx\8b95a19c5c9c8708\node_modules\flowise\dist\utils\buildChatflow.js:227:36)
    at async createAndStreamInternalPrediction (C:\Users\smaug\AppData\Local\npm-cache\_npx\8b95a19c5c9c8708\node_modules\flowise\dist\controllers\internal-predictions\index.js:32:29)`

**Comment by HenryHengZJ** [comment]
Im guessing there is some sort of cache, can you try creating a new flow and see?

**Comment by n0valis** [comment]
It seems you were right
