### ISSUE TITLE
[BUG] multi_tool_use.parallel bug using AgentFlows with GPT-4o

### ISSUE THREAD

**Issue by dkindlund** [FlowiseAI/Flowise#3352]
**Describe the bug**
Hey @HenryHengZJ, after experimenting with multiple AgentFlows in Flowise using GPT-4o, I've encountered a well-known upstream bug with GPT-4o called the "multi_tool_use.parallel bug" as explained here:
https://community.openai.com/t/model-tries-to-call-unknown-function-multi-tool-use-parallel/490653
https://community.openai.com/t/the-multi-tool-use-parallel-bug-and-how-to-fix-it/880771

Essentially, when you create an AgentFlow in Flowise and setup at least 1 supervisor and 2 workers, where each worker has more than about 4 tools, then about 20% of the time during normal prompts, GPT-4o starts *hallucinating* an _unknown_ tool named `multi_tool_use.parallel` which you can see in the Langfuse trace logs with an error like this:

```
Error: 400 litellm.BadRequestError: AzureException BadRequestError - Error code: 400 - {'error': {'message': "Invalid 'messages[3].tool_calls[0].function.name': string does not match pattern. Expected a string that matches the pattern '^[a-zA-Z0-9_-]+$'.", 'type': 'invalid_request_error', 'param': 'messages[3].tool_calls[0].function.name', 'code': 'invalid_value'}}
Received Model Group=gpt-4o
Available Model Group Fallbacks=None
```

To be crystal clear, this is _clearly_ a bug within the GPT-4o model. Ultimately, this is something OpenAI needs to fix. HOWEVER, some developers have built "workarounds" for this problem, and I'm wondering if you'd be able/open to building a workaround in Flowise as well.

Here is an example of one such workaround:
https://community.openai.com/t/model-tries-to-call-unknown-function-multi-tool-use-parallel/490653/34

Let me know your thoughts here -- this obviously impacts any Flowise user who wants to use AgentFlows with GPT-4o models.

**To Reproduce**

1. Create a new AgentFlow using GPT-4o
2. Specify 1 supervisor and at least 2 workers, where each worker needs to be linked to 4 or more tools
3. Feed in at least 100 prompts with Langfuse tracing enabled
4. See that about 20% of the time through Langfuse, the `multi_tool_use.parallel` bug get thrown.

**Expected behavior**
Ideally, I'd like Flowise to be able to handle and work around this bug.

**Comment by HenryHengZJ** [comment]
Oh thats interesting.. will take a look and see how to come up with a workaround, hopefully openai is able to solve this

**Comment by dkindlund** [comment]
Hey @HenryHengZJ , just providing an incremental update on this.  This problem _still_ exists with the Aug 2024 version of the GPT-4o models, unfortunately.  When using AgentFlows in Flowise, the error manifests as this sort of error:

```
Error: Error buildAgentGraph - Branch condition returned unknown or null destination
    at buildAgentGraph (/usr/local/lib/node_modules/flowise/dist/utils/buildAgentGraph.js:405:15)
    at async utilBuildAgentResponse (/usr/local/lib/node_modules/flowise/dist/utils/buildChatflow.js:428:31)
    at async utilBuildChatflow (/usr/local/lib/node_modules/flowise/dist/utils/buildChatflow.js:195:20)
    at async Object.buildChatflow (/usr/local/lib/node_modules/flowise/dist/services/predictions/index.js:9:28)
    at async createPrediction (/usr/local/lib/node_modules/flowise/dist/controllers/predictions/index.js:82:37)
```

When examining the `ToolCallingAgentOutputParser` span in Langfuse, I see that the LLM returns `next: "multi_tool_use.parallel"` which Flowise can't properly handle (which is why this error is getting thrown).

What's even weirder, is that I've explicitly passed into the `ChatOpenAI` node the `Additional Parameter` of `BaseOptions` value of:
```json
{ "parallel_tool_calls": false }
```

... But that doesn't seem to make a difference at all.

I'm thinking what Flowise could do to account for this is:
1) Do _not_ cache any LLM response where `multi_tool_use.parallel` is present in the payload
2) Catch this error and silently _retry_ for up to X times (default of 3, but you can specify an X value in an optional `Additional Parameter`)

**Comment by dkindlund** [comment]
Oh, and if you're having trouble reproducing this error, you need to make your prompt _very_ complicated.  It seems that the LLM will switch to `multi_tool_use.parallel` if and only if the original prompt is complex (not simple).
