### ISSUE TITLE
[BUG] ChatOllama: LLM run errored with error: "llama3 does not support tools"

### ISSUE THREAD

**Issue by iotcloudarchitect** [FlowiseAI/Flowise#3361]
**Describe the bug**
When running the flow and providing an animal name as example, no result is generated and logs of flowise provide the following error:

`
2024-10-15 17:56:26 2024-10-15 15:56:26 [INFO]: [server]: Chatflow a20007d3-7ec1-42ef-a1b7-11abf61e7778_e42bfafa-d579-40ca-92ef-0b56876f87e4 added into ChatflowPool
2024-10-15 17:56:26 2024-10-15 15:56:26 [VERBOSE]: [chain/start] [1:chain:LangGraph] Entering Chain run with input: {
2024-10-15 17:56:26   "input": ""
2024-10-15 17:56:26 }
2024-10-15 17:56:26 2024-10-15 15:56:26 [VERBOSE]: [chain/start] [1:chain:LangGraph > 2:chain:__start__] Entering Chain run with input: {
2024-10-15 17:56:26   "messages": [
2024-10-15 17:56:26     {
2024-10-15 17:56:26       "lc": 1,
2024-10-15 17:56:26       "type": "constructor",
2024-10-15 17:56:26       "id": [
2024-10-15 17:56:26         "langchain_core",
2024-10-15 17:56:26         "messages",
2024-10-15 17:56:26         "HumanMessage"
2024-10-15 17:56:26       ],
2024-10-15 17:56:26       "kwargs": {
2024-10-15 17:56:26         "content": "cat",
2024-10-15 17:56:26         "additional_kwargs": {},
2024-10-15 17:56:26         "response_metadata": {}
2024-10-15 17:56:26       }
2024-10-15 17:56:26     }
2024-10-15 17:56:26   ]
2024-10-15 17:56:26 }
2024-10-15 17:56:26 2024-10-15 15:56:26 [VERBOSE]: [chain/end] [1:chain:LangGraph > 2:chain:__start__] [0ms] Exiting Chain run with output: {}
2024-10-15 17:56:26 2024-10-15 15:56:26 [VERBOSE]: [chain/start] [1:chain:LangGraph > 3:chain:supervisor] Entering Chain run with input: {
2024-10-15 17:56:26   "messages": [
2024-10-15 17:56:26     {
2024-10-15 17:56:26       "lc": 1,
2024-10-15 17:56:26       "type": "constructor",
2024-10-15 17:56:26       "id": [
2024-10-15 17:56:26         "langchain_core",
2024-10-15 17:56:26         "messages",
2024-10-15 17:56:26         "HumanMessage"
2024-10-15 17:56:26       ],
2024-10-15 17:56:26       "kwargs": {
2024-10-15 17:56:26         "content": "cat",
2024-10-15 17:56:26         "additional_kwargs": {},
2024-10-15 17:56:26         "response_metadata": {}
2024-10-15 17:56:26       }
2024-10-15 17:56:26     }
2024-10-15 17:56:26   ],
2024-10-15 17:56:26   "next": null,
2024-10-15 17:56:26   "instructions": null,
2024-10-15 17:56:26   "team_members": null
2024-10-15 17:56:26 }
2024-10-15 17:56:26 2024-10-15 15:56:26 [VERBOSE]: [chain/start] [1:chain:LangGraph > 3:chain:supervisor > 4:chain:RunnableLambda] Entering Chain run with input: {
2024-10-15 17:56:26   "messages": [
2024-10-15 17:56:26     {
2024-10-15 17:56:26       "lc": 1,
2024-10-15 17:56:26       "type": "constructor",
2024-10-15 17:56:26       "id": [
2024-10-15 17:56:26         "langchain_core",
2024-10-15 17:56:26         "messages",
2024-10-15 17:56:26         "HumanMessage"
2024-10-15 17:56:26       ],
2024-10-15 17:56:26       "kwargs": {
2024-10-15 17:56:26         "content": "cat",
2024-10-15 17:56:26         "additional_kwargs": {},
2024-10-15 17:56:26         "response_metadata": {}
2024-10-15 17:56:26       }
2024-10-15 17:56:26     }
2024-10-15 17:56:26   ],
2024-10-15 17:56:26   "next": null,
2024-10-15 17:56:26   "instructions": null,
2024-10-15 17:56:26   "team_members": null
2024-10-15 17:56:26 }
2024-10-15 17:56:26 2024-10-15 15:56:26 [VERBOSE]: [chain/start] [1:chain:LangGraph > 3:chain:supervisor > 4:chain:RunnableLambda > 5:chain:RunnableSequence] Entering Chain run with input: {
2024-10-15 17:56:26   "messages": [
2024-10-15 17:56:26     {
2024-10-15 17:56:26       "lc": 1,
2024-10-15 17:56:26       "type": "constructor",
2024-10-15 17:56:26       "id": [
2024-10-15 17:56:26         "langchain_core",
2024-10-15 17:56:26         "messages",
2024-10-15 17:56:26         "HumanMessage"
2024-10-15 17:56:26       ],
2024-10-15 17:56:26       "kwargs": {
2024-10-15 17:56:26         "content": "cat",
2024-10-15 17:56:26         "additional_kwargs": {},
2024-10-15 17:56:26         "response_metadata": {}
2024-10-15 17:56:26       }
2024-10-15 17:56:26     }
2024-10-15 17:56:26   ],
2024-10-15 17:56:26   "next": null,
2024-10-15 17:56:26   "instructions": null,
2024-10-15 17:56:26   "team_members": null,
2024-10-15 17:56:26   "signal": {}
2024-10-15 17:56:26 }
2024-10-15 17:56:26 2024-10-15 15:56:26 [VERBOSE]: [chain/start] [1:chain:LangGraph > 3:chain:supervisor > 4:chain:RunnableLambda > 5:chain:RunnableSequence > 6:prompt:ChatPromptTemplate] Entering Chain run with input: {
2024-10-15 17:56:26   "messages": [
2024-10-15 17:56:26     {
2024-10-15 17:56:26       "lc": 1,
2024-10-15 17:56:26       "type": "constructor",
2024-10-15 17:56:26       "id": [
2024-10-15 17:56:26         "langchain_core",
2024-10-15 17:56:26         "messages",
2024-10-15 17:56:26         "HumanMessage"
2024-10-15 17:56:26       ],
2024-10-15 17:56:26       "kwargs": {
2024-10-15 17:56:26         "content": "cat",
2024-10-15 17:56:26         "additional_kwargs": {},
2024-10-15 17:56:26         "response_metadata": {}
2024-10-15 17:56:26       }
2024-10-15 17:56:26     }
2024-10-15 17:56:26   ],
2024-10-15 17:56:26   "next": null,
2024-10-15 17:56:26   "instructions": null,
2024-10-15 17:56:26   "team_members": null,
2024-10-15 17:56:26   "signal": {}
2024-10-15 17:56:26 }
2024-10-15 17:56:26 2024-10-15 15:56:26 [VERBOSE]: [chain/end] [1:chain:LangGraph > 3:chain:supervisor > 4:chain:RunnableLambda > 5:chain:RunnableSequence > 6:prompt:ChatPromptTemplate] [1ms] Exiting Chain run with output: {
2024-10-15 17:56:26   "lc": 1,
2024-10-15 17:56:26   "type": "constructor",
2024-10-15 17:56:26   "id": [
2024-10-15 17:56:26     "langchain_core",
2024-10-15 17:56:26     "prompt_values",
2024-10-15 17:56:26     "ChatPromptValue"
2024-10-15 17:56:26   ],
2024-10-15 17:56:26   "kwargs": {
2024-10-15 17:56:26     "messages": [
2024-10-15 17:56:26       {
2024-10-15 17:56:26         "lc": 1,
2024-10-15 17:56:26         "type": "constructor",
2024-10-15 17:56:26         "id": [
2024-10-15 17:56:26           "langchain_core",
2024-10-15 17:56:26           "messages",
2024-10-15 17:56:26           "SystemMessage"
2024-10-15 17:56:26         ],
2024-10-15 17:56:26         "kwargs": {
2024-10-15 17:56:26           "content": "You are a supervisor tasked with managing a conversation between the following workers: storyauthor, headlineauthor.\nGiven the following user request, respond with the worker to act next.\nEach worker will perform a task and respond with their results and status.\nWhen finished, respond with FINISH.\nSelect strategically to minimize the number of steps taken.\nYou start wit the StoryAuthor and pass the result to the HeadlineAuthor.",
2024-10-15 17:56:26           "additional_kwargs": {},
2024-10-15 17:56:26           "response_metadata": {}
2024-10-15 17:56:26         }
2024-10-15 17:56:26       },
2024-10-15 17:56:26       {
2024-10-15 17:56:26         "lc": 1,
2024-10-15 17:56:26         "type": "constructor",
2024-10-15 17:56:26         "id": [
2024-10-15 17:56:26           "langchain_core",
2024-10-15 17:56:26           "messages",
2024-10-15 17:56:26           "HumanMessage"
2024-10-15 17:56:26         ],
2024-10-15 17:56:26         "kwargs": {
2024-10-15 17:56:26           "content": "cat",
2024-10-15 17:56:26           "additional_kwargs": {},
2024-10-15 17:56:26           "response_metadata": {}
2024-10-15 17:56:26         }
2024-10-15 17:56:26       },
2024-10-15 17:56:26       {
2024-10-15 17:56:26         "lc": 1,
2024-10-15 17:56:26         "type": "constructor",
2024-10-15 17:56:26         "id": [
2024-10-15 17:56:26           "langchain_core",
2024-10-15 17:56:26           "messages",
2024-10-15 17:56:26           "HumanMessage"
2024-10-15 17:56:26         ],
2024-10-15 17:56:26         "kwargs": {
2024-10-15 17:56:26           "content": "Given the conversation above, who should act next? Or should we FINISH? Select one of: FINISH, storyauthor, headlineauthor",
2024-10-15 17:56:26           "additional_kwargs": {},
2024-10-15 17:56:26           "response_metadata": {}
2024-10-15 17:56:26         }
2024-10-15 17:56:26       }
2024-10-15 17:56:26     ]
2024-10-15 17:56:26   }
2024-10-15 17:56:26 }
2024-10-15 17:56:26 2024-10-15 15:56:26 [VERBOSE]: [llm/start] [1:chain:LangGraph > 3:chain:supervisor > 4:chain:RunnableLambda > 5:chain:RunnableSequence > 7:llm:ChatOllama] Entering LLM run with input: {
2024-10-15 17:56:26   "messages": [
2024-10-15 17:56:26     [
2024-10-15 17:56:26       {
2024-10-15 17:56:26         "lc": 1,
2024-10-15 17:56:26         "type": "constructor",
2024-10-15 17:56:26         "id": [
2024-10-15 17:56:26           "langchain_core",
2024-10-15 17:56:26           "messages",
2024-10-15 17:56:26           "SystemMessage"
2024-10-15 17:56:26         ],
2024-10-15 17:56:26         "kwargs": {
2024-10-15 17:56:26           "content": "You are a supervisor tasked with managing a conversation between the following workers: storyauthor, headlineauthor.\nGiven the following user request, respond with the worker to act next.\nEach worker will perform a task and respond with their results and status.\nWhen finished, respond with FINISH.\nSelect strategically to minimize the number of steps taken.\nYou start wit the StoryAuthor and pass the result to the HeadlineAuthor.",
2024-10-15 17:56:26           "additional_kwargs": {},
2024-10-15 17:56:26           "response_metadata": {}
2024-10-15 17:56:26         }
2024-10-15 17:56:26       },
2024-10-15 17:56:26       {
2024-10-15 17:56:26         "lc": 1,
2024-10-15 17:56:26         "type": "constructor",
2024-10-15 17:56:26         "id": [
2024-10-15 17:56:26           "langchain_core",
2024-10-15 17:56:26           "messages",
2024-10-15 17:56:26           "HumanMessage"
2024-10-15 17:56:26         ],
2024-10-15 17:56:26         "kwargs": {
2024-10-15 17:56:26           "content": "cat",
2024-10-15 17:56:26           "additional_kwargs": {},
2024-10-15 17:56:26           "response_metadata": {}
2024-10-15 17:56:26         }
2024-10-15 17:56:26       },
2024-10-15 17:56:26       {
2024-10-15 17:56:26         "lc": 1,
2024-10-15 17:56:26         "type": "constructor",
2024-10-15 17:56:26         "id": [
2024-10-15 17:56:26           "langchain_core",
2024-10-15 17:56:26           "messages",
2024-10-15 17:56:26           "HumanMessage"
2024-10-15 17:56:26         ],
2024-10-15 17:56:26         "kwargs": {
2024-10-15 17:56:26           "content": "Given the conversation above, who should act next? Or should we FINISH? Select one of: FINISH, storyauthor, headlineauthor",
2024-10-15 17:56:26           "additional_kwargs": {},
2024-10-15 17:56:26           "response_metadata": {}
2024-10-15 17:56:26         }
2024-10-15 17:56:26       }
2024-10-15 17:56:26     ]
2024-10-15 17:56:26   ]
2024-10-15 17:56:26 }
2024-10-15 17:56:26 2024-10-15 15:56:26 [VERBOSE]: [llm/error] [1:chain:LangGraph > 3:chain:supervisor > 4:chain:RunnableLambda > 5:chain:RunnableSequence > 7:llm:ChatOllama] [26ms] LLM run errored with error: "llama3 does not support tools\n\nResponseError: llama3 does not support tools\n    at checkOk (/usr/local/lib/node_modules/flowise/node_modules/ollama/dist/shared/ollama.9c897541.cjs:72:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async post (/usr/local/lib/node_modules/flowise/node_modules/ollama/dist/shared/ollama.9c897541.cjs:120:3)\n    at async Ollama.processStreamableRequest (/usr/local/lib/node_modules/flowise/node_modules/ollama/dist/shared/ollama.9c897541.cjs:253:22)\n    at async ChatOllama._streamResponseChunks (/usr/local/lib/node_modules/flowise/node_modules/@langchain/ollama/dist/chat_models.cjs:455:32)\n    at async ChatOllama._generate (/usr/local/lib/node_modules/flowise/node_modules/@langchain/ollama/dist/chat_models.cjs:407:26)\n    at async Promise.allSettled (index 0)\n    at async ChatOllama._generateUncached (/usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/language_models/chat_models.cjs:177:29)\n    at async ChatOllama.invoke (/usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/language_models/chat_models.cjs:61:24)\n    at async RunnableSequence.invoke (/usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:1146:33)\n    at async agentNode (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/multiagents/Supervisor/Supervisor.js:608:24)\n    at async RunnableLambda.supervisorNode [as func] (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/multiagents/Supervisor/Supervisor.js:582:57)\n    at async /usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:1513:34"
2024-10-15 17:56:26 2024-10-15 15:56:26 [VERBOSE]: [chain/error] [1:chain:LangGraph > 3:chain:supervisor > 4:chain:RunnableLambda > 5:chain:RunnableSequence] [29ms] Chain run errored with error: "llama3 does not support tools\n\nResponseError: llama3 does not support tools\n    at checkOk (/usr/local/lib/node_modules/flowise/node_modules/ollama/dist/shared/ollama.9c897541.cjs:72:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async post (/usr/local/lib/node_modules/flowise/node_modules/ollama/dist/shared/ollama.9c897541.cjs:120:3)\n    at async Ollama.processStreamableRequest (/usr/local/lib/node_modules/flowise/node_modules/ollama/dist/shared/ollama.9c897541.cjs:253:22)\n    at async ChatOllama._streamResponseChunks (/usr/local/lib/node_modules/flowise/node_modules/@langchain/ollama/dist/chat_models.cjs:455:32)\n    at async ChatOllama._generate (/usr/local/lib/node_modules/flowise/node_modules/@langchain/ollama/dist/chat_models.cjs:407:26)\n    at async Promise.allSettled (index 0)\n    at async ChatOllama._generateUncached (/usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/language_models/chat_models.cjs:177:29)\n    at async ChatOllama.invoke (/usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/language_models/chat_models.cjs:61:24)\n    at async RunnableSequence.invoke (/usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:1146:33)\n    at async agentNode (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/multiagents/Supervisor/Supervisor.js:608:24)\n    at async RunnableLambda.supervisorNode [as func] (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/multiagents/Supervisor/Supervisor.js:582:57)\n    at async /usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:1513:34"
2024-10-15 17:56:26 2024-10-15 15:56:26 [VERBOSE]: [chain/error] [1:chain:LangGraph > 3:chain:supervisor > 4:chain:RunnableLambda] [30ms] Chain run errored with error: "Aborted!\n\nError: Aborted!\n    at agentNode (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/multiagents/Supervisor/Supervisor.js:614:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async RunnableLambda.supervisorNode [as func] (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/multiagents/Supervisor/Supervisor.js:582:57)\n    at async /usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:1513:34"
2024-10-15 17:56:26 2024-10-15 15:56:26 [VERBOSE]: [chain/error] [1:chain:LangGraph > 3:chain:supervisor] [30ms] Chain run errored with error: "Aborted!\n\nError: Aborted!\n    at agentNode (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/multiagents/Supervisor/Supervisor.js:614:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async RunnableLambda.supervisorNode [as func] (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/multiagents/Supervisor/Supervisor.js:582:57)\n    at async /usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:1513:34"
2024-10-15 17:56:26 2024-10-15 15:56:26 [VERBOSE]: [chain/error] [1:chain:LangGraph] [33ms] Chain run errored with error: "Aborted!\n\nError: Aborted!\n    at agentNode (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/multiagents/Supervisor/Supervisor.js:614:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async RunnableLambda.supervisorNode [as func] (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/multiagents/Supervisor/Supervisor.js:582:57)\n    at async /usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:1513:34"
`

**To Reproduce**
Run the flow providing animal.

**Expected behavior**
Flow should utlize Ollama as the chat model agent.

**Screenshots**

**Flow**
Have look at the exported flow, there is no magic.

**Setup**

-   Installation: Flowise (Port 3000) & Ollama (Port 11434) running inside a Docker container having a shared network.
-   Flowise Version 2.1.2 & Ollama Version 0.3.13
-   OS: macOS
-   Browser: Microsoft Edge

[Offer Generator Agents.json](https://github.com/user-attachments/files/17381327/Offer.Generator.Agents.json)

**Comment by iotcloudarchitect** [comment]
![Uploading flowise.png…]()

**Comment by iotcloudarchitect** [comment]
![flowise](https://github.com/user-attachments/assets/6b2a303e-5e7e-4f4b-8097-6f9628568e9e)

**Comment by iotcloudarchitect** [comment]
Docker Compose:

`
version: '3.1'

services:
    flowise:
        image: flowiseai/flowise
        restart: always
        environment:
            - PORT=${PORT}
            - CORS_ORIGINS=${CORS_ORIGINS}
            - IFRAME_ORIGINS=${IFRAME_ORIGINS}
            - FLOWISE_USERNAME=${FLOWISE_USERNAME}
            - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
            - FLOWISE_FILE_SIZE_LIMIT=${FLOWISE_FILE_SIZE_LIMIT}
            - DEBUG=${DEBUG}
            - DATABASE_PATH=${DATABASE_PATH}
            - DATABASE_TYPE=${DATABASE_TYPE}
            - DATABASE_PORT=${DATABASE_PORT}
            - DATABASE_HOST=${DATABASE_HOST}
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_USER=${DATABASE_USER}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_SSL=${DATABASE_SSL}
            - DATABASE_SSL_KEY_BASE64=${DATABASE_SSL_KEY_BASE64}
            - APIKEY_PATH=${APIKEY_PATH}
            - SECRETKEY_PATH=${SECRETKEY_PATH}
            - FLOWISE_SECRETKEY_OVERWRITE=${FLOWISE_SECRETKEY_OVERWRITE}
            - LOG_LEVEL=${LOG_LEVEL}
            - LOG_PATH=${LOG_PATH}
            - BLOB_STORAGE_PATH=${BLOB_STORAGE_PATH}
            - DISABLE_FLOWISE_TELEMETRY=${DISABLE_FLOWISE_TELEMETRY}
            - MODEL_LIST_CONFIG_JSON=${MODEL_LIST_CONFIG_JSON}
        ports:
            - '${PORT}:${PORT}'
        networks:
            - app-network 
        volumes:
            - ~/.flowise:/root/.flowise
        entrypoint: /bin/sh -c "sleep 3; flowise start"
    ollama:
        image: ollama/ollama
        environment:
            - OLLAMA_DEBUG=1
        ports:
            - "${OLLAMA_PORT}:${OLLAMA_PORT}"
        networks:
            - app-network 
        volumes:
            - ~/.ollama:/root/.ollama
        restart: always
networks:
  app-network:
    driver: bridge

`

**Comment by HenryHengZJ** [comment]
llama 3 does not support tools - as mentioned its not able to run multi agents, because under the hood there are tools involved. So you will have to use llama 3.2 https://ollama.com/library/llama3.2

**Comment by iotcloudarchitect** [comment]
Many thanks for clarification.
Llama 3.2 works!
