### ISSUE TITLE
[BUG] MongoNotConnectedError: Flowise API Fails Until Message is Sent to Chatbot

### ISSUE THREAD

**Issue by ArkMaster123** [FlowiseAI/Flowise#3404]
The Flowise API throws a MongoNotConnectedError when attempting to interact with MongoDB, specifically during operations such as fetching chat history. The error persists until a message is sent via the chatbot interface, which seems to re-establish the MongoDB connection, allowing the API to function correctly. This suggests that MongoDB connections may be timing out or not persisting correctly for API requests.

To Reproduce

1.Deploy a Flowise instance (version 2.1.2) with MongoDB for chat history storage.
2. Call an API endpoint that involves MongoDB operations, such as fetching chat history.
3. Observe the MongoNotConnectedError in the logs.
4. Send a message via the Flowise chatbot.
5. After the message is sent, the API resumes working correctly.

Expected behavior
Flowise should maintain a stable connection to MongoDB, allowing API requests involving MongoDB operations to work without requiring a chatbot message to re-establish the connection.

Setup

Installation: Deployed via Render
Flowise Version: 2.1.2
OS: (Specify the operating system, e.g., Ubuntu on Render)
Browser: N/A (API calls made programmatically)

**Additional context**
Add any other context about the problem here:

2024-10-23 10:44:39 [ERROR]: [server]: Error: Client must be connected before running operations
MongoNotConnectedError: Client must be connected before running operations
    at executeOperationAsync (/usr/src/node_modules/.pnpm/mongodb@6.3.0_gcp-metadata@6.1.0_encoding@0.1.13__socks@2.8.1/node_modules/mongodb/lib/operations/execute_operation.js:23:19)
    at /usr/src/node_modules/.pnpm/mongodb@6.3.0_gcp-metadata@6.1.0_encoding@0.1.13__socks@2.8.1/node_modules/mongodb/lib/operations/execute_operation.js:12:45
    at maybeCallback (/usr/src/node_modules/.pnpm/mongodb@6.3.0_gcp-metadata@6.1.0_encoding@0.1.13__socks@2.8.1/node_modules/mongodb/lib/utils.js:270:21)
    at executeOperation (/usr/src/node_modules/.pnpm/mongodb@6.3.0_gcp-metadata@6.1.0_encoding@0.1.13__socks@2.8.1/node_modules/mongodb/lib/operations/execute_operation.js:12:38)
    at FindCursor._initialize (/usr/src/node_modules/.pnpm/mongodb@6.3.0_gcp-metadata@6.1.0_encoding@0.1.13__socks@2.8.1/node_modules/mongodb/lib/cursor/find_cursor.js:55:73)
    at [kInit] (/usr/src/node_modules/.pnpm/mongodb@6.3.0_gcp-metadata@6.1.0_encoding@0.1.13__socks@2.8.1/node_modules/mongodb/lib/cursor/abstract_cursor.js:450:38)
    at next (/usr/src/node_modules/.pnpm/mongodb@6.3.0_gcp-metadata@6.1.0_encoding@0.1.13__socks@2.8.1/node_modules/mongodb/lib/cursor/abstract_cursor.js:510:32)
    at FindCursor.next (/usr/src/node_modules/.pnpm/mongodb@6.3.0_gcp-metadata@6.1.0_encoding@0.1.13__socks@2.8.1/node_modules/mongodb/lib/cursor/abstract_cursor.js:226:16)
    at Collection.findOne (/usr/src/node_modules/.pnpm/mongodb@6.3.0_gcp-metadata@6.1.0_encoding@0.1.13__socks@2.8.1/node_modules/mongodb/lib/collection.js:267:34)
    at BufferMemoryExtended.getChatMessages (/usr/src/packages/components/dist/nodes/memory/MongoDBMemory/MongoDBMemory.js:128:48)
    at RunnableLambda.chat_history [as func] (/usr/src/packages/components/dist/nodes/agents/ToolAgent/ToolAgent.js:268:48)
    at /usr/src/node_modules/.pnpm/@langchain+core@0.2.18_langchain@0.2.11_@aws-sdk+client-s3@3.529.1_@aws-sdk+credential-provid_4p2zda2v3zalzl2nestlm24jli/node_modules/@langchain/core/dist/runnables/base.cjs:1599:44
    at MockAsyncLocalStorage.run (/usr/src/node_modules/.pnpm/@langchain+core@0.2.18_langchain@0.2.11_@aws-sdk+client-s3@3.529.1_@aws-sdk+credential-provid_4p2zda2v3zalzl2nestlm24jli/node_modules/@langchain/core/dist/singletons/index.cjs:12:16)
    at AsyncLocalStorageProvider.runWithConfig (/usr/src/node_modules/.pnpm/@langchain+core@0.2.18_langchain@0.2.11_@aws-sdk+client-s3@3.529.1_@aws-sdk+credential-provid_4p2zda2v3zalzl2nestlm24jli/node_modules/@langchain/core/dist/singletons/index.cjs:48:24)
    at output (/usr/src/node_modules/.pnpm/@langchain+core@0.2.18_langchain@0.2.11_@aws-sdk+client-s3@3.529.1_@aws-sdk+credential-provid_4p2zda2v3zalzl2nestlm24jli/node_modules/@langchain/core/dist/runnables/base.cjs:1597:64)
    at new Promise (<anonymous>)

**Comment by HenryHengZJ** [comment]
related: https://github.com/FlowiseAI/Flowise/issues/3115
