### ISSUE TITLE
[BUG] Vector search on Postgres does not work with ssl

### ISSUE THREAD

**Issue by jomach** [FlowiseAI/Flowise#3503]
**Describe the bug**
When I try to connect to postgres on Azure (Cosmos) I get: 

Error: vectorsService.upsertVector - Error: error: no pg_hba.conf entry for host "37.4.231.19", user "citus", database "citus", no encryption

**To Reproduce**
1. Create a new database on azure cosmos and select postgres api
2. Add on flowise the VectorStore Postgres
3. add sslmode=require

**Expected behavior**
Press the green button upsert vector database should work

**Screenshots**
<img width="1250" alt="image" src="https://github.com/user-attachments/assets/4bf52f85-3bc1-4e6e-84b8-461e7b368434">

**Logs**
2024-11-11 12:44:31 [ERROR]: [server]: Error: Error: error: no pg_hba.conf entry for host "37.4.231.19", user "citus", database "citus", no encryption
Error: Error: error: no pg_hba.conf entry for host "37.4.231.19", user "citus", database "citus", no encryption
    at buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:494:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async upsertVector (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:151:32)
    at async Object.upsertVectorMiddleware (/usr/local/lib/node_modules/flowise/dist/services/vectors/index.js:9:16)
    at async createInternalUpsert (/usr/local/lib/node_modules/flowise/dist/controllers/vectors/index.js:28:29)

Seems not to work

**Comment by sirsimonson** [comment]
Have you tried setting additional Configuration on the Postgres Node as such? 
![image](https://github.com/user-attachments/assets/b22e6e96-500c-4b8a-b84c-e05468f750c4)

**Comment by jomach** [comment]
@sirsimonson  no to be honest

**Comment by sirsimonson** [comment]
Worked for my SSL configured postgres flexible SQL server instance so I suggest you give it a try
