### ISSUE TITLE
[BUG] "chatollama" not working where chat ollama function present in previous versions was working 

### ISSUE THREAD

**Issue by tkondi** [FlowiseAI/Flowise#3572]
![image](https://github.com/user-attachments/assets/df9a60bc-ca51-48f8-a5b3-1c01a64be2bf)

I get fetch failed error:

2024-11-25 21:33:38 [ERROR]: [server]: Error: fetch failed    
TypeError: fetch failed        
    at node:internal/deps/undici/undici:12618:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async post (C:\Users\tkondi\AppData\Roaming\npm\node_modules\flowise\node_modules\ollama\dist\shared\ollama.6a7c6e0f.cjs:119:20)
    at async Ollama.processStreamableRequest (C:\Users\tkondi\AppData\Roaming\npm\node_modules\flowise\node_modules\ollama\dist\shared\ollama.6a7c6e0f.cjs:236:25)
    at async ChatOllama._streamResponseChunks (C:\Users\tkondi\AppData\Roaming\npm\node_modules\flowise\node_modules\@langchain\ollama\dist\chat_models.cjs:474:24)
    at async ChatOllama._streamIterator (C:\Users\tkondi\AppData\Roaming\npm\node_modules\flowise\node_modules\@langchain\ollama\node_modules\@langchain\core\dist\language_models\chat_models.cjs:92:34)
    at async ChatOllama.transform (C:\Users\tkondi\AppData\Roaming\npm\node_modules\flowise\node_modules\@langchain\ollama\node_modules\@langchain\core\dist\runnables\base.cjs:402:9)    
    at async wrapInputForTracing (C:\Users\tkondi\AppData\Roaming\npm\node_modules\flowise\node_modules\flowise-components\node_modules\@langchain\core\dist\runnables\base.cjs:267:30)   
    at async pipeGeneratorWithSetup (C:\Users\tkondi\AppData\Roaming\npm\node_modules\flowise\node_modules\flowise-components\node_modules\@langchain\core\dist\utils\stream.cjs:245:19)  
    at async StringOutputParser._transformStreamWithConfig (C:\Users\tkondi\AppData\Roaming\npm\node_modules\flowise\node_modules\flowise-components\node_modules\@langchain\core\dist\runnables\base.cjs:288:26)        
    at async StringOutputParserlowise\node_modules\flowise-components\node_modules\@langchain\core\dist\output_parsers\transform.cjs:36:9)
    at async RunnableSequence._streamIterator (C:\Users\tkondi\AppData\Roaming\npm\node_modules\flowise\node_modules\flowise-components\node_modules\@langchain\core\dist\runnables\base.cjs:1208:30)
    at async RunnableSequence.transform (C:\Users\tkondi\AppData\Roaming\npm\node_modules\flowise\node_modules\flowise-components\node_modules\@langchain\core\dist\runnables\base.cjs:394:9)
    at async RunnableBinding.transform (C:\Users\tkondi\AppData\Roaming\npm\node_modules\flowise\node_modules\flowise-components\node_modules\@langchain\core\dist\runnables\base.cjs:840:9)
    at async RunnableSequence._streamIterator (C:\Users\tkondi\AppData\Roaming\npm\node_modules\flowise\node_modules\flowise-components\node_modules\@langchain\core\dist\runnables\base.cjs:1208:30)
2024-11-25 21:36:48 [INFO]: ⬆️ POST /api/v1/node-config

**Comment by davide445** [comment]
I have the same problem, ollama is working fine on flowise with the embedding alone, testing with a downloaded llm got this error. Testing the llm only with ollama cli is working. Both ollama and flowise latest release
2024-12-07 20:00:42 [ERROR]: [server]: Error: fetch failed
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11372:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async post (/home/davide445/.nvm/versions/node/v18.18.2/lib/node_modules/flowise/node_modules/ollama/dist/shared/ollama.11c1a3a8.cjs:119:20)
    at async Ollama.processStreamableRequest (/home/davide445/.nvm/versions/node/v18.18.2/lib/node_modules/flowise/node_modules/ollama/dist/shared/ollama.11c1a3a8.cjs:236:25)
    at async ChatOllama._streamResponseChunks (/home/davide445/.nvm/versions/node/v18.18.2/lib/node_modules/flowise/node_modules/@langchain/ollama/dist/chat_models.cjs:754:24)
    at async ChatOllama._streamIterator (/home/davide445/.nvm/versions/node/v18.18.2/lib/node_modules/flowise/node_modules/@langchain/core/dist/language_models/chat_models.cjs:94:34)
    at async ChatOllama.transform (/home/davide445/.nvm/versions/node/v18.18.2/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:402:9)
    at async wrapInputForTracing (/home/davide445/.nvm/versions/node/v18.18.2/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:275:30)
    at async pipeGeneratorWithSetup (/home/davide445/.nvm/versions/node/v18.18.2/lib/node_modules/flowise/node_modules/@langchain/core/dist/utils/stream.cjs:270:19)
    at async StringOutputParser._transformStreamWithConfig (/home/davide445/.nvm/versions/node/v18.18.2/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:296:26)
    at async StringOutputParser.transform (/home/davide445/.nvm/versions/node/v18.18.2/lib/node_modules/flowise/node_modules/@langchain/core/dist/output_parsers/transform.cjs:36:9)
    at async RunnableSequence._streamIterator (/home/davide445/.nvm/versions/node/v18.18.2/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:1320:30)
    at async RunnableSequence.transform (/home/davide445/.nvm/versions/node/v18.18.2/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:402:9)
    at async RunnableBinding.transform (/home/davide445/.nvm/versions/node/v18.18.2/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:883:9)
    at async RunnableSequence._streamIterator (/home/davide445/.nvm/versions/node/v18.18.2/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:1320:30)

**Comment by davide445** [comment]
On my side I discovered how to solve the problem: instead of using http://localhost:11434 as Base URL I just needed to use http://127.0.0.1:11434

**Comment by abhiroop43** [comment]
is there a plan to fix this issue? The ollama Chat API is working fine. with curl.

**Comment by jacky0wl** [comment]
I'm noticing when sending a chat request that I hit 404 on ollama from flowise trying to request `/api/chat` and not `/api/generate` :
```log
[GIN] 2025/03/14 - 16:29:13 | 404 |      573.24µs |             ::1 | POST     "/api/chat"
[GIN] 2025/03/14 - 16:30:42 | 404 |      389.83µs |       127.0.0.1 | POST     "/api/chat"
```

**Comment by anticrusader** [comment]
> On my side I discovered how to solve the problem: instead of using http://localhost:11434 as Base URL I just needed to use http://127.0.0.1:11434

it solved the issue on my end. Thank you
