### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by meitokaeri** [FlowiseAI/Flowise#3583]
**Describe the bug**
When I click on Marketplaces on the [http://localhost:3000/] page, the browser shows a completely white screen. Additionally, when I click [CHAT] under chatflows, the same issue occurs.

I have tested this with both node-v18.20.5-x64 and node-v20.18.1-x64, but the problem persists in both versions.

**To Reproduce**

1. Go to 'http://localhost:3000/'
2. Click on 'Marketplaces'
3. See white screen
----------------------------------------------
1. Go to 'http://localhost:3000/'
2. Click on 'Chatflow'
3. Click on 'Chat'
4. See white screen

**Expected behavior**
I expected it to display the Marketplaces content or the Chatbot interface.

**Screenshots**
![001](https://github.com/user-attachments/assets/dbfc5b47-9811-4255-8c51-e1b65a064dc3)
[http://localhost:3000/] > [Chatflows] > [Chat]

![002](https://github.com/user-attachments/assets/6ab3745d-7b70-4543-8448-220ee4de9eba)
[http://localhost:3000/] > [Marketplaces]

**Setup**

-   Installation [npx flowise start]
-   Flowise Version [2.1.5]
-   OS: [Windows]
-   Browser [chrome, safari]

**Additional context**
I have also tested with **Node.js 23.3.0**, but the same issue occurs.

**Comment by PylotLight** [comment]
We also get this, but I assumed it was because we're doing some basepath rewrites for assets, but looks like its happening for other users?

**Comment by meitokaeri** [comment]
> We also get this, but I assumed it was because we're doing some basepath rewrites for assets, but looks like its happening for other users?

I encountered this issue the first time I installed Flowise on this computer. I plan to test it on another computer to see if it happens there as well.

**Comment by Pasceli** [comment]
I have exactly the same issue after installing flowise

**Comment by repetitioestmaterstudiorum** [comment]
Same for me. This error is not happening when using the same version (2.2.1) but the Docker version.

**Comment by PylotLight** [comment]
Can everyone paste the url they are accessing as well as the endpoint for the css/js assets in the head tag?
This is likely caused by assets not able to load is my guess

**Comment by erlebach** [comment]
This happens on my Mac M2 with Sequoia OS. I have the same problem with Safari, Chrome, and Brave (the latest version). The blank screen occurs when clicking on "Marketplace", and when using the "Chat" icon to start a conversation. Everything works within Docker, but unfortunately, in that case, I cannot use Ollama since `localhost:11434` is not accessible from within the Docker container using the `docker-compose.yml` file provided in the `Flowise` repository and the fact that I am a noobie in this area. Can anybody please help with explicit instructions?

**Comment by PylotLight** [comment]
@erlebach  Does using the simple docker run command to pull and run simple example from repo work vs the compose example?

**Comment by sroe001** [comment]
I am experiencing the same thing; any resolution?

**Comment by farbensan** [comment]
Same here... waiting for a solution also.

**Comment by Axeldrone** [comment]
Hi, I have the same problem, a white page on marketplaces. I am also waiting for solutions. Thanks.

**Comment by Pasceli** [comment]
I solved it by completely uninstalling everything, then following the method in this video:
https://youtu.be/nqAK_L66sIQ?si=WyYEBEUTalkiDSwH
There was a steep learning curve for me to install all the stuff because i am not a developer, but now I use Flowise and it works flawlessly.

**Comment by Axeldrone** [comment]
Thanks, but it did not help me. Could not install the longer version due to yarn installation, the shorter version did not open localhost3000. Get back through node.js installation, but  the screen is still white in marketplaces, and also when making chat flow 
and tap on the chat tab it goes white.

**Comment by Axeldrone** [comment]
Have resolved the issue by uninstalling the newest version of node.js and installing v20.18.1. All works now.

**Comment by Onyx808** [comment]
Im having the same issue, any fix other than reinstalling?

**Comment by Onyx808** [comment]
I installed node.js v20.18.1 as @Axeldrone said, and now it all works again, thanks!

**Comment by kojakster** [comment]
could fix it as well with using node.js v20.18.1 on my macbook  : thank you @Axeldrone

**Comment by Prakti-DO** [comment]
v20.18.1 fixed it for me aswell when i was using it 1-2 weeks ago. Now all of the sudden i get the white screen issue again on the same installation. So weird

**Comment by HenryHengZJ** [comment]
I was able to replicate the issue when doing `npm install -g flowise` on node 22, 23. When i open the About Flowise, I can see it actually installed 1.6.0 instead of the latest version (2.2.3)

Hence we are seeing the white screen.

![image](https://github.com/user-attachments/assets/64a98944-83ca-4be6-aae3-92e2d23b1ef9)

So I tried with `npm install -g flowise@2.2.3` and this fixes the issue.

**Comment by sudo-a13** [comment]
deprecate to flowise version 2.2.3 and node 20.18.2, that fixed it for me

**Comment by pierrecorsini** [comment]
[flowise@2.2.7-patch.1](https://github.com/FlowiseAI/Flowise/releases/tag/flowise%402.2.7-patch.1)

```
index-gS4G3Zvm.js:62 TypeError: Cannot read properties of undefined (reading 'map')
    at index-Dbxwj0ft.js:71:6213
    at Yp (index-gS4G3Zvm.js:62:24283)
    at fl (index-gS4G3Zvm.js:62:42409)
    at index-gS4G3Zvm.js:62:40726
    at P (index-gS4G3Zvm.js:47:1600)
    at MessagePort.X (index-gS4G3Zvm.js:47:1970)
Gv @ index-gS4G3Zvm.js:62
index-gS4G3Zvm.js:60 Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at index-Dbxwj0ft.js:71:6213
    at Yp (index-gS4G3Zvm.js:62:24283)
    at fl (index-gS4G3Zvm.js:62:42409)
    at index-gS4G3Zvm.js:62:40726
    at P (index-gS4G3Zvm.js:47:1600)
    at MessagePort.X (index-gS4G3Zvm.js:47:1970)
```

Optimized JS is:
` Y((l = b.data) == null ? void 0 : l.fileUploadSizeAndTypes.map(d => d.fileTypes).join(",")))`

Seems to point to :
https://github.com/FlowiseAI/Flowise/blame/b988cae58c75e1ca64decfe19e76e1ae79d6a704/packages/ui/src/views/chatmessage/ChatMessage.jsx#L255

Introduced in https://github.com/FlowiseAI/Flowise/commit/66acd0c0006a949e7e88418b3cc9beebccb06507

**Comment by timdonovanuk** [comment]
Still an issue in 2.2.8

**Comment by HenryHengZJ** [comment]
> Still an issue in 2.2.8.
> 
> Confirming that this works: deprecate to flowise version 2.2.3 and node 20.18.2. The drop from node 22.x to 20.x seems to have made it work.



> Using: [flowise@2.2.7-patch.1](https://github.com/FlowiseAI/Flowise/releases/tag/flowise%402.2.7-patch.1)
> 
> ```
> index-gS4G3Zvm.js:62 TypeError: Cannot read properties of undefined (reading 'map')
>     at index-Dbxwj0ft.js:71:6213
>     at Yp (index-gS4G3Zvm.js:62:24283)
>     at fl (index-gS4G3Zvm.js:62:42409)
>     at index-gS4G3Zvm.js:62:40726
>     at P (index-gS4G3Zvm.js:47:1600)
>     at MessagePort.X (index-gS4G3Zvm.js:47:1970)
> Gv @ index-gS4G3Zvm.js:62
> index-gS4G3Zvm.js:60 Uncaught TypeError: Cannot read properties of undefined (reading 'map')
>     at index-Dbxwj0ft.js:71:6213
>     at Yp (index-gS4G3Zvm.js:62:24283)
>     at fl (index-gS4G3Zvm.js:62:42409)
>     at index-gS4G3Zvm.js:62:40726
>     at P (index-gS4G3Zvm.js:47:1600)
>     at MessagePort.X (index-gS4G3Zvm.js:47:1970)
> ```
> 
> Optimized JS is: ` Y((l = b.data) == null ? void 0 : l.fileUploadSizeAndTypes.map(d => d.fileTypes).join(",")))`
> 
> Seems to point to : https://github.com/FlowiseAI/Flowise/blame/b988cae58c75e1ca64decfe19e76e1ae79d6a704/packages/ui/src/views/chatmessage/ChatMessage.jsx#L255
> 
> Introduced in [66acd0c](https://github.com/FlowiseAI/Flowise/commit/66acd0c0006a949e7e88418b3cc9beebccb06507)

If that's the case, I added a simple check to detect if its undefined, not sure will this solves the problem
