### ISSUE TITLE
[BUG] workflow failing with cant read property of undefined: label 

### ISSUE THREAD

**Issue by matiashegoburu** [FlowiseAI/Flowise#3597]
**Describe the bug**
When i run the attached agent flow, i get this error in the logs:

2024-11-22 18:39:47 [ERROR]: [server]: Error: Cannot read properties of undefined (reading 'label')
Error: Cannot read properties of undefined (reading 'label')
at buildAgentGraph (/usr/src/packages/server/dist/utils/buildAgentGraph.js:399:19)
at async utilBuildAgentResponse (/usr/src/packages/server/dist/utils/buildChatflow.js:428:31)
at async utilBuildChatflow (/usr/src/packages/server/dist/utils/buildChatflow.js:195:20)
at async createAndStreamInternalPrediction (/usr/src/packages/server/dist/controllers/internal-predictions/index.js:
33:29)
2024-11-22 18:39:47 [ERROR]: [server]: Error: Error buildAgentGraph - Cannot read properties of undefined (reading 'label')
Error: Error buildAgentGraph - Cannot read properties of undefined (reading 'label')
at buildAgentGraph (/usr/src/packages/server/dist/utils/buildAgentGraph.js:405:15)
at async utilBuildAgentResponse (/usr/src/packages/server/dist/utils/buildChatflow.js:428:31)
at async utilBuildChatflow (/usr/src/packages/server/dist/utils/buildChatflow.js:195:20)
at async createAndStreamInternalPrediction (/usr/src/packages/server/dist/controllers/internal-predictions/index.js:
33:29)
2024-11-22 18:39:47 [ERROR]: [server]: Error: Error buildAgentGraph - Cannot read properties of undefined (reading 'label')
Error: Error buildAgentGraph - Cannot read properties of undefined (reading 'label')
at utilBuildAgentResponse (/usr/src/packages/server/dist/utils/buildChatflow.js:534:15)
at async utilBuildChatflow (/usr/src/packages/server/dist/utils/buildChatflow.js:195:20)
at async createAndStreamInternalPrediction (/usr/src/packages/server/dist/controllers/internal-predictions/index.js:33:29)

**To Reproduce**
see attached agent flow
[title writer Agents.json](https://github.com/user-attachments/files/17943327/title.writer.Agents.json)

**Setup**
docker, flowise 2.1.5, os ubuntu 24.04

**Additional context**

**Comment by pooxid** [comment]
I have similar issue if not the same, I may be wrong but it seems something is wrong with the State. I tried with Gemini Flash in addition to ollama qwen2.5-coder:32b and its the same.

**Comment by SirLucian** [comment]
I think this is to do with override variables. You now have to configure them in your global variables, you can't just declare them on the fly. so I add a couple empty objects for things I want to declare in api calls and then in my chatflow config I can toggle them to allow for overwriting

**Comment by HenryHengZJ** [comment]
fix: https://github.com/FlowiseAI/Flowise/pull/3585

should be released in next version
