### ISSUE TITLE
[BUG] Error buildAgentGraph - Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by Vinci-virtuoso** [FlowiseAI/Flowise#3772]
**Describe the bug**
This flow is not running I am using Leons video to build a sequential agent

**To Reproduce**
Load the below json file to observe the flow
[Shopify Agent Agents.json](https://github.com/user-attachments/files/18254418/Shopify.Agent.Agents.json)

**Expected behavior**
This flow should work as expected using Leon Youtube video
https://www.youtube.com/watch?v=6LbvgTbS0BE
**Screenshots**
![Screenshot 2024-12-26 183120](https://github.com/user-attachments/assets/502999e6-f602-4bc1-9964-fb1c78ae1804)

**Setup**

-   Installation 
-   Flowise  running docker locally from github repo
-   OS: Windows
-   Browser Brave

Error traces:
2024-12-26 18:31:08 Error: Error buildAgentGraph - Cannot read properties of undefined (reading 'name')
2024-12-26 18:31:08     at utilBuildAgentResponse (/usr/src/packages/server/dist/utils/buildChatflow.js:549:15)
2024-12-26 18:31:08     at async utilBuildChatflow (/usr/src/packages/server/dist/utils/buildChatflow.js:196:20)
2024-12-26 18:31:08     at async createAndStreamInternalPrediction (/usr/src/packages/server/dist/controllers/internal-predictions/index.js:33:29)

**Comment by HenryHengZJ** [comment]
The `Loop To` name must be a valid agent node name within the canvas. For example, if you have "AgentA" as the Loop To name, your canvas must have the LLM Node or Agent Node with the name "AgentA"
