### ISSUE TITLE
[BUG] Error when trying to access local Ollama model outside of Flowise container

### ISSUE THREAD

**Issue by javismiles** [FlowiseAI/Flowise#3783]
1 - I launch Flowise Docker container
2 - Ollama is installed in my machine and can be accessed as usual on its port 11434

In Flowise I build a super simple workflow, basically
a Tool Agent node with:
- ChatOllama node as input to the Tool Calling Chat Model
- Serp API node input to Tools
- Buffer Memory node input to Memory
- Memory Cache node input to cache of ChatOllama node
that's all

3 - I set the base URL of the ChatOllama node to
http://host.docker.internal:11434/
so that it accesses my local ollama outside of the docker container

4- That url works well , if I go to it on a browser I see the "ollama is running".

5. Now when I run the chat in Flowise I get this strange message:

json: cannot unmarshal string into Go struct field ChatRequest.tools of type api.Tool

No matter what I do, no matter what ollama model I select, I tried tons of them, I always get the same error message

All of this I did it on a modern 2024 Windows 11 Laptop, and installed everything from scratch on 29th December 2024

Note: By the way, if I do the same with n8n, it works all well, that's how I know that accessing my local ollama models through http://host.docker.internal:11434/ works 100% well, because with n8n works perfect, but it fails with flowise

thank you for any help

![flowiseerror](https://github.com/user-attachments/assets/a79545a3-c90b-4c78-8bd0-0cca594226aa)

**Comment by HenryHengZJ** [comment]
thats the first time Im seeing this error.. which version of Flowise are you on? does it happen with another model? I'd suggest try a simple conversation chain: 
![image](https://github.com/user-attachments/assets/e2c91478-06a9-4704-b1d2-2ba200bb8486)

**Comment by HenryHengZJ** [comment]
works for me when using tool agent: 
![image](https://github.com/user-attachments/assets/398d02ba-be78-452d-844f-41d0a1189d28)

**Comment by mkmatzat** [comment]
> thats the first time Im seeing this error.. which version of Flowise are you on? does it happen with another model? I'd suggest try a simple conversation chain: 

I build exactly this chain (attached below). But my error is different. When I hit the chat icon, the screen went blank. In the browser console I see:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at index-qqT5J-RG.js:71:6213
    at zp (index-7IT9aGXw.js:62:24283)
    at fl (index-7IT9aGXw.js:62:42409)
    at index-7IT9aGXw.js:62:40726
    at P (index-7IT9aGXw.js:47:1600)
    at MessagePort.q (index-7IT9aGXw.js:47:1970)
```

But when I ran the curl command for this flow I got an answer from the model by the flow:

```
>curl http://localhost:3000/api/v1/prediction/3b0c61f3-63b1-453f-a496-a738c8c363cb \
     -X POST \
     -d '{"question": "Hey, how are you?"}' \
     -H "Content-Type: application/json"
{"text":"I'm functioning within optimal parameters, thank you for asking! My systems are up-to-date, and I've been processing an enormous amount of information since my last update in December 2023. It's great to be chatting with you!\n\nBy the way, did you know that I'm based on a large language model architecture, specifically a variant of transformer-based models? These models have revolutionized natural language processing and are used in various applications, including chatbots like me.\n\nHow about you? How's your day going so far?","question":"Hey, how are you?","chatId":"94d0dc25-1fc2-4f6f-ad0e-c876753ea11f","chatMessageId":"b1add089-ffcb-4fbd-a8ec-4e4cdf3f7506","sessionId":"94d0dc25-1fc2-4f6f-ad0e-c876753ea11f","memoryType":"Buffer Memory"}%  
```                     
So I think, my ollama server works ok and pulls the model specified in the Flowise ollama widget when the curl request is perfomred.

So what is my problem here?

[Ollama Chat Bot Chatflow.json](https://github.com/user-attachments/files/18322788/Ollama.Chat.Bot.Chatflow.json)

**Comment by kitsune7** [comment]
I'm having the same issue as @mkmatzat ☝🏻

**Comment by mkmatzat** [comment]
It seems it is a platform issue. 

The issue I had reported before happened on a Mac OS (v15.2)  machine.
If I start Flowise on a Windows 11 machine in the console with

> npx flowise start 

and reference the ollama LLM server running on the Mac - then everything works fine.

![Image](https://github.com/user-attachments/assets/e87f9c66-9c33-46c7-8a0a-175af6afc01c)

But if I connect from the Windows machine the Flowise instance on the Mac, it fails in any browser on the Windows machine as well.

The Flowise version on 

- Mac:  **1.6.0 flowise@2.2.4** (python3 v3.11.9cmd)
- Windows 11: **2.0.1 flowise@2.2.4** (python v3.12.2)

Could the Python version makes the difference?

**Comment by mkmatzat** [comment]
I solved the issue for me by running Flowise on Docker.Desktop on my Mac OS system, which works fine.
I assume the mix of the native installed components like Python, NodeJS, etc. causes my initial issue. 
I will try to install much as possible on Docker to avoid conflicting libraries for future required components.
