### ISSUE TITLE
[BUG] CSV Document Loader - Blob is not defined

### ISSUE THREAD

**Issue by mrchris2000** [FlowiseAI/Flowise#482]
Flowise version - 1.2.13

Run using 'npx flowise start' from admin terminal on Windows 11.

**Describe the bug**
Added a CSV document file loader and wired it in to an in memory vector store with the intention of querying the CSV data.
When run the following error is output to the terminal:

```
 ReferenceError: Blob is not defined
    at Csv_DocumentLoaders.init (C:\Users\c_hag\AppData\Roaming\npm\node_modules\flowise\node_modules\flowise-components\dist\nodes\documentloaders\Csv\Csv.js:60:26)
    at buildLangchain (C:\Users\c_hag\AppData\Roaming\npm\node_modules\flowise\dist\utils\index.js:212:72)
    at async App.processPrediction (C:\Users\c_hag\AppData\Roaming\npm\node_modules\flowise\dist\index.js:611:44)
    at async C:\Users\c_hag\AppData\Roaming\npm\node_modules\flowise\dist\index.js:362:13
```

I think this is a reasonable flow, but I admit I'm new to this, so it could be a flow issue perhaps?
![image](https://github.com/FlowiseAI/Flowise/assets/5471394/9c582347-c99f-443c-992b-39345f9301c7)

**Comment by HenryHengZJ** [comment]
can you check if you have node >= 18.15.0? `node -v`

**Comment by mrchris2000** [comment]
That resolved it thanks - for some reason I was defaulting to 16.x.

I dropped in a Character splitter for ',' with chunk size 1000 but its consistently giving wrong answers.
From reading around it looks like CSV and langchain is quite a weak story, I'd probably have more luck dumping the CSV into SQLite and using SQL queries so I'll try that next I guess.
Thanks for the assistance.
