### ISSUE TITLE
[BUG] Marketplace tab not loading

### ISSUE THREAD

**Issue by harlev** [FlowiseAI/Flowise#493]
**Describe the bug**
After update from [flowise@1.2.13](https://github.com/FlowiseAI/Flowise/releases/tag/flowise%401.2.13) to [flowise@1.2.14](https://github.com/FlowiseAI/Flowise/releases/tag/flowise%401.2.14) Clicking on the "Marketplace" tab results in an empty page

**Comment by chungyau97** [comment]
Hi @harlev, I would like to ask some questions before we proceed.

1. Is Flowise `Hosted` or `Local`?
2. You're running on `yarn`, `npx` or `docker`?

**Comment by harlev** [comment]
Hi @chungyau97
I am running a local install. I was unig npx. Basically followed the vanilla instructions on the README page.
I installed the 1.2.13 on my machine and on an EC2 machine. Then upgraded both by running `npm install` again, and got the issue on both.
Eventually I just started from a clean install to avoid the issue.

**Comment by chungyau97** [comment]
I'm not able to replicate your error using [quick-start](https://github.com/flowiseai/flowise#quick-start) guide
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/7ab34861-be89-45c9-9c7c-170be5f6ba8a)

For upgrading, I believe you need to use `npm install -g flowise` instead of `npm install`
Then spin up Flowise with `npx flowise start`

If you're running on using [setup](https://github.com/flowiseai/flowise#setup) guide and using `yarn dev`
Remember to complete steps 6
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/e235c072-ef9b-4827-b6e9-755a74bda1cc)

**Comment by HenryHengZJ** [comment]
@harlev feel free to reopen if you're still having issue.

**Comment by dharmaduraiTech** [comment]
I'm also facing same issue even after upgrading flowise


**_index-CPHl8PIk.js:1 TypeError: t[r].usecases is not iterable (cannot read property undefined)
    at index-CPHl8PIk.js:1:9434
    at Wp (index-BEPqkojn.js:62:24283)
    at fl (index-BEPqkojn.js:62:42409)
    at index-BEPqkojn.js:62:40726
    at P (index-BEPqkojn.js:47:1600)
    at MessagePort.q (index-BEPqkojn.js:47:1970)
index-BEPqkojn.js:62 TypeError: t.categories.join is not a function
    at H (index-CPHl8PIk.js:1:7777)
    at Array.filter (<anonymous>)
    at as (index-CPHl8PIk.js:1:13826)
    at my (index-BEPqkojn.js:60:19539)
    at Wv (index-BEPqkojn.js:62:3139)
    at iE (index-BEPqkojn.js:62:44833)
    at nE (index-BEPqkojn.js:62:39790)
    at Z4 (index-BEPqkojn.js:62:39718)
    at fp (index-BEPqkojn.js:62:39570)
    at Qv (index-BEPqkojn.js:62:35934)
index-BEPqkojn.js:62 Uncaught TypeError: t.categories.join is not a function
    at H (index-CPHl8PIk.js:1:7777)
    at Array.filter (<anonymous>)
    at as (index-CPHl8PIk.js:1:13826)
    at my (index-BEPqkojn.js:60:19539)
    at Wv (index-BEPqkojn.js:62:3139)
    at iE (index-BEPqkojn.js:62:44833)
    at nE (index-BEPqkojn.js:62:39790)
    at Z4 (index-BEPqkojn.js:62:39718)
    at fp (index-BEPqkojn.js:62:39570)
    at Qv (index-BEPqkojn.js:62:35934)_*
