### ISSUE TITLE
[BUG] 400 while using Zep with a Conversation Chain

### ISSUE THREAD

**Issue by nsvrana** [FlowiseAI/Flowise#563]
**Describe the bug**
I receive a 400 error when using a Conversation Chain with self-hosted Zep for memory management. The chat works for 1-2 rounds of conversation prior to failing, I believe it fails when it attempts to retrieve the memory. 

My setup has Flowise and Zep in a docker-compose together, running in the same environment.

**To Reproduce**
Set-up a conversation chain with Zep, have a conversation.

**Logs**
_Flowise Logs_
```
2023-07-17 22:13:34 [INFO]: ⬆️ POST /api/v1/chatmessage/089d50be-994f-440c-9bf2-951307b368a2
2023-07-17 22:13:34 [INFO]: ⬆️ POST /api/v1/internal-prediction/089d50be-994f-440c-9bf2-951307b368a2
2023-07-17 22:13:34 [INFO]: [server]: Chatflow 089d50be-994f-440c-9bf2-951307b368a2 added into ChatflowPool
2023-07-17 22:13:50 [INFO]: ⬆️ POST /api/v1/chatmessage/089d50be-994f-440c-9bf2-951307b368a2
2023-07-17 22:15:16 [INFO]: ⬆️ POST /api/v1/chatmessage/089d50be-994f-440c-9bf2-951307b368a2
2023-07-17 22:15:16 [INFO]: ⬆️ POST /api/v1/internal-prediction/089d50be-994f-440c-9bf2-951307b368a2
2023-07-17 22:15:16 [INFO]: [server]: Chatflow 089d50be-994f-440c-9bf2-951307b368a2 added into ChatflowPool
2023-07-17 22:15:16 [ERROR]: [server]: Error: Got an unexpected status code: 400
Error: Got an unexpected status code: 400
    at /usr/local/lib/node_modules/flowise/node_modules/@getzep/zep-js/dist/zep-client.js:65:31
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/flowise/node_modules/@getzep/zep-js/dist/zep-client.js:29:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

_Zep Logs_
```
time="2023-07-17T22:13:34Z" level=info msg="URL/api/v1/sessions/6b9c363c-a942-456e-8d54-392fee4d1e43/memory" bytes=10 category=router duration=1302535 duration_display=1.302735ms method=GET proto=HTTP/1.1 remote_ip=IP status_code=404
time="2023-07-17T22:13:50Z" level=info msg="URL/api/v1/sessions/6b9c363c-a942-456e-8d54-392fee4d1e43/memory" bytes=2 category=router duration=4900803 duration_display=4.901225ms method=POST proto=HTTP/1.1 remote_ip=IP status_code=200
23-07-17T22:15:16Z" level=info msg="URL/api/v1/sessions/6b9c363c-a942-456e-8d54-392fee4d1e43/memory" bytes=3319 category=router duration=918782 duration_display="919.151µs" method=GET proto=HTTP/1.1 remote_ip=IP status_code=200
time="2023-07-17T22:15:16Z" level=error msg="strconv.Atoi: parsing \"NaN\": invalid syntax"
time="2023-07-17T22:15:16Z" level=info msg="URL/api/v1/sessions/6b9c363c-a942-456e-8d54-392fee4d1e43/memory?lastn=NaN" bytes=44 category=router duration=73573 duration_display="73.781µs" method=GET proto=HTTP/1.1 remote_ip=IP status_code=400

```

**Comment by nsvrana** [comment]
It looks like at some point Zep's API was updated to require "lastn" messages. Flowise is not passing that resulting in the invalid parsing. I believe you need to update the Zep package in package.json to work with the latest Zep server.

**Comment by nsvrana** [comment]
I have figured it out - the Zep block I was using was created in version 1.2.14 and has been updated in 1.2.15. The block was no automatically updated, so it was missing the "Size" parameter resulting in an error where the variable was missing.

**Request:** Blocks should either be updated automatically or there needs to be a UI indicator when an obsolete version of a block is being used in a flow.
