### ISSUE TITLE
[BUG] - ENOENT: no such file or directory, open ''

### ISSUE THREAD

**Issue by christianbradley** [FlowiseAI/Flowise#640]
**Describe the bug**
No such file or directory '' when trying chat.

**To Reproduce**
start flowise
create a conversation chain w chatopenai and buffer memory
save
try to chat

**Expected behavior**
chat works

**Screenshots**
<img width="1477" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/145614/77d701a1-944b-40d9-9f22-2146ad3eec81">

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**
-   Installation [e.g. docker, `npx flowise start`, `yarn start`]
-   Flowise Version [e.g. 1.2.11]
-   OS: [e.g. macOS, Windows, Linux]
-   Browser [e.g. chrome, safari]

**Additional context**
Logs:

2023-07-28 19:14:20 [INFO]: Starting Flowise...
2023-07-28 19:14:20 [INFO]: ⚡️ [server]: Flowise Server is listening at 3000
2023-07-28 19:14:20 [INFO]: 📦 [server]: Data Source has been initialized!
2023-07-28 19:20:17 [INFO]: ⬆️ POST /api/v1/credentials
2023-07-28 19:21:03 [INFO]: ⬆️ POST /api/v1/chatflows
2023-07-28 19:21:08 [INFO]: ⬆️ POST /api/v1/chatmessage/8523ad62-b583-419b-b121-5dcd5131853c
2023-07-28 19:21:08 [INFO]: ⬆️ POST /api/v1/internal-prediction/8523ad62-b583-419b-b121-5dcd5131853c
2023-07-28 19:21:08 [ERROR]: Error: Error: ENOENT: no such file or directory, open ''
Error: Error: Error: ENOENT: no such file or directory, open ''
    at getCredentialData (/Users/xyz/.npm/_npx/8b95a19c5c9c8708/node_modules/flowise-components/dist/src/utils.js:448:15)
    at async ChatOpenAI_ChatModels.init (/Users/xyz/.npm/_npx/8b95a19c5c9c8708/node_modules/flowise-components/dist/nodes/chatmodels/ChatOpenAI/ChatOpenAI.js:130:32)
    at async buildLangchain (/Users/xyz/.npm/_npx/8b95a19c5c9c8708/node_modules/flowise/dist/utils/index.js:220:50)
    at async App.processPrediction (/Users/xyz/.npm/_npx/8b95a19c5c9c8708/node_modules/flowise/dist/index.js:841:44)
    at async /Users/xyz/.npm/_npx/8b95a19c5c9c8708/node_modules/flowise/dist/index.js:557:13
2023-07-28 19:21:08 [ERROR]: [server]: Error: Error: Error: Error: ENOENT: no such file or directory, open ''
Error: Error: Error: Error: ENOENT: no such file or directory, open ''
    at buildLangchain (/Users/xyz/.npm/_npx/8b95a19c5c9c8708/node_modules/flowise/dist/utils/index.js:230:19)
    at async App.processPrediction (/Users/xyz/.npm/_npx/8b95a19c5c9c8708/node_modules/flowise/dist/index.js:841:44)
    at async /Users/xyz/.npm/_npx/8b95a19c5c9c8708/node_modules/flowise/dist/index.js:557:13
2023-07-28 19:21:08 [INFO]: ⬆️ POST /api/v1/chatmessage/8523ad62-b583-419b-b121-5dcd5131853c

**Comment by HenryHengZJ** [comment]
Is this on Docker?

**Comment by HenryHengZJ** [comment]
issue should be resolved now. simply pull the latest docker image or reinstall flowise if using npx

**Comment by pgm-norbert** [comment]
After reinstalling flowise, now Im getting this: 

2023-07-29 10:23:07 [INFO]: Starting Flowise...
2023-07-29 10:23:07 [INFO]: ⚡️ [server]: Flowise Server is listening at 3000
2023-07-29 10:23:07 [INFO]: 📦 [server]: Data Source has been initialized!
2023-07-29 10:23:18 [INFO]: ⬆️ POST /api/v1/chatmessage/bf389282-df6e-4847-9d0a-a8c0efe92571
2023-07-29 10:23:18 [INFO]: ⬆️ POST /api/v1/internal-prediction/bf389282-df6e-4847-9d0a-a8c0efe92571
Error: Malformed UTF-8 data
    at Object.stringify (/usr/local/lib/node_modules/flowise/node_modules/crypto-js/core.js:523:24)
    at WordArray.init.toString (/usr/local/lib/node_modules/flowise/node_modules/crypto-js/core.js:278:38)
    at decryptCredentialData (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/src/utils.js:425:41)
    at async getCredentialData (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/src/utils.js:448:41)
    at async OpenAIEmbedding_Embeddings.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/embeddings/OpenAIEmbedding/OpenAIEmbedding.js:57:32)
    at async buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:220:50)
    at async App.processPrediction (/usr/local/lib/node_modules/flowise/dist/index.js:843:44)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:559:13
2023-07-29 10:23:18 [ERROR]: Error: Credentials could not be decrypted.
Error: Error: Credentials could not be decrypted.
    at getCredentialData (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/src/utils.js:452:15)
    at async OpenAIEmbedding_Embeddings.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/embeddings/OpenAIEmbedding/OpenAIEmbedding.js:57:32)
    at async buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:220:50)
    at async App.processPrediction (/usr/local/lib/node_modules/flowise/dist/index.js:843:44)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:559:13
2023-07-29 10:23:18 [ERROR]: [server]: Error: Error: Error: Credentials could not be decrypted.
Error: Error: Error: Credentials could not be decrypted.
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:230:19)
    at async App.processPrediction (/usr/local/lib/node_modules/flowise/dist/index.js:843:44)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:559:13
2023-07-29 10:23:18 [INFO]: ⬆️ POST /api/v1/chatmessage/bf389282-df6e-4847-9d0a-a8c0efe92571

**Comment by HenryHengZJ** [comment]
just delete the credential, and recreate a new one

**Comment by pgm-norbert** [comment]
Yes, jumped the gun, all works now

**Comment by wuyabing** [comment]
我也遇到了这个问题，使用的版本是1.3.2自己起的前端，也是报这个错误，删除了credential，新建也是不行，知道什么原因吗 @pgm-norbert @HenryHengZJ

**Comment by prashantbhudwal** [comment]
Getting the same error again @HenryHengZJ. Did everything mentioned here. Updated to latest and re-added the credentials. Using npm to install.

2023-08-16 10:20:23 [ERROR]: Error: Error: ENOENT: no such file or directory, open ''
Error: Error: Error: ENOENT: no such file or directory, open ''

**Comment by HenryHengZJ** [comment]
If you are using NPM installation, try specify the `SECRETKEY_PATH`, for example: `npx flowise start --SECRETKEY_PATH=<your-path>`, this will be the path where encryption key is stored. Normally, if not specified, a default path will be used, which works for me if I was just using `npx flowise start`
https://docs.flowiseai.com/migration-guide/v1.3.0-migration-guide

**Comment by all4five** [comment]
> If you are using NPM installation, try specify the `SECRETKEY_PATH`, for example: `npx flowise start --SECRETKEY_PATH=<your-path>`, this will be the path where encryption key is stored. Normally, if not specified, a default path will be used, which works for me if I was just using `npx flowise start` https://docs.flowiseai.com/migration-guide/v1.3.0-migration-guide

Can you give me an example if what to write into <your-path> I also get the same issue, and as a novice I'm not sure how the path/which path should be entered here.  

I tried <npx flowise start --SECRETKEY_PATH=/root/.flowise>  but it only this error occurs:

2023-08-18 18:05:40 [INFO]: Starting Flowise...
2023-08-18 18:05:40 [INFO]: ⚡️ [server]: Flowise Server is listening at 3000
2023-08-18 18:05:40 [INFO]: 📦 [server]: Data Source has been initialized!
2023-08-18 18:05:41 [ERROR]: ❌ [server]: Error during Data Source initialization: ENOENT: no such file or directory, open '/root/.flowise/encryption.key'
Error: ENOENT: no such file or directory, open '/root/.flowise/encryption.key'


https://docs.flowiseai.com/migration-guide/v1.3.0-migration-guide was no help for me sadly.

**Comment by adolfousier** [comment]
I was able to solve this issue by setting up a variable NODE_VERSION=18.15.0 but also increasing RAM from 512mb to 2gb, now everything is working fine on render/railway with node or docker.

Deployed on render.com and railway.app, also deployed as node and docker just for testing purposes, everything working fine for now.
