### ISSUE TITLE
[BUG] local qna is not working.

### ISSUE THREAD

**Issue by gaord** [FlowiseAI/Flowise#665]
**Describe the bug**
Use marketplace Local QaN template and fill in as below screenshot:

Both localAI containers for embedding and models are running well.

.env has debug and log level set to debug. Log is not very much helpful. here is docker container log when asking a question:
2023-07-31 13:46:28 [INFO]: ⬆️ POST /api/v1/chatmessage/d4fae657-1e0b-40fe-bd22-54bb09ab9c3a
2023-07-31 13:46:28 [INFO]: ⬆️ POST /api/v1/internal-prediction/d4fae657-1e0b-40fe-bd22-54bb09ab9c3a
2023-07-31 13:48:05 [ERROR]: Request failed with status code 500
Error: Request failed with status code 500
    at createError (/usr/local/lib/node_modules/flowise/node_modules/openai/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/flowise/node_modules/openai/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/flowise/node_modules/openai/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-07-31 13:48:05 [ERROR]: [server]: Error: Error: Request failed with status code 500
Error: Error: Request failed with status code 500
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:230:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async App.processPrediction (/usr/local/lib/node_modules/flowise/dist/index.js:843:44)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:559:13
2023-07-31 13:48:05 [INFO]: ⬆️ POST /api/v1/chatmessage/d4fae657-1e0b-40fe-bd22-54bb09ab9c3a 

**To Reproduce**

**Expected behavior**
the flow should be working or logs could have helpful information about where goes wrong with the configuration.

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/9567937/ef6d765a-7fda-48d9-9c7a-f25538b8aa8c)

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**
-   use docker-compose to bring it up: local llm model,local embedding model
-   flowise/1.3.2 linux-x64 node-v18.17.0
-   OS: [ Windows]
-   Browser [safari]

**Additional context**

**Comment by HenryHengZJ** [comment]
if you look at logs from LocalAI, its possible that it has hung up, thats why causing 500 error. I've had couple of scenarios like this where my LocalAI eats up all docker memory and then returning 500

**Comment by gaord** [comment]
it turns out the embedding model are not properly installed. Anyway, It would be great to omit more informative logs upon the problem.
