### ISSUE TITLE
[BUG] Error with Retreival QA chain and Chain Tool

### ISSUE THREAD

**Issue by mahmoudsorf** [FlowiseAI/Flowise#708]
**Describe the bug**

getting this error when using Retreival QA chain and Chain Tool.
But the error is not coming on every execution.

2023-08-07 11:03:22 [INFO]: [server]: Chatflow ee504980-0f27-4098-9360-7a33903c9f68 added into ChatflowPool
2023-08-07 11:03:26 [ERROR]: [server]: Error: input values have 1 keys, you must specify an input key or pass only 1 key as input
Error: input values have 1 keys, you must specify an input key or pass only 1 key as input
    at getInputValue (/root/.nvm/versions/node/v20.4.0/lib/node_modules/flowise/node_modules/langchain/dist/memory/base.cjs:25:15)
    at BufferMemory.saveContext (/root/.nvm/versions/node/v20.4.0/lib/node_modules/flowise/node_modules/langchain/dist/memory/chat_memory.cjs:40:75)
    at ConversationalRetrievalQAChain.call (/root/.nvm/versions/node/v20.4.0/lib/node_modules/flowise/node_modules/langchain/dist/chains/base.cjs:106:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConversationalRetrievalQAChain.run (/root/.nvm/versions/node/v20.4.0/lib/node_modules/flowise/node_modules/langchain/dist/chains/base.cjs:59:30)
    at async ChainTool.call (/root/.nvm/versions/node/v20.4.0/lib/node_modules/flowise/node_modules/langchain/dist/tools/base.cjs:32:22)
    at async /root/.nvm/versions/node/v20.4.0/lib/node_modules/flowise/node_modules/langchain/dist/agents/executor.cjs:104:23
    at async Promise.all (index 0)
    at async AgentExecutor._call (/root/.nvm/versions/node/v20.4.0/lib/node_modules/flowise/node_modules/langchain/dist/agents/executor.cjs:100:30)
    at async AgentExecutor.call (/root/.nvm/versions/node/v20.4.0/lib/node_modules/flowise/node_modules/langchain/dist/chains/base.cjs:90:28)

**Comment by HenryHengZJ** [comment]
can you share the flow you're using?

**Comment by Utkarshkapil** [comment]
add content-type : application/json header should fix it if u are using chatfloow endpoint
