### ISSUE TITLE
[BUG]: Facing issue in executing tool of template get_stock_movers

### ISSUE THREAD

**Issue by Vikson97** [FlowiseAI/Flowise#721]
**Describe the bug**
I was trying to execute the tool functionality but getting following error, Also checked code but not able to find proper point of error.
pls suggest where i am doing wrong with my flow.

**Expected behavior**
I have changed the api cred in tool code but still its giving some zod object error.

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/49556518/d837348b-70b1-4f70-a819-4db6e7c325e2)

![image](https://github.com/FlowiseAI/Flowise/assets/49556518/d46bdd5b-515c-4c03-9854-2d279ad26ca4)

**Error**
[2.35s] Chain run errored with error: "[\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"object\",\n    \"received\": \"string\",\n    \"path\": [],\n    \"message\": \"Expected object, received string\"\n  }\n]"
2023-08-10 12:12:52 [ERROR]: [server]: Error: [
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "string",
    "path": [],
    "message": "Expected object, received string"
  }
]
ZodError: [
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "string",
    "path": [],
    "message": "Expected object, received string"
  }
]
    at get error [as error] (/home/admin1/workspace/LLM/Flowise/node_modules/zod/lib/types.js:43:31)
    at ZodObject.parseAsync (/home/admin1/workspace/LLM/Flowise/node_modules/zod/lib/types.js:164:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DynamicStructuredTool.call (/home/admin1/workspace/LLM/Flowise/node_modules/langchain/dist/tools/base.cjs:26:24)
    at async /home/admin1/workspace/LLM/Flowise/node_modules/langchain/dist/agents/executor.cjs:104:23
    at async Promise.all (index 0)

**Comment by chungyau97** [comment]
Hi @Vikson97,

Please change `Conversational Agent` to `OpenAI Function Agent`
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/2641d267-1d8f-4889-8245-dd10f92a6755)

**Comment by chungyau97** [comment]
Hi @Vikson97,

I'm not able to get `Azure ChatOpenAI` to work as well.

If you're experience in coding could you try to re-create this flow using coding with `LangChain JS` [library](https://github.com/hwchase17/langchainjs)?
