### ISSUE TITLE
[BUG] "conversation retrieval agent", Error: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by mahmoudsorf** [FlowiseAI/Flowise#724]
**Describe the bug**
Getting this Error from Time to Time while running the new "conversation retriaval agent".

2023-08-10 12:04:02 [ERROR]: [server]: Error: Cannot read properties of undefined (reading 'replace')
TypeError: Cannot read properties of undefined (reading 'replace')
    at OpenAIEmbeddings.embedQuery (/root/.nvm/versions/node/v20.4.0/lib/node_modules/flowise/node_modules/langchain/dist/embeddings/openai.cjs:141:46)
    at QdrantVectorStore.similaritySearch (/root/.nvm/versions/node/v20.4.0/lib/node_modules/flowise/node_modules/langchain/dist/vectorstores/base.cjs:69:90)
    at VectorStoreRetriever._getRelevantDocuments (/root/.nvm/versions/node/v20.4.0/lib/node_modules/flowise/node_modules/langchain/dist/vectorstores/base.cjs:38:33)
    at VectorStoreRetriever.getRelevantDocuments (/root/.nvm/versions/node/v20.4.0/lib/node_modules/flowise/node_modules/langchain/dist/schema/retriever.cjs:54:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DynamicTool.func (/root/.nvm/versions/node/v20.4.0/lib/node_modules/flowise/node_modules/langchain/dist/agents/toolkits/conversational_retrieval/tool.cjs:7:22)
    at async DynamicTool.call (/root/.nvm/versions/node/v20.4.0/lib/node_modules/flowise/node_modules/langchain/dist/tools/base.cjs:35:22)
    at async /root/.nvm/versions/node/v20.4.0/lib/node_modules/flowise/node_modules/langchain/dist/agents/executor.cjs:104:23
    at async Promise.all (index 0)
    at async AgentExecutor._call (/root/.nvm/versions/node/v20.4.0/lib/node_modules/flowise/node_modules/langchain/dist/agents/executor.cjs:100:30)

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/141017916/523e9e34-8f62-4180-91ec-4e9ba0499c0c)

**Comment by chungyau97** [comment]
Hi @mahmoudsorf,

Could you share your NodeJs version? `node --version`
Only happen in this Flow, does it occur on a simple flow such as in the marketplace?

**Comment by htsnet** [comment]
I am receiving the same error: TypeError: Cannot read properties of undefined (reading 'replace')

![image](https://github.com/FlowiseAI/Flowise/assets/9755885/0199e577-148e-43be-a6ef-c03f2d13072e)

**Comment by mahmoudsorf** [comment]
> 

node --version
v20.4.0

I did not try with simple flow but tried it with function agent and got the same error as well. Seems it is more related to Retriever Tool.

**Comment by chungyau97** [comment]
Hi @mahmou and @htsnet,

I'm not able to replicate the error you guys shown in my local setup with NodeJS `v20.5.1` shown below:

**Conversational Retrieval Agent**
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/0a1e4707-c4af-4c2a-94a4-9a7f663ac051)

**Conversational Retrieval QA Chain**
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/7be5b483-06a0-4620-9542-4333a65bd0ae)
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/b3308375-6f0d-4b37-9e76-b97780cdc4cd)

Could you guys troubleshooting with re-upsert documents with `Conversational Retrieval QA Chain` in marketplace?

**Comment by jacoblee93** [comment]
Hey folks, opened https://github.com/hwchase17/langchainjs/pull/2280 that should hopefully help with this.

I'll aim to merge it tomorrow morning, let me know if you see it again after the next release.

**Comment by HenryHengZJ** [comment]
> Hey folks, opened [hwchase17/langchainjs#2280](https://github.com/hwchase17/langchainjs/pull/2280) that should hopefully help with this.
> 
> I'll aim to merge it tomorrow morning, let me know if you see it again after the next release.

awesome thanks @jacoblee93 !

**Comment by htsnet** [comment]
I update my nodejs (>node --version v20.5.1) and run again "npm install flowise".
After that, I open Flowise again and it crashed (the cmd panel closes without warning). 
I need to review everyrhing

**Comment by BharathxD** [comment]
Hey guys, I've deployed this application to an EC2 instance (with Docker), but the error still persists
Any suggestions?
