### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by cbassoc3265** [FlowiseAI/Flowise#730]
Any advice would be appreciated:

I am using ChatLocalAI and trying to use/connect to a local Llama-2 llm. I keep getting the following error: Cannot read properties on defined (reading '0').

My log reads:

2023-08-10 22:33:13 [INFO]: ⬆️ POST /api/v1/chatmessage/5c7c9f51-ba1b-4cea-99f9-a4467ca40466
2023-08-10 22:33:13 [INFO]: ⬆️ POST /api/v1/internal-prediction/5c7c9f51-ba1b-4cea-99f9-a4467ca40466
2023-08-10 22:33:13 [INFO]: [server]: Chatflow 5c7c9f51-ba1b-4cea-99f9-a4467ca40466 added into ChatflowPool
2023-08-10 22:33:13 [ERROR]: [server]: Error: Cannot read properties of undefined (reading '0')
TypeError: Cannot read properties of undefined (reading '0')
    at OpenAIChat._call (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/llms/openai-chat.cjs:463:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async OpenAIChat._generate (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/llms/base.cjs:256:29)
    at async OpenAIChat._generateUncached (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/llms/base.cjs:133:22)
    at async LLMChain._call (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/chains/llm_chain.cjs:121:33)
    at async LLMChain.call (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/chains/base.cjs:98:28)
    at async runPrediction (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chains/LLMChain/LLMChain.js:132:29)
    at async LLMChain_Chains.run (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chains/LLMChain/LLMChain.js:77:21)
    at async App.processPrediction (/usr/local/lib/node_modules/flowise/dist/index.js:873:23)
2023-08-10 22:33:13 [INFO]: ⬆️ POST /api/v1/chatmessage/5c7c9f51-ba1b-4cea-99f9-a4467ca40466

**Additional context**
Works perfect with no errors when using OpenAI API as the llm.

My chatflow:

![Capture](https://github.com/FlowiseAI/Flowise/assets/6226309/0b829ac0-e708-453c-b9ca-607394b3035f)

**Setup**
-   Installation [`npx flowise start`]
-   Flowise Version [1.3.3] 
-   OS: [Linux - virtual server]
-   Browser [chrome]
- Latest 18+ version of Nodejs

**Comment by HenryHengZJ** [comment]
Sometimes this happens when your docker running LocalAI ran out of memory and shut down LocalAI container

**Comment by cbassoc3265** [comment]
I had a suspicion it was the docker-compose. I have more than enough memory, both RAM and SSD. Would you suggest me uninstalling LocalAI and re-installing it? If so, how do I start?

**Comment by HenryHengZJ** [comment]
I'd say first try and confirm if the LocalAI was the issue (as in the container was killed). You can try to increase the docker allocated memory, that might help
