### ISSUE TITLE
[BUG] MRKLAgent is not compatible with Custom Tool

### ISSUE THREAD

**Issue by zhengxiang5965** [FlowiseAI/Flowise#763]
**Describe the bug**
MRKLAgent is not compatible with Custom Tool

**To Reproduce**
Simultaneously using MRKLAgent and Custom Tool to form a stream

**Expected behavior**

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/31379313/44ae7c65-1eba-4eda-bcef-125d75d9d636)

**Flow**
**Setup**
-   Installation [e.g. docker, `npx flowise start`, `yarn start`]
-   Flowise Version [e.g. 1.2.11]
-   OS: [e.g. macOS, Windows, Linux]
-   Browser [e.g. chrome, safari]

**Additional context**

2023-08-14 05:14:53 [ERROR]: [server]: Error: [
{
"code": "invalid_type",
"expected": "object",
"received": "string",
"path": [],
"message": "Expected object, received string"
}
]
ZodError: [
{
"code": "invalid_type",
"expected": "object",
"received": "string",
"path": [],
"message": "Expected object, received string"
}
]
at get error [as error] (/usr/local/lib/node_modules/flowise/node_modules/zod/lib/types.js:43:31)
at ZodObject.parseAsync (/usr/local/lib/node_modules/flowise/node_modules/zod/lib/types.js:164:22)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async DynamicStructuredTool.call (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/tools/base.cjs:29:24)
at async /usr/local/lib/node_modules/flowise/node_modules/langchain/dist/agents/executor.cjs:104:23
at async Promise.all (index 0)
at async AgentExecutor._call (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/agents/executor.cjs:100:30)
at async AgentExecutor.call (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/chains/base.cjs:98:28)
at async MRKLAgentLLM_Agents.run (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/agents/MRKLAgentLLM/MRKLAgentLLM.js:42:24)
at async App.processPrediction (/usr/local/lib/node_modules/flowise/dist/index.js:873:23)
error: unexpected EOF

**Comment by chungyau97** [comment]
Hi @zhengxiang5965,

Try using `OpenAI Function Agent` node.

**Comment by zhengxiang5965** [comment]
> Hi @zhengxiang5965,
> 
> Try using `OpenAI Function Agent` node.

Why are you doing it so rigidly？

**Comment by zhengxiang5965** [comment]
The react prompt agent needs to be used in combination with "custom tools", and I believe it can be fully implemented technically, which has already been implemented in Langflow

@HenryHengZJ 

and there will be no problem with "expected object, received string". This problem seems to be easy to solve
