### ISSUE TITLE
[BUG] Error: Please set the REPLICATE_API_TOKEN environment variable

### ISSUE THREAD

**Issue by marckrenn** [FlowiseAI/Flowise#765]
**Describe the bug**
Replicate API Token appears not to be set correctly, neither via GUI (as Replicate Credential) nor via .env var

**To Reproduce**

1. Load Marketplaces/Replicate LLM example
2. Paste in API Key from Replicate
3. Set `REPLICATE_API_TOKEN=` .env var
4. Ask LLM any question

**Expected behavior**
Replicate API Token to be set via GUI or env var.

**Flow**
* Marketplaces/Replicate LLM
* Custom flow

**Setup**
-   Installation: docker
-   Flowise Version 1.3.3
-   OS: macOS
-   Browser chrome

**Additional context**
```
2023-08-14 12:05:51 Error: Please set the REPLICATE_API_TOKEN environment variable
2023-08-14 12:05:51     at new Replicate (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/llms/replicate.cjs:42:19)
2023-08-14 12:05:51     at Replicate_LLMs.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/llms/Replicate/Replicate.js:106:23)
2023-08-14 12:05:51     at async buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:220:50)
2023-08-14 12:05:51     at async App.processPrediction (/usr/local/lib/node_modules/flowise/dist/index.js:846:44)
2023-08-14 12:05:51     at async /usr/local/lib/node_modules/flowise/dist/index.js:559:13
2023-08-14 12:05:51 2023-08-14 10:05:51 [ERROR]: [server]: Error: Error: Please set the REPLICATE_API_TOKEN environment variable
2023-08-14 12:05:51 Error: Error: Please set the REPLICATE_API_TOKEN environment variable
2023-08-14 12:05:51     at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:230:19)
2023-08-14 12:05:51     at async App.processPrediction (/usr/local/lib/node_modules/flowise/dist/index.js:846:44)
2023-08-14 12:05:51     at async /usr/local/lib/node_modules/flowise/dist/index.js:559:13
```

**Comment by HenryHengZJ** [comment]
good spot! the template is not updated with latest credential change, will update that.

If you re-add it from the menu you should be able to create a new credential for Replicate:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/2d424e17-8b65-4b8b-8351-23997bd54b3c)

**Comment by marckrenn** [comment]
Hey Henry, thanks for your reply.

Thing is though, it doesn't work for me regardless – I get the exact same error with the updated node w/ the Credential picker.

It's supposed to be the [API token from this replicate page](https://replicate.com/account/api-tokens) (starting with `r8_`), correct?

**Comment by HenryHengZJ** [comment]
ahh noticed the bug, will fix that! thanks!

**Comment by HenryHengZJ** [comment]
PR opened - #769

**Comment by HenryHengZJ** [comment]
PR merged and will be pushed into next release

**Comment by marckrenn** [comment]
Amazing, thank you! :)
