### ISSUE TITLE
[BUG] Looking for a coder that can investigate an error I am getting.

### ISSUE THREAD

**Issue by cbassoc3265** [FlowiseAI/Flowise#788]
I am willing to pay, and can't find anyone who knows Flowise and LocalAI enough to do this. Here is my error:

2023-08-10 22:33:13 [INFO]: ⬆️ POST /api/v1/chatmessage/5c7c9f51-ba1b-4cea-99f9-a4467ca40466
2023-08-10 22:33:13 [INFO]: ⬆️ POST /api/v1/internal-prediction/5c7c9f51-ba1b-4cea-99f9-a4467ca40466
2023-08-10 22:33:13 [INFO]: [server]: Chatflow 5c7c9f51-ba1b-4cea-99f9-a4467ca40466 added into ChatflowPool
2023-08-10 22:33:13 [ERROR]: [server]: Error: Cannot read properties of undefined (reading '0')
TypeError: Cannot read properties of undefined (reading '0')
at OpenAIChat._call (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/llms/openai-chat.cjs:463:28)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Promise.all (index 0)
at async OpenAIChat._generate (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/llms/base.cjs:256:29)
at async OpenAIChat._generateUncached (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/llms/base.cjs:133:22)
at async LLMChain._call (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/chains/llm_chain.cjs:121:33)
at async [LLMChain.call](https://www.freelancer.com/users/l.php?url=http:%2F%2FLLMChain.call&sig=48a06cae7b6453af895ba2452497da855e122a489ce6d7f1cf8e74f2287e4485) (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/chains/base.cjs:98:28)
at async runPrediction (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chains/LLMChain/LLMChain.js:132:29)
at async [LLMChain_Chains.run](https://www.freelancer.com/users/l.php?url=http:%2F%2FLLMChain_Chains.run&sig=5366dec6a4cf4ac5e60329d463e6b88d512229d76b3e19269c5e734d9595cf72) (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chains/LLMChain/LLMChain.js:77:21)
at async App.processPrediction (/usr/local/lib/node_modules/flowise/dist/index.js:873:23)
2023-08-10 22:33:13 [INFO]: ⬆️ POST /api/v1/chatmessage/5c7c9f51-ba1b-4cea-99f9-a4467ca40466

**Comment by chungyau97** [comment]
Hi @cbassoc3265,

Could you share screenshot of your flow?
