### ISSUE TITLE
Error: Error: Error: ENOENT: no such file or directory, open ''

### ISSUE THREAD

**Issue by Iamtheoldman** [FlowiseAI/Flowise#863]
gave all my apis but got this error even on step by step guides

**Comment by chungyau97** [comment]
Hi @Iamtheoldman,

Could you tell me more on your setup before we proceed?
1. NodeJS version
2. OS
3. Cloud or Local

**Comment by Sal-ix** [comment]
Hi, 
Probably local. I faced a similar issue here. Missing SVGs in node_modules folder, when transitioning directly from 'yarn install' to 'yarn dev'. 
Running the 'yarn build' command fixed it.

**Comment by chungyau97** [comment]
Hey @Sal-ix, yup you have to `yarn build` showed on [step 4](https://docs.flowiseai.com/getting-started#setup)

**Comment by ondrejhadrava** [comment]
I had this issue as well. I resolved it by changing node version to v18.17.1 and reinstalling Flowise.

**Comment by platothefish** [comment]
I'm getting the same:

Node JS version: v18.17.1
Mac OS 13.5.2 (Mac M1)
Local

Terminal:

elizabethoconnell@oxfordreviewpro ~ % npx flowise start     
2023-09-09 13:23:38 [INFO]: Starting Flowise...
2023-09-09 13:23:38 [INFO]: ⚡️ [server]: Flowise Server is listening at 3000
2023-09-09 13:23:38 [INFO]: 📦 [server]: Data Source has been initialized!
2023-09-09 13:24:17 [INFO]: ❌ DELETE /api/v1/chatmessage/6673bdc7-a18a-4da4-8ad6-897484b8b161
2023-09-09 13:24:25 [INFO]: ⬆️ POST /api/v1/chatmessage/6673bdc7-a18a-4da4-8ad6-897484b8b161
2023-09-09 13:24:25 [INFO]: ⬆️ POST /api/v1/internal-prediction/6673bdc7-a18a-4da4-8ad6-897484b8b161
2023-09-09 13:24:25 [ERROR]: Error: Error: ENOENT: no such file or directory, open ''
Error: Error: Error: ENOENT: no such file or directory, open ''
    at getCredentialData (/Users/elizabethoconnell/.npm/_npx/8b95a19c5c9c8708/node_modules/flowise-components/dist/src/utils.js:467:15)
    at async ChatOpenAI_ChatModels.init (/Users/elizabethoconnell/.npm/_npx/8b95a19c5c9c8708/node_modules/flowise-components/dist/nodes/chatmodels/ChatOpenAI/ChatOpenAI.js:138:32)
    at async buildLangchain (/Users/elizabethoconnell/.npm/_npx/8b95a19c5c9c8708/node_modules/flowise/dist/utils/index.js:221:50)
    at async App.processPrediction (/Users/elizabethoconnell/.npm/_npx/8b95a19c5c9c8708/node_modules/flowise/dist/index.js:765:40)
    at async /Users/elizabethoconnell/.npm/_npx/8b95a19c5c9c8708/node_modules/flowise/dist/index.js:558:13
2023-09-09 13:24:25 [ERROR]: [server]: Error: Error: Error: Error: ENOENT: no such file or directory, open ''
Error: Error: Error: Error: ENOENT: no such file or directory, open ''
    at buildLangchain (/Users/elizabethoconnell/.npm/_npx/8b95a19c5c9c8708/node_modules/flowise/dist/utils/index.js:231:19)
    at async App.processPrediction (/Users/elizabethoconnell/.npm/_npx/8b95a19c5c9c8708/node_modules/flowise/dist/index.js:765:40)
    at async /Users/elizabethoconnell/.npm/_npx/8b95a19c5c9c8708/node_modules/flowise/dist/index.js:558:13
2023-09-09 13:24:25 [INFO]: ⬆️ POST /api/v1/chatmessage/6673bdc7-a18a-4da4-8ad6-897484b8b161

**Comment by platothefish** [comment]
Okay solved. I installed Homebrew /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" and then brew install node and then reinstalled Flowise, deleted and reinstalled the credentials and BINGO! It works.

**Comment by platothefish** [comment]
Ah so today I am back to Error: Error: Error: ENOENT: no such file or directory, open '' 

Poo!

**Comment by chungyau97** [comment]
Hey @platothefish, 

could you share a screenshot of your flow? 
In the mean time, try using these commands `sudo npm install -g flowise` and `sudo npx flowise start`.

**Comment by HenryHengZJ** [comment]
Added this PR - https://github.com/FlowiseAI/Flowise/pull/939 

You can overwrite the encryption key using env variable instead of the old way of storing the key into a local path, this should all the errors regarding credentials

**Comment by platothefish** [comment]
Okay I solved this by running "sudo npx flowise start"  and then closing it and re starting it with npx flowise start. Probably a permissions issue somewhere along the line.

**Comment by adolfousier** [comment]
I was able to fix this issue by setting up a variable NODE_VERSION=18.15.0 but also increasing RAM from 512mb to 2gb, now everything is working fine on render/railway with node or docker.
