### ISSUE TITLE
mrlkAgentLLM not found

### ISSUE THREAD

**Issue by umaar** [FlowiseAI/Flowise#9]
Getting this error

```js
Error: Node mrlkAgentLLM not found
    at /usr/local/lib/node_modules/flowise/dist/index.js:106:23
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:284:15
    at param (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:365:14)
    at param (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:421:3)
    at next (/usr/local/lib/node_modules/flowise/node_modules/express/lib/router/index.js:280:10)
```

<img width="956" alt="image" src="https://user-images.githubusercontent.com/381495/232116818-b1e5e0f0-e14e-4f21-946f-e3dd17dbe4bc.png">

**Comment by HenryHengZJ** [comment]
hey @umaar, if you do a reinstall or pull latest changes again, errors should goes away. Merged https://github.com/FlowiseAI/Flowise/pull/4 which fixed some of the typo and classes. Should be `MRLK` instead of `MRLK`

**Comment by umaar** [comment]
Working now!
