### ISSUE TITLE
Redis connection "Error: Error: Credentials could not be decrypted."

### ISSUE THREAD

**Issue by joelr45** [FlowiseAI/Flowise#915]
Hey guys, awesome tool! 

I am able to connect successfully to my hosted redis instance with no issue. However when I try and replicate the connection string using the redis node it gives me this error when trying to use the conversational retrieval node: 
**Error: Error: Credentials could not be decrypted.**

This works fine with buffer memory. Is there some other setting or env that needs to be set for using this?

With thanks!

**Comment by chungyau97** [comment]
Hi @joelr45, 

Seem like your encryption key got changed or replaced.
If you re-create the credential are you able to use Redis?

**Comment by joelr45** [comment]
Yeah I am looking at the logs, 

```
Error: Error: Credentials could not be decrypted.
    at getCredentialData (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/src/utils.js:467:15)
    at async OpenAIEmbedding_Embeddings.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/embeddings/OpenAIEmbedding/OpenAIEmbedding.js:57:32)
    at async buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:221:50)
    at async App.processPrediction (/usr/local/lib/node_modules/flowise/dist/index.js:765:40)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:558:13

```
and 

```
Error: Error: Error: Credentials could not be decrypted.
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:231:19)
    at async App.processPrediction (/usr/local/lib/node_modules/flowise/dist/index.js:765:40)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:558:13
```

What's the best method to re-create the encryption key? I tried changing the PASSPHRASE and redeploying. 

I have tried to delete the redis node, re-add input connection string, save and test the chat...

**Comment by joelr45** [comment]
I just realized its my postgres, something is affecting that...need to sort this out.

**Comment by chungyau97** [comment]
Hi @joelr45, make sure you setup `SECRETKEY_PATH ` on your envrionment that will lead to persistent disk.

Persistent Disk is a place that will not be deleted/modify during an update. Here's an example in [Render Persistent Disk docs](https://docs.flowiseai.com/deployment/render#persistent-disk)
