### ISSUE TITLE
[BUG] Unknown collation: 'utf8mb4_0900_ai_ci'

### ISSUE THREAD

**Issue by kientv** [FlowiseAI/Flowise#934]
I run docker in latest version

**Error log**
flowise-flowise-1  | yarn run v1.22.19
flowise-flowise-1  | $ run-script-os
flowise-flowise-1  | $ cd packages/server/bin && ./run start
flowise-flowise-1  | 2023-09-18 04:11:09 [INFO]: Starting Flowise...
flowise-flowise-1  | 2023-09-18 04:11:09 [INFO]: ⚡️ [server]: Flowise Server is listening at 3000
flowise-flowise-1  | 2023-09-18 04:11:09 [INFO]: 📦 [server]: Data Source has been initialized!
flowise-flowise-1  | 2023-09-18 04:11:09 [ERROR]: ❌ [server]: Error during Data Source initialization: ER_UNKNOWN_COLLATION: Unknown collation: 'utf8mb4_0900_ai_ci'
flowise-flowise-1  | QueryFailedError: ER_UNKNOWN_COLLATION: Unknown collation: 'utf8mb4_0900_ai_ci'
flowise-flowise-1  |     at Query.<anonymous> (/usr/src/packages/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:158:37)
flowise-flowise-1  |     at Query.<anonymous> (/usr/src/packages/node_modules/mysql/lib/Connection.js:526:10)
flowise-flowise-1  |     at Query._callback (/usr/src/packages/node_modules/mysql/lib/Connection.js:488:16)
flowise-flowise-1  |     at Sequence.end (/usr/src/packages/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
flowise-flowise-1  |     at Query.ErrorPacket (/usr/src/packages/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
flowise-flowise-1  |     at Protocol._parsePacket (/usr/src/packages/node_modules/mysql/lib/protocol/Protocol.js:291:23)
flowise-flowise-1  |     at Parser._parsePacket (/usr/src/packages/node_modules/mysql/lib/protocol/Parser.js:433:10)
flowise-flowise-1  |     at Parser.write (/usr/src/packages/node_modules/mysql/lib/protocol/Parser.js:43:10)
flowise-flowise-1  |     at Protocol.write (/usr/src/packages/node_modules/mysql/lib/protocol/Protocol.js:38:16)
flowise-flowise-1  |     at Socket.<anonymous> (/usr/src/packages/node_modules/mysql/lib/Connection.js:88:28)

**Comment by kientv** [comment]
It work fine after I changed mysql migration code to:    
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;` 

instead of  `CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`
