### ISSUE TITLE
[BUG]SQLITE_ERROR: no such column: ChatFlow.isPublic

### ISSUE THREAD

**Issue by temco** [FlowiseAI/Flowise#951]
when I installed flowise with `npm install flowise` after I'd uninstalled it and installed `flowise@1.2.1` for some tests, I could never run it any more. 

**To Reproduce**

1. `npm install flowise`
2. `npx flowise start`
3. See Errors

**Expected behavior**
at the very first time, I can run it with the former steps, build the flows and chat with the openai key 

**Screenshots**
```
2023-09-20 11:10:02 [INFO]: Starting Flowise...
2023-09-20 11:10:02 [INFO]: ⚡️ [server]: Flowise Server is listening at 3000
2023-09-20 11:10:02 [INFO]: 📦 [server]: Data Source has been initialized!
2023-09-20 11:10:03 [ERROR]: ❌ [server]: Error during Data Source initialization: SQLITE_ERROR: no such column: ChatFlow.isPublic
at handler (/Users/x/Downloads/Flowise/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:81:26)
    at replacement (/Users/x/Downloads/Flowise/node_modules/sqlite3/lib/trace.js:25:27)
    at Statement.errBack (/Users/x/Downloads/Flowise/node_modules/sqlite3/lib/sqlite3.js:15:21)
2023-09-20 11:09:49 [INFO]: Shutting down Flowise...
```

**Comment by chungyau97** [comment]
Hi @temco, please access your sqlite and delete the migration table
`C:\Users\username\.flowise\database.sqlite`
